In [1]:
# Standard library
import json
import os
import re
import warnings
from pathlib import Path

# Third-party libraries
import numpy as np
import pandas as pd
from matplotlib import colormaps
from matplotlib.colors import Normalize
from sklearn.preprocessing import MinMaxScaler
from tqdm import tqdm

# Show all rows and prevent column truncation
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 0)  # Auto-detect width

In [2]:
metric_groups = {
    "Feature_Relevance": [
        "anova_f_mean", 
        "mutual_info_mean"
    ],
    "Local_Overlap": [
        "pca_centroid_distance_pca_centroid_score", 
        "mahalanobis_class_distance_mean"
    ],
    "Boundary_Hardness": [
        "svm_margin_mean", 
        "class_proba_entropy_mean"
    ],
    "Global_Structure": [
        "intrinsic_dimensionality_intrinsic_dimensionality_percent", 
        "calinski_harabasz_calinski_harabasz_score"
    ],
    "Class_Distribution_Separation": [
        "class_confusion_entropy_confusion_entropy", 
        "class_imbalance_normalized_entropy"
    ]
}

In [3]:
# Invert selected metrics (where higher = easier)
metrics_to_invert = {
    "anova_f_mean",
    "mutual_info_mean",
    "svm_margin_mean",
    "pca_centroid_score",
    "mahalanobis_class_distance_mean",
    "calinski_harabasz_calinski_harabasz_score",
    "class_imbalance_normalized_entropy"
}

In [4]:
row_order = [
    "CIC_IDS_2017",
    "CIC_IOT_Dataset2023",
    "IoT_23",
    "IoT_Network_Intrusion_Macro",
    "IoT_Network_Intrusion_Micro",
    "KDD_Cup_1999",
    "UNSW_NB15",
    "BCCC_CIC-BCCC-NRC-ACI-IOT-2023",
    "BCCC_CIC-BCCC-NRC-Edge-IIoTSet-2022",
    "BCCC_CIC-BCCC-NRC-IoMT-2024",
    "BCCC_CIC-BCCC-NRC-IoT-2022",
    "BCCC_CIC-BCCC-NRC-IoT-2023-Original_Training_and_Testing",
    "BCCC_CIC-BCCC-NRC-IoT-HCRL-2019",
    "BCCC_CIC-BCCC-NRC-MQTTIoT-IDS-2020",
    "BCCC_CIC-BCCC-NRC-TONIoT-2021",
    "BCCC_CIC-BCCC-NRC-UQ-IOT-2022",
    "BoT_IoT_Macro",
    "BoT_IoT_Micro",
    "CICAPT_IIoT_Phase1_Macro", # nok (single-class)
    "CICAPT_IIoT_Phase1_Micro", # nok (single-class)
    "CICAPT_IIoT_Phase2_Macro",
    "CICAPT_IIoT_Phase2_Micro",
    "CICEVSE2024_EVSE-A_Macro",
    "CICEVSE2024_EVSE-A_Micro",
    "CICEVSE2024_EVSE-B_Macro",
    "CICEVSE2024_EVSE-B_Micro",
    "CICIoMT2024_Bluetooth",
    "CICIoMT2024_WiFi_and_MQTT",
    "CICIoV2024_Decimal_Macro",
    "CICIoV2024_Decimal_Micro",
    "EDGE-IIOTSET_DNN-EdgeIIoT",
    "EDGE-IIOTSET_ML-EdgeIIoT",
    "MQTT_IoT_IDS2020_BiflowFeatures",
    "MQTT_IoT_IDS2020_PacketFeatures",
    "MQTT_IoT_IDS2020_UniflowFeatures",
    "NIDS_CIC-BoT-IoT",
    "NIDS_CIC-ToN-IoT",
    "NIDS_NF-BoT-IoT",
    "NIDS_NF-BoT-IoT-v2",
    "NIDS_NF-BoT-IoT-v3",
    "NIDS_NF-CICIDS2018-v3",
    "NIDS_NF-CSE-CIC-IDS2018",
    "NIDS_NF-CSE-CIC-IDS2018-v2",
    "NIDS_NF-ToN-IoT",
    "NIDS_NF-ToN-IoT-v2",
    "NIDS_NF-ToN-IoT-v3",
    "NIDS_NF-UNSW-NB15",
    "NIDS_NF-UNSW-NB15-v2",
    "NIDS_NF-UNSW-NB15-v3",
    "NIDS_NF-UQ-NIDS",
    "NIDS_NF-UQ-NIDS-v2",
    "N_BaIoT_Danmini_Doorbell",
    "N_BaIoT_Ecobee_Thermostat",
    "N_BaIoT_Ennio_Doorbell",
    "N_BaIoT_Philips_B120N10_Baby_Monitor",
    "N_BaIoT_Provision_PT_737E_Security_Camera",
    "N_BaIoT_Provision_PT_838_Security_Camera",
    "N_BaIoT_Samsung_SNH_1011_N_Webcam",
    "N_BaIoT_SimpleHome_XCS7_1002_WHT_Security_Camera",
    "N_BaIoT_SimpleHome_XCS7_1003_WHT_Security_Camera",
    "ToN_IoT_IoT_Fridge",
    "ToN_IoT_IoT_GPS_Tracker",
    "ToN_IoT_IoT_Garage_Door",
    "ToN_IoT_IoT_Modbus",
    "ToN_IoT_IoT_Motion_Light",
    "ToN_IoT_IoT_Thermostat",
    "ToN_IoT_IoT_Weather",
    "ToN_IoT_Linux_Disk",
    "ToN_IoT_Linux_Memory",
    "ToN_IoT_Linux_Process",
    "ToN_IoT_Network",
    "ToN_IoT_Windows_10",
    "ToN_IoT_Windows_7"
]

In [5]:
def blend_with_white(rgb, alpha):
    return [1 - alpha * (1 - c) for c in rgb]

def format_and_color_columns(df, color_map_dict={}, alpha=0.0):
    df_colored = df.copy()

    for col in df.columns:
        col_data = df[col]

        # === Step 1: Apply your custom formatting ===
        if pd.api.types.is_float_dtype(col_data):
            if 'time' in col:
                formatted = col_data.map(lambda x: f"{x:,.1f}")
            elif 'size' in col:
                formatted = col_data.map(lambda x: f"{x:,.2f}")
            else:
                formatted = col_data.map(lambda x: f"{x:,.3f}")
        elif pd.api.types.is_integer_dtype(col_data):
            formatted = col_data.map(lambda x: f"{x:,}")
        else:
            formatted = col_data.astype(str)

        # === Step 2: Apply LaTeX color using colormap if specified ===
        if col in color_map_dict and pd.api.types.is_numeric_dtype(col_data):
            cmap = colormaps[color_map_dict[col]]
            valid_mask = col_data.notna()
            norm = Normalize(vmin=col_data[valid_mask].min(), vmax=col_data[valid_mask].max())
    
            # Start with string-typed formatted column
            colored_column = formatted.astype(str).copy()
    
            # Compute blended RGB
            rgba_colors = cmap(norm(col_data[valid_mask]))[:, :3]
            blended_colors = [blend_with_white(rgb, alpha=alpha) for rgb in rgba_colors]
    
            for i, (r, g, b) in zip(col_data[valid_mask].index, blended_colors):
                df_colored.loc[i, col] = (
                    f"\\cellcolor[rgb]{{{r:.3f}, {g:.3f}, {b:.3f}}} {formatted[i]}"
                )
        else:
            df_colored[col] = formatted

    return df_colored

In [6]:
def flatten_metrics_dict(metrics_dict: dict, dataset_id: str, seed: int, keys_to_include=None) -> dict:
    flat = {"dataset_id": dataset_id, "seed": seed}
    for top_key, subdict in metrics_dict.items():
        if isinstance(subdict, dict):
            for sub_key, value in subdict.items():
                flat_key = f"{top_key}_{sub_key}"
                if keys_to_include is None or flat_key in keys_to_include:
                    flat[flat_key] = value
        else:
            if keys_to_include is None or top_key in keys_to_include:
                flat[top_key] = subdict
    return flat

def compute_composite_difficulty_from_dict(metrics_dict: dict, dataset_id: str, seed: int, min_metrics_per_group=1) -> pd.DataFrame | None:
    all_metrics = [m for group in metric_groups.values() for m in group]
    
    flat_dict = flatten_metrics_dict(metrics_dict, dataset_id, seed, keys_to_include=all_metrics)
    df = pd.DataFrame([flat_dict])
    df[df.select_dtypes(include=['float64']).columns] = df.select_dtypes(include=['float64']).astype('float32')
    df[df.select_dtypes(include=['int64']).columns] = df.select_dtypes(include=['int64']).astype('int32')
    
    available_metrics = []
    missing_metrics = []

    for metric in all_metrics:
        if metric in df.columns and not pd.isna(df.loc[0, metric]):
            available_metrics.append(metric)
        else:
            missing_metrics.append(metric)

    if missing_metrics:
        print(f"[INFO] {dataset_id}: Missing metrics: {missing_metrics}")
    
    valid_groups = {}
    for group_name, metric_list in metric_groups.items():
        valid_metrics_in_group = [m for m in metric_list if m in available_metrics]
        if len(valid_metrics_in_group) >= min_metrics_per_group:
            valid_groups[group_name] = valid_metrics_in_group
        else:
            print(f"[WARN] {dataset_id}: Group '{group_name}' has only {len(valid_metrics_in_group)} valid metrics")
    
    if len(valid_groups) < 3:
        print(f"[SKIP] {dataset_id}: Only {len(valid_groups)} valid groups, need at least 3")
        return None

    for metric in metrics_to_invert:
        if metric in available_metrics:
            df[metric] = -df[metric]

    # print(f"[INFO] {dataset_id}: Skipping normalization for single dataset")

    for group_name, metric_list in valid_groups.items():
        df[f"{group_name}_difficulty"] = df[metric_list].mean(axis=1)

    group_cols = [f"{g}_difficulty" for g in valid_groups.keys()]
    df["overall_difficulty"] = df[group_cols].mean(axis=1)
    df["metrics_used"] = len(available_metrics)
    df["groups_used"] = len(valid_groups)

    return df

def compute_all_composite_difficulties(root_dir: str, frac: str, suffix: str = ".complexity.json", min_metrics_per_group=1) -> pd.DataFrame:
    """
    Loads all complexity metric JSONs from a folder and computes composite difficulty scores.
    More flexible version that handles missing metrics gracefully.
    """
    
    exclude_substrings = {
        "CICAPT_IIoT_Phase1_Macro",
        "CICAPT_IIoT_Phase1_Micro",
        # "ToN_IoT_IoT_Motion_Light"
    }
    
    all_json_paths = [
        path for path in Path(root_dir).rglob(f"*{suffix}")
        if frac in str(path.resolve()) and not any(substr in path.stem for substr in exclude_substrings)
        # if 'full' in str(path.resolve()) and not any(substr in path.stem for substr in exclude_substrings)
    ]

    rows = []

    print(f"[{frac}]\tFound {len(all_json_paths)} JSON files to process")

    for path in tqdm(all_json_paths, desc="Computing composite difficulties"):
        try:
            seed = int(re.search(r'.*/seed_(\d+)/', str(path.resolve())).groups(1)[0])
            with open(path, 'r') as f:
                metrics_dict = json.load(f)

            # Remove metadata keys
            metrics_dict.pop('label_mappings', None)
            metrics_dict.pop('errors', None)

            dataset_id = path.stem.replace('_X_y.complexity', '')

            composite_df = compute_composite_difficulty_from_dict(
                metrics_dict, dataset_id, seed, min_metrics_per_group
            )
            # display(composite_df)
            
            if composite_df is not None:
                rows.append(composite_df)

        except Exception as e:
            print(f"[ERROR] Failed to process {path}: {e}")

    if not rows:
        print("No datasets could be processed")
        return pd.DataFrame()

    result_df = pd.concat(rows, ignore_index=True)
    # display(result_df)

    # Normalize across datasets
    print(f"\nNormalizing metrics across {len(result_df)} datasets...")

    # Determine metrics to normalize
    metric_cols = []
    for group_name, metric_list in metric_groups.items():
        metric_cols.extend(metric_list)

    available_metric_cols = [col for col in metric_cols if col in result_df.columns]

    # Fill NaNs before normalization if needed
    if result_df[available_metric_cols].isnull().values.any():
        print("[WARN] NaNs detected before normalization – filling with 0")
        result_df[available_metric_cols] = result_df[available_metric_cols].fillna(0)

    # Check for infinites
    inf_mask = np.isinf(result_df[available_metric_cols])
    if inf_mask.values.any():
        cols_with_inf = inf_mask.columns[inf_mask.any()].tolist()
        print(f"[ERROR] Infinity detected in columns: {cols_with_inf}")
        
        # Optional: See the max values to check for 'too large for float32'
        print("Max values per column:")
        print(result_df[available_metric_cols].max())
        return pd.DataFrame()

    # Normalize
    if available_metric_cols:
        scaler = MinMaxScaler()
        result_df[available_metric_cols] = scaler.fit_transform(result_df[available_metric_cols])

    # Recompute group difficulties
    for group_name, metric_list in metric_groups.items():
        available_group_metrics = [m for m in metric_list if m in result_df.columns]
        if available_group_metrics:
            result_df[f"{group_name}_difficulty"] = result_df[available_group_metrics].mean(axis=1)

    # Recompute overall difficulty
    group_cols = [f"{group_name}_difficulty" for group_name in metric_groups.keys()
                  if f"{group_name}_difficulty" in result_df.columns]
    if group_cols:
        result_df["overall_difficulty"] = result_df[group_cols].mean(axis=1)

    print(f"Successfully processed {len(result_df)} datasets")
    print(f"Average metrics used per dataset: {result_df['metrics_used'].mean():.1f}")
    print(f"Average groups used per dataset: {result_df['groups_used'].mean():.1f}")

    return result_df

In [7]:
ROOT_DIR = "../../2025-11-17/Output_Zip_v4_Complexity_v3"

SAMPLE_FRACS = ['sampled_05', 'sampled_10', 'sampled_20', 'sampled_25', 'sampled_50', 'full']

df_composite = {}

for frac in SAMPLE_FRACS:

    df_composite[frac] = compute_all_composite_difficulties(ROOT_DIR, frac, min_metrics_per_group=1)

    display(df_composite[frac])

[sampled_05]	Found 365 JSON files to process

Computing composite difficulties:  22%|██████████████████████████████████████▋                                                                                                                                            | 79/365 [00:00<00:01, 193.37it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'mahalanobis_class_distance_mean', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Local_Overlap' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[SKIP] ToN_IoT_IoT_Motion_Light: Only 2 valid groups, need at least 3
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'mahalanobis_class_distance_mean', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Local_Overlap' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[SKIP] ToN_IoT_IoT_Motion_Light: Only 2 valid groups, need at least 3
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'mahalanobis_class_distance_mean', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Local_Overlap' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[SKIP] ToN_IoT_IoT_Motion_Light: Only 2 valid groups, need at least 3
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'mahalanobis_class_distance_mean', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Local_Overlap' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[SKIP] ToN_IoT_IoT_Motion_Light: Only 2 valid groups, need at least 3
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'mahalanobis_class_distance_mean', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Local_Overlap' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[SKIP] ToN_IoT_IoT_Motion_Light: Only 2 valid groups, need at least 3
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  75%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                             | 272/365 [00:01<00:00, 184.82it/s]

[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:01<00:00, 183.93it/s]

[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'svm_margin_mean', 'class_proba_entropy_mean', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Garage_Door: Group 'Boundary_Hardness' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'svm_margin_mean', 'class_proba_entropy_mean', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Garage_Door: Group 'Boundary_Hardness' has only 0 valid metrics

Normalizing metrics across 360 datasets...
[WARN] NaNs detected before normalization – filling with 0
[ERROR] Infinity detected in columns: ['calinski_harabasz_calinski_harabasz_score']
Max values per column:
anova_f_mean                                                 -0.000000
mutual_info_mean                                             -0.000000
pca_centroid_distance_pca_centroid_score                     47.132252
mahalanobis_class_distance_mean                               0.000000
svm_margin_mean                                               0.000000
class_proba_entropy_mean                                      1.945252
intrinsic_dimensionality_intrinsic_dimensionality_percent     1.000000
calinski_harabasz_calinski_harabasz_score                     0.000000
class_confusion_entropy_confusion_entropy                     1.109905
class_imbalance_normalized_entropy                           -0.000442
dtype: float32

Empty DataFrame
Columns: []
Index: []

[sampled_10]	Found 365 JSON files to process

Computing composite difficulties:  21%|████████████████████████████████████▊                                                                                                                                              | 75/365 [00:00<00:01, 181.96it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['pca_centroid_distance_pca_centroid_score', 'svm_margin_mean', 'class_proba_entropy_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score', 'class_confusion_entropy_confusion_entropy']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Boundary_Hardness' has only 0 valid metrics
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  62%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████▋                                                                   | 227/365 [00:01<00:00, 182.72it/s]

[INFO] CICEVSE2024_EVSE-A_Macro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICEVSE2024_EVSE-A_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  73%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                                | 265/365 [00:01<00:00, 179.76it/s]

[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:02<00:00, 181.91it/s]

[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Normalizing metrics across 365 datasets...
[WARN] NaNs detected before normalization – filling with 0
Successfully processed 365 datasets
Average metrics used per dataset: 9.9
Average groups used per dataset: 5.0

,dataset_id,seed,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BoT_IoT_Macro,53,1.000000,0.914042,0.126299,0.580033,0.923182,0.303338,0.350000,0.815493,5.854920e-01,0.478899,0.957021,0.353166,0.613260,0.582746,5.321957e-01,0.607678,10,5
1,BoT_IoT_Macro,23,1.000000,0.914688,0.137974,0.580796,0.923576,0.303741,0.400000,0.812363,5.594637e-01,0.478848,0.957344,0.359385,0.613658,0.606181,5.191557e-01,0.611145,10,5
2,BoT_IoT_Macro,37,1.000000,0.912633,0.145754,0.581277,0.923888,0.303561,0.350000,0.824777,5.895723e-01,0.478433,0.956316,0.363515,0.613725,0.587389,5.340029e-01,0.610989,10,5
3,BoT_IoT_Macro,89,1.000000,0.912834,0.135210,0.580453,0.922334,0.302307,0.350000,0.795610,5.827284e-01,0.478503,0.956417,0.357832,0.612321,0.572805,5.306159e-01,0.605998,10,5
4,BoT_IoT_Macro,17,1.000000,0.912468,0.129567,0.578722,0.921618,0.303091,0.300000,0.783595,5.688878e-01,0.478434,0.956234,0.354144,0.612355,0.541798,5.236611e-01,0.597638,10,5
5,NIDS_NF-ToN-IoT-v2,53,1.000000,0.751609,0.065455,0.404204,0.884039,0.349673,0.473684,0.937568,7.195740e-01,0.258309,0.875805,0.234830,0.616856,0.705626,4.889414e-01,0.584412,10,5
6,NIDS_NF-ToN-IoT-v2,23,1.000000,0.753041,0.068652,0.402327,0.885435,0.347489,0.473684,0.938733,6.963974e-01,0.258398,0.876521,0.235490,0.616462,0.706209,4.773976e-01,0.582416,10,5
7,NIDS_NF-ToN-IoT-v2,37,1.000000,0.752509,0.064501,0.400927,0.886445,0.351676,0.473684,0.938480,7.155442e-01,0.258127,0.876254,0.232714,0.619060,0.706082,4.868355e-01,0.584189,10,5
8,NIDS_NF-ToN-IoT-v2,89,1.000000,0.746534,0.071108,0.403286,0.885822,0.345776,0.473684,0.937226,7.308245e-01,0.258168,0.873267,0.237197,0.615799,0.705455,4.944962e-01,0.585243,10,5
9,NIDS_NF-ToN-IoT-v2,17,1.000000,0.749828,0.071632,0.403831,0.885836,0.346541,0.473684,0.939052,7.051510e-01,0.257996,0.874914,0.237731,0.616189,0.706368,4.815735e-01,0.583355,10,5
10,ToN_IoT_Windows_7,53,1.000000,0.702034,0.170335,0.095973,0.630668,0.039400,0.250000,0.997632,1.245395e-01,0.603301,0.851017,0.133154,0.335034,0.623816,3.639204e-01,0.461388,10,5
11,ToN_IoT_Windows_7,23,1.000000,0.701225,0.185186,0.099096,0.665081,0.041330,0.259615,0.997567,1.110908e-01,0.601131,0.850613,0.142141,0.353206,0.628591,3.561108e-01,0.466132,10,5
12,ToN_IoT_Windows_7,37,1.000000,0.703803,0.166899,0.095258,0.637047,0.038928,0.250000,0.997683,1.199473e-01,0.605774,0.851901,0.131078,0.337988,0.623841,3.628606e-01,0.461534,10,5
13,ToN_IoT_Windows_7,89,1.000000,0.707303,0.174072,0.096298,0.633577,0.039325,0.250000,0.997632,1.317460e-01,0.604257,0.853651,0.135185,0.336451,0.623816,3.680016e-01,0.463421,10,5
14,ToN_IoT_Windows_7,17,1.000000,0.699518,0.181124,0.092367,0.627160,0.039775,0.250000,0.997555,1.354951e-01,0.602690,0.849759,0.136745,0.333467,0.623777,3.690926e-01,0.462568,10,5
15,MQTT_IoT_IDS2020_BiflowFeatures,53,0.999995,0.330921,0.056220,0.643054,0.663712,0.010716,0.142857,0.976716,1.558658e-01,0.308836,0.665458,0.349637,0.337214,0.559787,2.323507e-01,0.428889,10,5
16,MQTT_IoT_IDS2020_BiflowFeatures,23,0.999995,0.333802,0.054573,0.648991,0.687241,0.011458,0.142857,0.979453,1.293532e-01,0.309216,0.666899,0.351782,0.349350,0.561155,2.192848e-01,0.429694,10,5
17,MQTT_IoT_IDS2020_BiflowFeatures,37,0.999995,0.333195,0.053357,0.648466,0.681843,0.011899,0.142857,0.979457,1.612084e-01,0.308702,0.666595,0.350911,0.346871,0.561157,2.349554e-01,0.432098,10,5
18,MQTT_IoT_IDS2020_BiflowFeatures,89,0.999995,0.262879,0.062802,0.637366,0.666177,0.008470,0.142857,0.966119,1.591130e-01,0.308018,0.631437,0.350084,0.337324,0.554488,2.335657e-01,0.421380,10,5
19,MQTT_IoT_IDS2020_BiflowFeatures,17,0.999995,0.332883,0.059312,0.648883,0.683177,0.010390,0.142857,0.975874,1.628361e-01,0.309368,0.666439,0.354098,0.346784,0.559366,2.361022e-01,0.432558,10,5
20,MQTT_IoT_IDS2020_UniflowFeatures,53,1.000000,0.386017,0.038641,0.640997,0.653994,0.015433,0.250000,0.967911,2.797865e-01,0.390679,0.693009,0.339819,0.334713,0.608955,3.352328e-01,0.462346,10,5
21,MQTT_IoT_IDS2020_UniflowFeatures,23,1.000000,0.331198,0.048003,0.632720,0.676424,0.009814,0.250000,0.951245,2.339164e-01,0.391451,0.665599,0.340362,0.343119,0.600623,3.126839e-01,0.452477,10,5
22,MQTT_IoT_IDS2020_UniflowFeatures,37,1.000000,0.420696,0.040024,0.640915,0.643150,0.013989,0.250000,0.965028,2.527376e-01,0.389935,0.710348,0.340469,0.328569,0.607514,3.213366e-01,0.461647,10,5
23,MQTT_IoT_IDS2020_UniflowFeatures,89,1.000000,0.322180,0.046154,0.634470,0.656561,0.010990,0.250000,0.952908,2.764305e-01,0.390512,0.661090,0.340312,0.333776,0.601454,3.334714e-01,0.454021,10,5
24,MQTT_IoT_IDS2020_UniflowFeatures,17,1.000000,0.331780,0.046923,0.634998,0.670468,0.010959,0.250000,0.953008,2.433866e-01,0.389460,0.665890,0.340961,0.340713,0.601504,3.164234e-01,0.453098,10,5
25,NIDS_CIC-ToN-IoT,53,1.000000,0.804529,0.084989,0.281643,0.819297,0.231855,0.239437,0.839760,3.207084e-01,0.492876,0.902265,0.183316,0.525576,0.539598,4.067922e-01,0.511509,10,5
26,NIDS_CIC-ToN-IoT,23,1.000000,0.805193,0.080796,0.295502,0.819845,0.233398,0.197183,0.841039,3.203233e-01,0.492963,0.902596,0.188149,0.526622,0.519111,4.066432e-01,0.508624,10,5
27,NIDS_CIC-ToN-IoT,37,1.000000,0.804997,0.083289,0.280846,0.819289,0.230590,0.211268,0.840308,3.200347e-01,0.493102,0.902498,0.182067,0.524940,0.525788,4.065686e-01,0.508372,10,5
28,NIDS_CIC-ToN-IoT,89,1.000000,0.804461,0.082303,0.294416,0.817397,0.234047,0.211268,0.840452,2.829993e-01,0.493014,0.902230,0.188360,0.525722,0.525860,3.880067e-01,0.506036,10,5
29,NIDS_CIC-ToN-IoT,17,1.000000,0.804906,0.082087,0.294769,0.820208,0.234573,0.211268,0.840811,3.181000e-01,0.493062,0.902453,0.188428,0.527390,0.526039,4.055809e-01,0.509978,10,5
30,NIDS_NF-ToN-IoT-v3,53,1.000000,0.738502,0.084273,0.400782,0.879389,0.250415,0.413043,0.798003,6.214580e-01,0.302940,0.869251,0.242527,0.564902,0.605523,4.621991e-01,0.548881,10,5
31,NIDS_NF-ToN-IoT-v3,23,1.000000,0.738545,0.080504,0.403525,0.885205,0.258218,0.391304,0.798703,6.391132e-01,0.302993,0.869273,0.242014,0.571711,0.595003,4.710530e-01,0.549811,10,5
32,NIDS_NF-ToN-IoT-v3,37,1.000000,0.738697,0.079090,0.397485,0.884520,0.256291,0.391304,0.800499,6.324701e-01,0.303042,0.869348,0.238288,0.570406,0.595901,4.677559e-01,0.548340,10,5
33,NIDS_NF-ToN-IoT-v3,89,1.000000,0.738574,0.082003,0.400667,0.882624,0.254889,0.391304,0.799355,6.213720e-01,0.302957,0.869287,0.241335,0.568756,0.595330,4.621644e-01,0.547374,10,5
34,NIDS_NF-ToN-IoT-v3,17,1.000000,0.738576,0.080402,0.404835,0.883535,0.258013,0.391304,0.800090,6.272441e-01,0.303000,0.869288,0.242619,0.570774,0.595697,4.651220e-01,0.548700,10,5
35,ToN_IoT_IoT_GPS_Tracker,53,1.000000,0.183592,0.000149,0.858464,1.000000,0.740344,0.500000,0.999081,6.793822e-12,0.307565,0.591796,0.429307,0.870172,0.749540,1.537825e-01,0.558919,10,5
36,ToN_IoT_IoT_GPS_Tracker,23,1.000000,0.167616,0.000164,0.859318,1.000000,0.746776,0.500000,0.999070,5.727148e-12,0.301596,0.583808,0.429741,0.873388,0.749535,1.507978e-01,0.557454,10,5
37,ToN_IoT_IoT_GPS_Tracker,37,1.000000,0.152756,0.000160,0.860083,1.000000,0.744267,0.500000,0.999059,6.626359e-12,0.303948,0.576378,0.430122,0.872134,0.749530,1.519738e-01,0.556027,10,5
38,ToN_IoT_IoT_GPS_Tracker,89,1.000000,0.164607,0.000159,0.860029,1.000000,0.747712,0.500000,0.999067,5.684474e-12,0.300753,0.582304,0.430094,0.873856,0.749533,1.503763e-01,0.557233,10,5
39,ToN_IoT_IoT_GPS_Tracker,17,1.000000,0.174121,0.000164,0.861008,1.000000,0.745836,0.500000,0.999072,5.706907e-12,0.302182,0.587061,0.430586,0.872918,0.749536,1.510910e-01,0.558238,10,5
40,ToN_IoT_Network,53,1.000000,0.810305,0.021475,0.638589,0.892776,0.409806,0.225000,0.952001,7.224147e-01,0.339453,0.905152,0.330032,0.651291,0.588501,5.309339e-01,0.601182,10,5
41,ToN_IoT_Network,23,1.000000,0.809833,0.021403,0.632475,0.890171,0.411419,0.200000,0.952092,7.043853e-01,0.339092,0.904916,0.326939,0.650795,0.576046,5.217388e-01,0.596087,10,5
42,ToN_IoT_Network,37,1.000000,0.810228,0.021512,0.630633,0.892843,0.410941,0.225000,0.952009,7.061492e-01,0.338937,0.905114,0.326072,0.651892,0.588505,5.225431e-01,0.598825,10,5
43,ToN_IoT_Network,89,1.000000,0.810066,0.021730,0.632625,0.893602,0.407848,0.225000,0.952027,7.239891e-01,0.339688,0.905033,0.327178,0.650725,0.588514,5.318388e-01,0.600658,10,5
44,ToN_IoT_Network,17,1.000000,0.810098,0.021663,0.629883,0.893220,0.406131,0.225000,0.951912,7.188213e-01,0.339389,0.905049,0.325773,0.649675,0.588456,5.291053e-01,0.599612,10,5
45,ToN_IoT_IoT_Motion_Light,53,1.000000,1.000000,0.000000,1.000000,1.000000,0.356324,0.000000,1.000000,9.073629e-11,0.000000,1.000000,0.500000,0.678162,0.500000,4.536814e-11,0.535632,7,4
46,ToN_IoT_IoT_Motion_Light,23,1.000000,1.000000,0.000000,1.000000,1.000000,0.356324,0.000000,1.000000,9.073629e-11,0.000000,1.000000,0.500000,0.678162,0.500000,4.536814e-11,0.535632,7,4
47,ToN_IoT_IoT_Motion_Light,37,1.000000,1.000000,0.000000,1.000000,1.000000,0.000000,0.000000,1.000000,9.073629e-11,0.000000,1.000000,0.500000,0.500000,0.500000,4.536814e-11,0.500000,4,3
48,ToN_IoT_IoT_Motion_Light,89,1.000000,1.000000,0.000000,1.000000,1.000000,0.356324,0.000000,1.000000,9.073629e-11,0.000000,1.000000,0.500000,0.678162,0.500000,4.536814e-11,0.535632,7,4
49,ToN_IoT_IoT_Motion_Light,17,1.000000,1.000000,0.000000,1.000000,1.000000,0.356324,0.000000,1.000000,9.073629e-11,0.000000,1.000000,0.500000,0.678162,0.500000,4.536814e-11,0.535632,7,4
50,ToN_IoT_Linux_Process,53,1.000000,0.895137,0.014650,0.598009,0.907502,0.480053,0.285714,0.994022,1.813690e-01,0.454486,0.947569,0.306330,0.693778,0.639868,3.179277e-01,0.581094,10,5
51,ToN_IoT_Linux_Process,23,1.000000,0.895302,0.014670,0.597252,0.907939,0.480583,0.285714,0.993697,1.781659e-01,0.455414,0.947651,0.305961,0.694261,0.639706,3.167900e-01,0.580874,10,5
52,ToN_IoT_Linux_Process,37,1.000000,0.894231,0.015362,0.598474,0.909040,0.477239,0.285714,0.993907,1.683430e-01,0.455337,0.947116,0.306918,0.693139,0.639811,3.118401e-01,0.579765,10,5
53,ToN_IoT_Linux_Process,89,1.000000,0.898861,0.014761,0.597022,0.906307,0.479050,0.285714,0.993849,1.859791e-01,0.455401,0.949430,0.305892,0.692679,0.639782,3.206899e-01,0.581695,10,5
54,ToN_IoT_Linux_Process,17,1.000000,0.898709,0.014503,0.597264,0.907789,0.478918,0.285714,0.993910,1.806183e-01,0.455810,0.949354,0.305883,0.693354,0.639812,3.182142e-01,0.581324,10,5
55,CICIoV2024_Decimal_Micro,53,1.000000,0.964314,0.017830,0.679149,0.685691,0.021070,0.375000,0.999902,1.573882e-01,0.954615,0.982157,0.348490,0.353381,0.687451,5.560014e-01,0.585496,10,5
56,CICIoV2024_Decimal_Micro,23,1.000000,0.959119,0.015474,1.000000,0.731792,0.022258,0.375000,0.999900,8.184468e-02,0.954018,0.979559,0.507737,0.377025,0.687450,5.179314e-01,0.613941,9,5
57,CICIoV2024_Decimal_Micro,37,1.000000,0.962007,0.017610,0.679681,0.721568,0.022220,0.375000,0.999906,1.502166e-01,0.953746,0.981004,0.348646,0.371894,0.687453,5.519816e-01,0.588196,10,5
58,CICIoV2024_Decimal_Micro,89,1.000000,0.961765,0.018491,0.684046,0.682023,0.018986,0.375000,0.999899,1.445289e-01,0.956872,0.980882,0.351269,0.350504,0.687449,5.507003e-01,0.584161,10,5
59,CICIoV2024_Decimal_Micro,17,1.000000,0.966015,0.018152,1.000000,0.724693,0.023819,0.375000,0.999923,6.844050e-02,0.959275,0.983007,0.509076,0.374256,0.687462,5.138576e-01,0.613532,9,5
60,NIDS_NF-CSE-CIC-IDS2018,53,1.000000,0.769357,0.119851,0.684266,0.797243,0.117084,0.400000,0.834844,4.051659e-02,0.783076,0.884678,0.402058,0.457163,0.617422,4.117963e-01,0.554624,10,5
61,NIDS_NF-CSE-CIC-IDS2018,23,1.000000,0.769611,0.119701,0.684717,0.795429,0.116208,0.400000,0.835167,1.218053e-01,0.783844,0.884805,0.402209,0.455818,0.617584,4.528244e-01,0.562648,10,5
62,NIDS_NF-CSE-CIC-IDS2018,37,1.000000,0.770260,0.117466,0.684278,0.795596,0.118247,0.400000,0.839408,1.258783e-01,0.783623,0.885130,0.400872,0.456922,0.619704,4.547505e-01,0.563476,10,5
63,NIDS_NF-CSE-CIC-IDS2018,89,1.000000,0.769586,0.117324,0.683459,0.795395,0.116699,0.400000,0.836527,9.088187e-02,0.783275,0.884793,0.400392,0.456047,0.618264,4.370787e-01,0.559315,10,5
64,NIDS_NF-CSE-CIC-IDS2018,17,1.000000,0.770062,0.119622,0.684821,0.797021,0.116930,0.400000,0.835862,8.901250e-02,0.783548,0.885031,0.402222,0.456975,0.617931,4.362803e-01,0.559688,10,5
65,N_BaIoT_Provision_PT_737E_Security_Camera,53,0.999999,0.164576,0.171393,0.369171,0.741977,0.073354,0.086957,0.892281,2.734924e-01,0.145724,0.582288,0.270282,0.407665,0.489619,2.096081e-01,0.391892,10,5
66,N_BaIoT_Provision_PT_737E_Security_Camera,23,0.999999,0.169824,0.155733,0.378200,0.758958,0.078316,0.086957,0.892603,3.205357e-01,0.145543,0.584912,0.266966,0.418637,0.489780,2.330391e-01,0.398667,10,5
67,N_BaIoT_Provision_PT_737E_Security_Camera,37,0.999999,0.168920,0.144691,0.370689,0.743276,0.071127,0.086957,0.892626,2.908911e-01,0.145863,0.584460,0.257690,0.407202,0.489791,2.183773e-01,0.391504,10,5
68,N_BaIoT_Provision_PT_737E_Security_Camera,89,0.999999,0.166393,0.146946,0.380540,0.746823,0.079594,0.086957,0.893580,2.684485e-01,0.145418,0.583196,0.263743,0.413209,0.490268,2.069332e-01,0.391470,10,5
69,N_BaIoT_Provision_PT_737E_Security_Camera,17,0.999999,0.167048,0.145994,0.370932,0.749861,0.078068,0.086957,0.892704,2.930765e-01,0.145695,0.583524,0.258463,0.413964,0.489830,2.193856e-01,0.393033,10,5
70,CICEVSE2024_EVSE-B_Micro,53,0.999999,0.010425,0.080780,0.555466,0.763385,0.224223,0.073529,0.919248,5.592294e-01,0.344598,0.505212,0.318123,0.493804,0.496389,4.519137e-01,0.453088,10,5
71,CICEVSE2024_EVSE-B_Micro,23,0.999998,0.039632,0.174304,0.558492,0.765075,0.224655,0.088235,0.928881,4.973519e-01,0.344738,0.519815,0.366398,0.494865,0.508558,4.210451e-01,0.462136,10,5
72,CICEVSE2024_EVSE-B_Micro,37,0.999998,0.040038,0.140557,0.555979,0.768515,0.226059,0.088235,0.930083,5.173674e-01,0.344324,0.520018,0.348268,0.497287,0.509159,4.308457e-01,0.461115,10,5
73,CICEVSE2024_EVSE-B_Micro,89,0.999998,0.012639,0.080551,0.557945,0.776095,0.224880,0.073529,0.920759,5.541194e-01,0.344708,0.506319,0.319248,0.500487,0.497144,4.494136e-01,0.454522,10,5
74,CICEVSE2024_EVSE-B_Micro,17,0.999998,0.054950,0.085101,0.555722,0.768812,0.223983,0.088235,0.932831,5.815901e-01,0.345034,0.527474,0.320411,0.496397,0.510533,4.633122e-01,0.463626,10,5
75,ToN_IoT_IoT_Weather,53,1.000000,0.934563,0.020663,0.786233,0.815491,0.327039,1.000000,0.994244,7.355228e-16,0.686658,0.967282,0.403448,0.571265,0.997122,3.433290e-01,0.656489,10,5
76,ToN_IoT_IoT_Weather,23,1.000000,0.934110,0.020407,0.786159,0.815513,0.327097,1.000000,0.994214,6.036838e-16,0.686765,0.967055,0.403283,0.571305,0.997107,3.433824e-01,0.656426,10,5
77,ToN_IoT_IoT_Weather,37,1.000000,0.934325,0.020423,0.786190,0.815508,0.326993,1.000000,0.994252,1.616762e-15,0.686650,0.967163,0.403307,0.571251,0.997126,3.433248e-01,0.656434,10,5
78,ToN_IoT_IoT_Weather,89,1.000000,0.934053,0.020560,0.786142,0.815644,0.327181,1.000000,0.994116,5.273559e-16,0.686389,0.967026,0.403351,0.571413,0.997058,3.431947e-01,0.656409,10,5
79,ToN_IoT_IoT_Weather,17,1.000000,0.933996,0.021184,0.786109,0.815437,0.326432,1.000000,0.994121,0.000000e+00,0.686938,0.966998,0.403647,0.570934,0.997060,3.434688e-01,0.656422,10,5
80,NIDS_CIC-BoT-IoT,53,1.000000,0.949393,0.367451,0.286128,0.959960,0.438895,0.139241,0.703957,8.069161e-01,0.340555,0.974697,0.326789,0.699427,0.421599,5.737357e-01,0.599249,10,5
81,NIDS_CIC-BoT-IoT,23,1.000000,0.949099,0.359046,0.285664,0.960631,0.437462,0.139241,0.695104,7.729054e-01,0.340677,0.974550,0.322355,0.699047,0.417172,5.567911e-01,0.593983,10,5
82,NIDS_CIC-BoT-IoT,37,1.000000,0.949334,0.354984,0.285917,0.960905,0.437766,0.139241,0.683327,8.245659e-01,0.340704,0.974667,0.320451,0.699335,0.411284,5.826352e-01,0.597674,10,5
83,NIDS_CIC-BoT-IoT,89,1.000000,0.947158,0.273573,0.285699,0.960162,0.435826,0.139241,0.689535,8.214749e-01,0.340325,0.973579,0.279636,0.697994,0.414388,5.808998e-01,0.589299,10,5
84,NIDS_CIC-BoT-IoT,17,1.000000,0.948889,0.362964,0.285545,0.960456,0.437158,0.139241,0.681916,8.185442e-01,0.340333,0.974444,0.324255,0.698807,0.410578,5.794387e-01,0.597505,10,5
85,CICIoV2024_Binary_Macro,53,1.000000,0.992076,0.032434,0.007405,0.692935,0.015025,0.413333,0.999848,1.927052e-01,0.938819,0.996038,0.019919,0.353980,0.706591,5.657622e-01,0.528458,10,5
86,CICIoV2024_Binary_Macro,23,1.000000,0.991158,0.032952,0.004023,0.698718,0.014319,0.440000,0.999827,2.587882e-01,0.935980,0.995579,0.018487,0.356519,0.719913,5.973842e-01,0.537577,10,5
87,CICIoV2024_Binary_Macro,37,1.000000,0.991987,0.035059,0.005218,0.672327,0.014211,0.426667,0.999838,2.079782e-01,0.941720,0.995994,0.020139,0.343269,0.713253,5.748490e-01,0.529501,10,5
88,CICIoV2024_Binary_Macro,89,1.000000,0.990787,0.036224,0.001061,0.658814,0.012303,0.440000,0.999801,1.514973e-01,0.935980,0.995394,0.018643,0.335559,0.719900,5.437387e-01,0.522647,10,5
89,CICIoV2024_Binary_Macro,17,1.000000,0.992992,0.029312,0.001912,0.697970,0.017069,0.453333,0.999880,2.990072e-01,0.938881,0.996496,0.015612,0.357520,0.726607,6.189439e-01,0.543036,10,5
90,ToN_IoT_Linux_Disk,53,1.000000,0.913417,0.020539,0.814581,0.877100,0.485892,0.666667,0.995745,1.332442e-03,0.502180,0.956708,0.417560,0.681496,0.831206,2.517561e-01,0.627745,10,5
91,ToN_IoT_Linux_Disk,23,1.000000,0.907167,0.020714,0.812694,0.876745,0.484870,0.666667,0.995463,1.647349e-03,0.502753,0.953583,0.416704,0.680807,0.831065,2.522000e-01,0.626872,10,5
92,ToN_IoT_Linux_Disk,37,1.000000,0.888501,0.023423,0.814117,0.877474,0.484442,0.666667,0.995512,1.158619e-02,0.501337,0.944251,0.418770,0.680958,0.831089,2.564618e-01,0.626306,10,5
93,ToN_IoT_Linux_Disk,89,1.000000,0.904623,0.020197,0.813676,0.877218,0.485050,0.666667,0.995560,1.638736e-03,0.502067,0.952311,0.416936,0.681134,0.831113,2.518529e-01,0.626670,10,5
94,ToN_IoT_Linux_Disk,17,1.000000,0.906525,0.018283,0.815329,0.876866,0.485840,0.666667,0.995870,6.834195e-04,0.502896,0.953263,0.416806,0.681353,0.831269,2.517896e-01,0.626896,10,5
95,UNSW_NB15,53,1.000000,0.938428,0.050136,0.294502,0.624457,0.035310,0.200000,0.952162,9.972665e-01,0.883958,0.969214,0.172319,0.329884,0.576081,9.406120e-01,0.597622,10,5
96,UNSW_NB15,23,1.000000,0.934646,0.048869,0.295110,0.622471,0.035239,0.200000,0.951052,9.878048e-01,0.884023,0.967323,0.171990,0.328855,0.575526,9.359137e-01,0.595922,10,5
97,UNSW_NB15,37,1.000000,0.935557,0.048226,0.293820,0.642947,0.035318,0.200000,0.952255,9.962111e-01,0.884102,0.967779,0.171023,0.339133,0.576127,9.401567e-01,0.598844,10,5
98,UNSW_NB15,89,1.000000,0.935914,0.049323,0.292962,0.628352,0.035038,0.200000,0.950600,9.697340e-01,0.884763,0.967957,0.171142,0.331695,0.575300,9.272486e-01,0.594669,10,5
99,UNSW_NB15,17,1.000000,0.938198,0.048024,0.294198,0.633428,0.035485,0.200000,0.953370,9.828392e-01,0.884375,0.969099,0.171111,0.334457,0.576685,9.336072e-01,0.596992,10,5
100,MQTT_IoT_IDS2020_PacketFeatures,53,1.000000,0.314613,0.019420,0.699723,0.790400,0.265721,0.411765,0.996675,4.996602e-01,0.151480,0.657306,0.359572,0.528060,0.704220,3.255699e-01,0.514946,10,5
101,MQTT_IoT_IDS2020_PacketFeatures,23,1.000000,0.312777,0.019681,0.703892,0.784670,0.259807,0.411765,0.996460,4.361788e-01,0.153016,0.656388,0.361786,0.522238,0.704113,2.945973e-01,0.507825,10,5
102,MQTT_IoT_IDS2020_PacketFeatures,37,1.000000,0.358042,0.017435,0.699583,0.789326,0.270405,0.470588,0.997287,4.407691e-01,0.158912,0.679021,0.358509,0.529866,0.733938,2.998407e-01,0.520235,10,5
103,MQTT_IoT_IDS2020_PacketFeatures,89,1.000000,0.370246,0.017132,0.699717,0.788826,0.275841,0.411765,0.997202,4.378648e-01,0.150960,0.685123,0.358425,0.532333,0.704483,2.944126e-01,0.514955,10,5

[sampled_20]	Found 365 JSON files to process

Computing composite difficulties:  20%|████████████████████████████████████▎                                                                                                                                              | 74/365 [00:00<00:01, 182.76it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'calinski_harabasz_calinski_harabasz_score']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'calinski_harabasz_calinski_harabasz_score']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'calinski_harabasz_calinski_harabasz_score']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  76%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▌                                           | 276/365 [00:01<00:00, 174.81it/s]

[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  96%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▋       | 350/365 [00:01<00:00, 175.72it/s]

[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:02<00:00, 176.28it/s]

[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Normalizing metrics across 365 datasets...
[WARN] NaNs detected before normalization – filling with 0
Successfully processed 365 datasets
Average metrics used per dataset: 9.9
Average groups used per dataset: 5.0

,dataset_id,seed,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BoT_IoT_Macro,53,1.000000,0.935281,0.120434,0.578932,0.919557,0.302581,0.350000,0.815546,5.882888e-01,0.478370,0.967640,0.349683,0.611069,0.582773,5.333295e-01,0.608899,10,5
1,BoT_IoT_Macro,23,1.000000,0.935533,0.129060,0.579651,0.921171,0.302051,0.400000,0.813468,5.813456e-01,0.478526,0.967766,0.354355,0.611611,0.606734,5.299356e-01,0.614080,10,5
2,BoT_IoT_Macro,37,1.000000,0.934075,0.138396,0.580138,0.921980,0.304387,0.350000,0.822027,5.809092e-01,0.478131,0.967037,0.359267,0.613183,0.586014,5.295200e-01,0.611004,10,5
3,BoT_IoT_Macro,89,1.000000,0.934252,0.136415,0.579502,0.921103,0.303555,0.350000,0.797426,5.977336e-01,0.478145,0.967126,0.357958,0.612329,0.573713,5.379391e-01,0.609813,10,5
4,BoT_IoT_Macro,17,1.000000,0.934241,0.132241,0.579074,0.920011,0.302851,0.400000,0.812025,5.708659e-01,0.478013,0.967121,0.355658,0.611431,0.606012,5.244394e-01,0.612932,10,5
5,NIDS_NF-ToN-IoT-v2,53,1.000000,0.820677,0.062609,0.407522,0.882939,0.345637,0.473684,0.940336,7.050306e-01,0.258283,0.910338,0.235065,0.614288,0.707010,4.816566e-01,0.589672,10,5
6,NIDS_NF-ToN-IoT-v2,23,1.000000,0.814731,0.065138,0.401756,0.882553,0.347457,0.473684,0.938557,7.135882e-01,0.258388,0.907366,0.233447,0.615005,0.706121,4.859883e-01,0.589585,10,5
7,NIDS_NF-ToN-IoT-v2,37,1.000000,0.814310,0.061827,0.400547,0.882219,0.347577,0.473684,0.938207,7.134864e-01,0.258200,0.907155,0.231187,0.614898,0.705945,4.858431e-01,0.589006,10,5
8,NIDS_NF-ToN-IoT-v2,89,1.000000,0.810242,0.068217,0.403254,0.881680,0.344717,0.473684,0.937105,7.228872e-01,0.258132,0.905121,0.235736,0.613199,0.705395,4.905097e-01,0.589992,10,5
9,NIDS_NF-ToN-IoT-v2,17,1.000000,0.819350,0.067710,0.407693,0.884900,0.344118,0.473684,0.941604,7.031863e-01,0.257986,0.909675,0.237702,0.614509,0.707644,4.805863e-01,0.590023,10,5
10,ToN_IoT_Windows_7,53,1.000000,0.777674,0.163101,0.095401,0.618214,0.037236,0.250000,0.997648,1.166758e-01,0.604891,0.888837,0.129251,0.327725,0.623824,3.607832e-01,0.466084,10,5
11,ToN_IoT_Windows_7,23,1.000000,0.776844,0.177450,0.099024,0.644632,0.038797,0.259615,0.997570,1.089729e-01,0.602445,0.888422,0.138237,0.341714,0.628593,3.557088e-01,0.470535,10,5
12,ToN_IoT_Windows_7,37,1.000000,0.779062,0.160210,0.094725,0.619041,0.037121,0.250000,0.997674,1.154521e-01,0.607699,0.889531,0.127467,0.328081,0.623837,3.615754e-01,0.466098,10,5
13,ToN_IoT_Windows_7,89,1.000000,0.782777,0.164422,0.097421,0.629543,0.038536,0.250000,0.997669,1.237959e-01,0.604101,0.891389,0.130921,0.334040,0.623835,3.639487e-01,0.468827,10,5
14,ToN_IoT_Windows_7,17,1.000000,0.775067,0.166834,0.092682,0.635921,0.038858,0.250000,0.997551,1.322965e-01,0.600888,0.887533,0.129758,0.337389,0.623775,3.665920e-01,0.469010,10,5
15,MQTT_IoT_IDS2020_BiflowFeatures,53,0.999996,0.499245,0.054305,0.642330,0.668213,0.009227,0.142857,0.975935,1.545113e-01,0.308913,0.749620,0.348317,0.338720,0.559396,2.317121e-01,0.445553,10,5
16,MQTT_IoT_IDS2020_BiflowFeatures,23,0.999996,0.501928,0.053977,0.648900,0.671427,0.010147,0.142857,0.978828,1.246072e-01,0.308806,0.750962,0.351438,0.340787,0.560842,2.167064e-01,0.444147,10,5
17,MQTT_IoT_IDS2020_BiflowFeatures,37,0.999995,0.499966,0.052239,0.647717,0.677029,0.010429,0.142857,0.978830,1.482898e-01,0.308617,0.749981,0.349978,0.343729,0.560844,2.284535e-01,0.446597,10,5
18,MQTT_IoT_IDS2020_BiflowFeatures,89,0.999995,0.446168,0.060585,0.638684,0.643324,0.007465,0.142857,0.965320,1.509668e-01,0.307274,0.723081,0.349635,0.325395,0.554088,2.291205e-01,0.436264,10,5
19,MQTT_IoT_IDS2020_BiflowFeatures,17,0.999996,0.499554,0.057218,0.647877,0.682457,0.009302,0.142857,0.975205,1.603924e-01,0.308594,0.749775,0.352547,0.345880,0.559031,2.344930e-01,0.448345,10,5
20,MQTT_IoT_IDS2020_UniflowFeatures,53,1.000000,0.571978,0.037175,0.640298,0.658622,0.013830,0.250000,0.967126,2.726547e-01,0.390806,0.785989,0.338736,0.336226,0.608563,3.317302e-01,0.480249,10,5
21,MQTT_IoT_IDS2020_UniflowFeatures,23,1.000000,0.525175,0.045802,0.632472,0.640466,0.009193,0.250000,0.949782,2.395219e-01,0.391854,0.762588,0.339137,0.324829,0.599891,3.156879e-01,0.468427,10,5
22,MQTT_IoT_IDS2020_UniflowFeatures,37,1.000000,0.560985,0.038593,0.640311,0.624764,0.012393,0.250000,0.964071,2.512713e-01,0.389518,0.780492,0.339452,0.318578,0.607035,3.203945e-01,0.473191,10,5
23,MQTT_IoT_IDS2020_UniflowFeatures,89,1.000000,0.490185,0.044537,0.632953,0.645807,0.010154,0.250000,0.951680,2.749970e-01,0.390347,0.745093,0.338745,0.327980,0.600840,3.326722e-01,0.469066,10,5
24,MQTT_IoT_IDS2020_UniflowFeatures,17,1.000000,0.530889,0.044879,0.633988,0.633094,0.010217,0.250000,0.951883,2.471511e-01,0.389304,0.765444,0.339434,0.321655,0.600941,3.182278e-01,0.469140,10,5
25,NIDS_CIC-ToN-IoT,53,1.000000,0.852910,0.080180,0.279289,0.816105,0.232823,0.239437,0.841489,3.157955e-01,0.492599,0.926455,0.179734,0.524464,0.540463,4.041975e-01,0.515063,10,5
26,NIDS_CIC-ToN-IoT,23,1.000000,0.853575,0.077028,0.291835,0.813393,0.235049,0.197183,0.842803,3.167314e-01,0.492667,0.926787,0.184432,0.524221,0.519993,4.046990e-01,0.512026,10,5
27,NIDS_CIC-ToN-IoT,37,1.000000,0.853572,0.080317,0.280081,0.814861,0.232791,0.211268,0.842261,3.197193e-01,0.492804,0.926786,0.180199,0.523826,0.526764,4.062614e-01,0.512767,10,5
28,NIDS_CIC-ToN-IoT,89,1.000000,0.853479,0.078399,0.290205,0.813549,0.234742,0.211268,0.842220,2.857881e-01,0.492740,0.926739,0.184302,0.524146,0.526744,3.892641e-01,0.510239,10,5
29,NIDS_CIC-ToN-IoT,17,1.000000,0.853538,0.078486,0.290469,0.814502,0.235010,0.211268,0.842077,3.070950e-01,0.492684,0.926769,0.184477,0.524756,0.526672,3.998893e-01,0.512513,10,5
30,NIDS_NF-ToN-IoT-v3,53,1.000000,0.803762,0.079598,0.404059,0.879319,0.255626,0.391304,0.797352,6.232929e-01,0.302882,0.901881,0.241828,0.567473,0.594328,4.630876e-01,0.553720,10,5
31,NIDS_NF-ToN-IoT-v3,23,1.000000,0.803738,0.076896,0.403288,0.879431,0.256646,0.391304,0.797596,6.242878e-01,0.303003,0.901869,0.240092,0.568038,0.594450,4.636453e-01,0.553619,10,5
32,NIDS_NF-ToN-IoT-v3,37,1.000000,0.803804,0.075244,0.396484,0.879721,0.254753,0.391304,0.799694,6.272194e-01,0.303074,0.901902,0.235864,0.567237,0.595499,4.651466e-01,0.553130,10,5
33,NIDS_NF-ToN-IoT-v3,89,1.000000,0.803786,0.078980,0.399482,0.878749,0.252937,0.391304,0.797944,6.119560e-01,0.302936,0.901893,0.239231,0.565843,0.594624,4.574462e-01,0.551808,10,5
34,NIDS_NF-ToN-IoT-v3,17,1.000000,0.803737,0.077540,0.403859,0.879724,0.255907,0.391304,0.798675,6.190608e-01,0.302882,0.901868,0.240699,0.567815,0.594989,4.609713e-01,0.553269,10,5
35,ToN_IoT_IoT_GPS_Tracker,53,1.000000,0.373827,0.000151,0.859073,1.000000,0.745339,0.500000,0.999168,5.665836e-12,0.302538,0.686913,0.429612,0.872669,0.749584,1.512688e-01,0.578010,10,5
36,ToN_IoT_IoT_GPS_Tracker,23,1.000000,0.372802,0.000157,0.860315,1.000000,0.748293,0.500000,0.999170,5.655691e-12,0.299888,0.686401,0.430236,0.874147,0.749585,1.499438e-01,0.578062,10,5
37,ToN_IoT_IoT_GPS_Tracker,37,1.000000,0.362073,0.000153,0.859947,1.000000,0.744212,0.500000,0.999165,6.595786e-12,0.303847,0.681037,0.430050,0.872106,0.749582,1.519237e-01,0.576940,10,5
38,ToN_IoT_IoT_GPS_Tracker,89,1.000000,0.372980,0.000152,0.859853,1.000000,0.747566,0.500000,0.999170,5.660299e-12,0.300752,0.686490,0.430003,0.873783,0.749585,1.503760e-01,0.578047,10,5
39,ToN_IoT_IoT_GPS_Tracker,17,1.000000,0.366824,0.000157,0.860907,1.000000,0.747639,0.500000,0.999169,5.658994e-12,0.300572,0.683412,0.430532,0.873819,0.749585,1.502858e-01,0.577527,10,5
40,ToN_IoT_Network,53,1.000000,0.856154,0.020244,0.638963,0.887028,0.407789,0.225000,0.953069,7.120659e-01,0.338472,0.928077,0.329604,0.647408,0.589034,5.252690e-01,0.603878,10,5
41,ToN_IoT_Network,23,1.000000,0.856011,0.020356,0.631065,0.887230,0.410431,0.200000,0.953193,7.016103e-01,0.338209,0.928006,0.325710,0.648831,0.576597,5.199096e-01,0.599811,10,5
42,ToN_IoT_Network,37,1.000000,0.856216,0.020363,0.630280,0.887648,0.408442,0.225000,0.953019,7.108413e-01,0.338236,0.928108,0.325322,0.648045,0.589010,5.245388e-01,0.603005,10,5
43,ToN_IoT_Network,89,1.000000,0.856097,0.020547,0.633019,0.889889,0.408670,0.200000,0.953106,7.147580e-01,0.338913,0.928048,0.326783,0.649279,0.576553,5.268353e-01,0.601500,10,5
44,ToN_IoT_Network,17,1.000000,0.856032,0.020465,0.629226,0.888525,0.406534,0.225000,0.953052,7.080560e-01,0.338404,0.928016,0.324845,0.647530,0.589026,5.232299e-01,0.602529,10,5
45,ToN_IoT_IoT_Motion_Light,53,1.000000,1.000000,0.000000,1.000000,0.908670,0.564548,0.000000,1.000000,9.019267e-11,0.000000,1.000000,0.500000,0.736609,0.500000,4.509633e-11,0.547322,7,4
46,ToN_IoT_IoT_Motion_Light,23,1.000000,0.000000,0.005950,1.000000,0.932661,0.563971,0.500000,1.000000,9.019267e-11,0.000000,0.500000,0.502975,0.748316,0.750000,4.509633e-11,0.500258,8,5
47,ToN_IoT_IoT_Motion_Light,37,1.000000,0.725982,0.004463,1.000000,0.909305,0.326848,0.500000,0.999996,6.762502e-11,0.081740,0.862991,0.502231,0.618076,0.749998,4.086989e-02,0.554833,9,5
48,ToN_IoT_IoT_Motion_Light,89,1.000000,0.000000,0.005950,1.000000,0.932661,0.563971,0.500000,1.000000,9.019267e-11,0.000000,0.500000,0.502975,0.748316,0.750000,4.509633e-11,0.500258,8,5
49,ToN_IoT_IoT_Motion_Light,17,1.000000,0.000000,0.005950,1.000000,0.932661,0.563971,0.500000,1.000000,9.019267e-11,0.000000,0.500000,0.502975,0.748316,0.750000,4.509633e-11,0.500258,8,5
50,ToN_IoT_Linux_Process,53,1.000000,0.921278,0.014114,0.597788,0.905537,0.479803,0.285714,0.993886,1.769680e-01,0.453518,0.960639,0.305951,0.692670,0.639800,3.152432e-01,0.582861,10,5
51,ToN_IoT_Linux_Process,23,1.000000,0.920946,0.013834,0.596888,0.905856,0.478886,0.285714,0.993604,1.790219e-01,0.454311,0.960473,0.305361,0.692371,0.639659,3.166664e-01,0.582906,10,5
52,ToN_IoT_Linux_Process,37,1.000000,0.920883,0.014643,0.597702,0.905166,0.477242,0.285714,0.993834,1.805507e-01,0.454603,0.960441,0.306172,0.691204,0.639774,3.175766e-01,0.583034,10,5
53,ToN_IoT_Linux_Process,89,1.000000,0.924306,0.013810,0.596632,0.904938,0.479050,0.285714,0.993885,1.838004e-01,0.455371,0.962153,0.305221,0.691994,0.639799,3.195857e-01,0.583751,10,5
54,ToN_IoT_Linux_Process,17,1.000000,0.924316,0.013598,0.596633,0.904231,0.479912,0.285714,0.993930,1.814788e-01,0.455312,0.962158,0.305115,0.692071,0.639822,3.183955e-01,0.583512,10,5
55,CICIoV2024_Decimal_Micro,53,1.000000,0.975317,0.017091,0.679944,0.671846,0.018681,0.375000,0.999913,1.518828e-01,0.959144,0.987659,0.348517,0.345263,0.687456,5.555133e-01,0.584882,10,5
56,CICIoV2024_Decimal_Micro,23,1.000000,0.969704,0.013892,1.000000,0.722317,0.020753,0.375000,0.999908,8.134482e-02,0.956390,0.984852,0.506946,0.371535,0.687454,5.188672e-01,0.613931,9,5
57,CICIoV2024_Decimal_Micro,37,1.000000,0.971918,0.016522,0.679587,0.723818,0.020462,0.375000,0.999912,1.436462e-01,0.956289,0.985959,0.348054,0.372140,0.687456,5.499674e-01,0.588715,10,5
58,CICIoV2024_Decimal_Micro,89,1.000000,0.970446,0.020460,1.000000,0.713299,0.020224,0.375000,0.999926,1.240248e-01,0.961573,0.985223,0.510230,0.366762,0.687463,5.427991e-01,0.618495,9,5
59,CICIoV2024_Decimal_Micro,17,1.000000,0.972199,0.017349,0.679204,0.723378,0.023485,0.375000,0.999915,1.215063e-01,0.957429,0.986099,0.348277,0.373431,0.687458,5.394678e-01,0.586947,10,5
60,NIDS_NF-CSE-CIC-IDS2018,53,1.000000,0.824819,0.113996,0.684196,0.787974,0.116470,0.400000,0.836002,8.949675e-02,0.781536,0.912409,0.399096,0.452222,0.618001,4.355165e-01,0.563449,10,5
61,NIDS_NF-CSE-CIC-IDS2018,23,1.000000,0.824678,0.112275,0.684797,0.791094,0.116409,0.400000,0.837355,3.784553e-02,0.781816,0.912339,0.398536,0.453751,0.618678,4.098307e-01,0.558627,10,5
62,NIDS_NF-CSE-CIC-IDS2018,37,1.000000,0.824757,0.112308,0.684263,0.791441,0.117350,0.400000,0.839744,1.180147e-01,0.781512,0.912378,0.398286,0.454396,0.619872,4.497634e-01,0.566939,10,5
63,NIDS_NF-CSE-CIC-IDS2018,89,1.000000,0.824685,0.110594,0.683552,0.787734,0.116759,0.400000,0.838507,1.271977e-01,0.781303,0.912342,0.397073,0.452246,0.619254,4.542502e-01,0.567033,10,5
64,NIDS_NF-CSE-CIC-IDS2018,17,1.000000,0.825063,0.112186,0.684751,0.789486,0.116936,0.400000,0.837000,8.606344e-02,0.781757,0.912531,0.398469,0.453211,0.618500,4.339100e-01,0.563324,10,5
65,N_BaIoT_Provision_PT_737E_Security_Camera,53,0.999999,0.377083,0.153392,0.366036,0.737395,0.070996,0.086957,0.893856,2.747279e-01,0.147509,0.688541,0.259714,0.404195,0.490406,2.111186e-01,0.410795,10,5
66,N_BaIoT_Provision_PT_737E_Security_Camera,23,0.999999,0.377201,0.146216,0.375387,0.751173,0.076153,0.086957,0.893935,3.080890e-01,0.147242,0.688600,0.260802,0.413663,0.490446,2.276654e-01,0.416235,10,5
67,N_BaIoT_Provision_PT_737E_Security_Camera,37,0.999999,0.376436,0.141085,0.367693,0.726205,0.069291,0.086957,0.893878,2.891257e-01,0.147810,0.688218,0.254389,0.397748,0.490417,2.184678e-01,0.409848,10,5
68,N_BaIoT_Provision_PT_737E_Security_Camera,89,0.999999,0.375938,0.138320,0.377272,0.739711,0.077570,0.086957,0.894335,2.639569e-01,0.147588,0.687969,0.257796,0.408641,0.490646,2.057724e-01,0.410165,10,5
69,N_BaIoT_Provision_PT_737E_Security_Camera,17,0.999999,0.376131,0.140721,0.367998,0.737712,0.076000,0.086957,0.894010,3.083827e-01,0.147603,0.688065,0.254359,0.406856,0.490483,2.279926e-01,0.413551,10,5
70,CICEVSE2024_EVSE-B_Micro,53,0.999999,0.286676,0.141654,0.552529,0.766992,0.213482,0.088235,0.931861,5.468605e-01,0.354344,0.643337,0.347091,0.490237,0.510048,4.506021e-01,0.488263,10,5
71,CICEVSE2024_EVSE-B_Micro,23,0.999999,0.286256,0.144974,0.554771,0.768539,0.214607,0.088235,0.931474,5.585962e-01,0.354385,0.643127,0.349872,0.491573,0.509855,4.564908e-01,0.490184,10,5
72,CICEVSE2024_EVSE-B_Micro,37,0.999998,0.288407,0.132955,0.552277,0.747531,0.214618,0.088235,0.932471,5.658157e-01,0.353989,0.644203,0.342616,0.481075,0.510353,4.599025e-01,0.487630,10,5
73,CICEVSE2024_EVSE-B_Micro,89,0.999998,0.293050,0.140058,0.555333,0.763381,0.213162,0.088235,0.932007,5.551072e-01,0.354721,0.646524,0.347695,0.488272,0.510121,4.549140e-01,0.489505,10,5
74,CICEVSE2024_EVSE-B_Micro,17,0.999998,0.287658,0.088686,0.552527,0.759876,0.212843,0.088235,0.932986,6.015673e-01,0.354586,0.643828,0.320607,0.486360,0.510611,4.780766e-01,0.487896,10,5
75,ToN_IoT_IoT_Weather,53,1.000000,0.950924,0.019786,0.785965,0.810442,0.326781,1.000000,0.994156,0.000000e+00,0.686347,0.975462,0.402875,0.568611,0.997078,3.431737e-01,0.657440,10,5
76,ToN_IoT_IoT_Weather,23,1.000000,0.950566,0.019508,0.785893,0.810232,0.326309,1.000000,0.994160,4.996004e-16,0.686960,0.975283,0.402700,0.568271,0.997080,3.434799e-01,0.657363,10,5
77,ToN_IoT_IoT_Weather,37,1.000000,0.950910,0.019522,0.785915,0.810311,0.326749,1.000000,0.994223,7.494005e-16,0.686660,0.975455,0.402719,0.568530,0.997111,3.433298e-01,0.657429,10,5
78,ToN_IoT_IoT_Weather,89,1.000000,0.950715,0.019694,0.785892,0.810368,0.326564,1.000000,0.994087,8.049117e-16,0.686612,0.975357,0.402793,0.568466,0.997043,3.433058e-01,0.657393,10,5
79,ToN_IoT_IoT_Weather,17,1.000000,0.950638,0.019971,0.785837,0.810305,0.326511,1.000000,0.994141,6.522560e-16,0.686720,0.975319,0.402904,0.568408,0.997070,3.433601e-01,0.657412,10,5
80,NIDS_CIC-BoT-IoT,53,1.000000,0.961340,0.336597,0.282521,0.958393,0.436043,0.139241,0.722756,8.021930e-01,0.338834,0.980670,0.309559,0.697218,0.430998,5.705134e-01,0.597792,10,5
81,NIDS_CIC-BoT-IoT,23,1.000000,0.960824,0.330126,0.282653,0.957923,0.435608,0.139241,0.716072,8.138095e-01,0.338878,0.980412,0.306390,0.696765,0.427656,5.763440e-01,0.597513,10,5
82,NIDS_CIC-BoT-IoT,37,1.000000,0.960685,0.324821,0.282349,0.958800,0.436202,0.139241,0.699705,7.988111e-01,0.338941,0.980343,0.303585,0.697501,0.419473,5.688761e-01,0.593956,10,5
83,NIDS_CIC-BoT-IoT,89,1.000000,0.959094,0.265844,0.281926,0.959593,0.436285,0.139241,0.705775,8.102066e-01,0.338623,0.979547,0.273885,0.697939,0.422508,5.744150e-01,0.589659,10,5
84,NIDS_CIC-BoT-IoT,17,1.000000,0.960020,0.335270,0.282104,0.958028,0.435977,0.139241,0.708075,7.864498e-01,0.338612,0.980010,0.308687,0.697003,0.423658,5.625312e-01,0.594378,10,5
85,CICIoV2024_Binary_Macro,53,1.000000,0.994089,0.029752,0.006117,0.684322,0.013964,0.426667,0.999852,2.831939e-01,0.939741,0.997044,0.017935,0.349143,0.713259,6.114675e-01,0.537770,10,5
86,CICIoV2024_Binary_Macro,23,1.000000,0.993448,0.028746,0.004822,0.683980,0.016242,0.453333,0.999840,2.542140e-01,0.929732,0.996724,0.016784,0.350111,0.726587,5.919731e-01,0.536436,10,5
87,CICIoV2024_Binary_Macro,37,1.000000,0.994208,0.033693,0.005367,0.668068,0.012621,0.426667,0.999840,2.067080e-01,0.944836,0.997104,0.019530,0.340345,0.713254,5.757722e-01,0.529201,10,5
88,CICIoV2024_Binary_Macro,89,1.000000,0.993400,0.033685,0.003748,0.664116,0.012230,0.440000,0.999814,1.426694e-01,0.937169,0.996700,0.018716,0.338173,0.719907,5.399194e-01,0.522683,10,5
89,CICIoV2024_Binary_Macro,17,1.000000,0.994846,0.026621,0.000000,0.688759,0.016335,0.453333,0.999885,3.509179e-01,0.937263,0.997423,0.013311,0.352547,0.726609,6.440903e-01,0.546796,10,5
90,ToN_IoT_Linux_Disk,53,1.000000,0.934618,0.019446,0.814069,0.873754,0.486065,0.666667,0.995680,1.263847e-03,0.501580,0.967309,0.416758,0.679910,0.831173,2.514219e-01,0.629314,10,5
91,ToN_IoT_Linux_Disk,23,1.000000,0.930603,0.019625,0.813462,0.873359,0.484731,0.666667,0.995547,1.473886e-03,0.502827,0.965302,0.416544,0.679045,0.831107,2.521507e-01,0.628830,10,5
92,ToN_IoT_Linux_Disk,37,1.000000,0.917267,0.020979,0.815372,0.874076,0.485027,0.666667,0.995604,9.103627e-03,0.500929,0.958633,0.418176,0.679551,0.831135,2.550163e-01,0.628502,10,5
93,ToN_IoT_Linux_Disk,89,1.000000,0.928406,0.019444,0.813934,0.873640,0.484424,0.666667,0.995575,2.876478e-03,0.502253,0.964203,0.416689,0.679032,0.831121,2.525646e-01,0.628722,10,5
94,ToN_IoT_Linux_Disk,17,1.000000,0.930610,0.017545,0.815406,0.873217,0.484905,0.666667,0.995812,6.743224e-04,0.503308,0.965305,0.416475,0.679061,0.831239,2.519911e-01,0.628814,10,5
95,UNSW_NB15,53,1.000000,0.954085,0.047690,0.293575,0.624982,0.034837,0.200000,0.952031,9.938637e-01,0.884114,0.977043,0.170633,0.329909,0.576016,9.389886e-01,0.598518,10,5
96,UNSW_NB15,23,1.000000,0.951073,0.047096,0.294215,0.610484,0.034922,0.200000,0.951158,9.811568e-01,0.884131,0.975536,0.170656,0.322703,0.575579,9.326441e-01,0.595424,10,5
97,UNSW_NB15,37,1.000000,0.951871,0.046257,0.292920,0.615183,0.034926,0.200000,0.951850,1.000000e+00,0.884289,0.975936,0.169589,0.325055,0.575925,9.421445e-01,0.597730,10,5
98,UNSW_NB15,89,1.000000,0.951090,0.047198,0.292153,0.602789,0.034652,0.200000,0.950421,9.985153e-01,0.884816,0.975545,0.169675,0.318720,0.575211,9.416658e-01,0.596163,10,5
99,UNSW_NB15,17,1.000000,0.953631,0.046202,0.293182,0.631308,0.034978,0.200000,0.953343,9.764053e-01,0.884490,0.976815,0.169692,0.333143,0.576671,9.304476e-01,0.597354,10,5
100,MQTT_IoT_IDS2020_PacketFeatures,53,1.000000,0.489814,0.018371,0.699902,0.781945,0.253145,0.411765,0.996714,4.693399e-01,0.158634,0.744907,0.359136,0.517545,0.704239,3.139868e-01,0.527963,10,5
101,MQTT_IoT_IDS2020_PacketFeatures,23,1.000000,0.499290,0.018687,0.701873,0.781964,0.251153,0.411765,0.996567,4.447860e-01,0.154279,0.749645,0.360280,0.516559,0.704166,2.995325e-01,0.526036,10,5
102,MQTT_IoT_IDS2020_PacketFeatures,37,1.000000,0.515226,0.016784,0.701119,0.787234,0.258629,0.470588,0.997235,4.516364e-01,0.159728,0.757613,0.358951,0.522931,0.733911,3.056823e-01,0.535818,10,5
103,MQTT_IoT_IDS2020_PacketFeatures,89,1.000000,0.525417,0.016549,0.698180,0.785310,0.265577,0.411765,0.997201,4.623204e-01,0.147457,0.762708,0.357364,0.525444,0.704483,3.048888e-01,0.530978,10,5

[sampled_25]	Found 365 JSON files to process

Computing composite difficulties:  20%|████████████████████████████████████▎                                                                                                                                              | 74/365 [00:00<00:01, 175.75it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'calinski_harabasz_calinski_harabasz_score']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'calinski_harabasz_calinski_harabasz_score']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  75%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏                                            | 273/365 [00:01<00:00, 173.93it/s]

[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  95%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏         | 345/365 [00:01<00:00, 172.14it/s]

[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:02<00:00, 172.83it/s]

[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Garage_Door: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Normalizing metrics across 365 datasets...
[WARN] NaNs detected before normalization – filling with 0
Successfully processed 365 datasets
Average metrics used per dataset: 9.9
Average groups used per dataset: 5.0

,dataset_id,seed,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BoT_IoT_Macro,53,1.000000,0.926660,0.125274,0.579007,0.934937,0.302844,0.400000,0.824251,5.829638e-01,0.478142,0.963330,0.352141,0.618891,0.612126,5.305527e-01,0.615408,10,5
1,BoT_IoT_Macro,23,1.000000,0.926737,0.125557,0.578879,0.937582,0.302280,0.400000,0.812930,5.782478e-01,0.478173,0.963368,0.352218,0.619931,0.606465,5.282106e-01,0.614039,10,5
2,BoT_IoT_Macro,37,1.000000,0.925479,0.134476,0.579717,0.935082,0.303685,0.350000,0.823720,5.773503e-01,0.477958,0.962739,0.357097,0.619383,0.586860,5.276539e-01,0.610747,10,5
3,BoT_IoT_Macro,89,1.000000,0.925315,0.131498,0.578973,0.936897,0.302388,0.350000,0.799286,5.977641e-01,0.477794,0.962657,0.355235,0.619642,0.574643,5.377792e-01,0.609991,10,5
4,BoT_IoT_Macro,17,1.000000,0.925380,0.128807,0.578917,0.936225,0.302018,0.400000,0.812346,5.713781e-01,0.477888,0.962690,0.353862,0.619121,0.606173,5.246330e-01,0.613296,10,5
5,NIDS_NF-ToN-IoT-v2,53,1.000000,0.797352,0.060515,0.406588,0.908159,0.345522,0.473684,0.940289,7.078449e-01,0.258289,0.898676,0.233551,0.626841,0.706987,4.830669e-01,0.589824,10,5
6,NIDS_NF-ToN-IoT-v2,23,1.000000,0.798326,0.063400,0.404720,0.901186,0.341299,0.473684,0.940407,7.094522e-01,0.258416,0.899163,0.234060,0.621242,0.707046,4.839342e-01,0.589089,10,5
7,NIDS_NF-ToN-IoT-v2,37,1.000000,0.789838,0.061570,0.401170,0.906004,0.347174,0.473684,0.937839,7.037405e-01,0.258252,0.894919,0.231370,0.626589,0.705762,4.809961e-01,0.587927,10,5
8,NIDS_NF-ToN-IoT-v2,89,1.000000,0.793280,0.066408,0.406468,0.902885,0.342722,0.473684,0.939724,7.032202e-01,0.258033,0.896640,0.236438,0.622804,0.706704,4.806264e-01,0.588642,10,5
9,NIDS_NF-ToN-IoT-v2,17,1.000000,0.795627,0.065504,0.406966,0.906356,0.343983,0.473684,0.941202,7.081215e-01,0.257994,0.897814,0.236235,0.625169,0.707443,4.830578e-01,0.589944,10,5
10,ToN_IoT_Windows_7,53,1.000000,0.748806,0.160035,0.097893,0.688874,0.036892,0.250000,0.997650,1.181778e-01,0.605466,0.874403,0.128964,0.362883,0.623825,3.618219e-01,0.470379,10,5
11,ToN_IoT_Windows_7,23,1.000000,0.748637,0.169162,0.098550,0.710669,0.038762,0.259615,0.997579,9.934882e-02,0.601649,0.874319,0.133856,0.374716,0.628597,3.504989e-01,0.472397,10,5
12,ToN_IoT_Windows_7,37,1.000000,0.750908,0.157231,0.094510,0.695883,0.037015,0.250000,0.997651,1.148013e-01,0.606578,0.875454,0.125871,0.366449,0.623826,3.606896e-01,0.470458,10,5
13,ToN_IoT_Windows_7,89,1.000000,0.752437,0.160942,0.096961,0.712283,0.038585,0.250000,0.997652,1.257534e-01,0.603499,0.876219,0.128952,0.375434,0.623826,3.646260e-01,0.473811,10,5
14,ToN_IoT_Windows_7,17,1.000000,0.746940,0.163988,0.091741,0.696675,0.038953,0.250000,0.997560,1.407626e-01,0.601411,0.873470,0.127865,0.367814,0.623780,3.710867e-01,0.472803,10,5
15,MQTT_IoT_IDS2020_BiflowFeatures,53,0.999994,0.434626,0.053401,0.646623,0.723041,0.009005,0.142857,0.975606,1.571886e-01,0.308916,0.717310,0.350012,0.366023,0.559232,2.330521e-01,0.445126,10,5
16,MQTT_IoT_IDS2020_BiflowFeatures,23,0.999994,0.436403,0.052716,0.648529,0.732414,0.009851,0.142857,0.978539,1.217862e-01,0.308909,0.718198,0.350622,0.371132,0.560698,2.153476e-01,0.443200,10,5
17,MQTT_IoT_IDS2020_BiflowFeatures,37,0.999994,0.435171,0.050921,0.650210,0.735103,0.010093,0.142857,0.978534,1.488566e-01,0.308526,0.717582,0.350565,0.372598,0.560696,2.286913e-01,0.446027,10,5
18,MQTT_IoT_IDS2020_BiflowFeatures,89,0.999994,0.371655,0.060063,0.641942,0.709655,0.007333,0.142857,0.964920,1.468031e-01,0.307030,0.685824,0.351002,0.358494,0.553889,2.269166e-01,0.435225,10,5
19,MQTT_IoT_IDS2020_BiflowFeatures,17,0.999994,0.437354,0.056871,0.646910,0.739058,0.009070,0.142857,0.974877,1.523599e-01,0.308233,0.718674,0.351891,0.374064,0.558867,2.302963e-01,0.446758,10,5
20,MQTT_IoT_IDS2020_UniflowFeatures,53,1.000000,0.513219,0.036584,0.639826,0.704222,0.013431,0.250000,0.966733,2.719166e-01,0.389966,0.756609,0.338205,0.358826,0.608366,3.309415e-01,0.478590,10,5
21,MQTT_IoT_IDS2020_UniflowFeatures,23,1.000000,0.462400,0.044982,0.631837,0.704522,0.009084,0.250000,0.949223,2.382951e-01,0.391503,0.731200,0.338410,0.356803,0.599612,3.148993e-01,0.468185,10,5
22,MQTT_IoT_IDS2020_UniflowFeatures,37,1.000000,0.507774,0.037881,0.639934,0.718528,0.012032,0.250000,0.964310,2.512564e-01,0.389995,0.753887,0.338908,0.365280,0.607155,3.206256e-01,0.477171,10,5
23,MQTT_IoT_IDS2020_UniflowFeatures,89,1.000000,0.424394,0.043829,0.632283,0.672651,0.009868,0.250000,0.951066,2.737764e-01,0.390191,0.712197,0.338056,0.341260,0.600533,3.319836e-01,0.464806,10,5
24,MQTT_IoT_IDS2020_UniflowFeatures,17,1.000000,0.435503,0.044157,0.633310,0.719130,0.009923,0.250000,0.951278,2.487793e-01,0.389953,0.717751,0.338734,0.364526,0.600639,3.193660e-01,0.468203,10,5
25,NIDS_CIC-ToN-IoT,53,1.000000,0.833616,0.078460,0.277968,0.850949,0.232234,0.239437,0.842353,3.288882e-01,0.492456,0.916808,0.178214,0.541591,0.540895,4.106721e-01,0.517636,10,5
26,NIDS_CIC-ToN-IoT,23,1.000000,0.834402,0.075449,0.292362,0.850498,0.233628,0.211268,0.843597,2.835513e-01,0.492544,0.917201,0.183905,0.542063,0.527432,3.880476e-01,0.511730,10,5
27,NIDS_CIC-ToN-IoT,37,1.000000,0.834212,0.078535,0.280036,0.850277,0.232509,0.211268,0.842916,3.211917e-01,0.492752,0.917106,0.179285,0.541393,0.527092,4.069719e-01,0.514370,10,5
28,NIDS_CIC-ToN-IoT,89,1.000000,0.834049,0.076581,0.287219,0.851114,0.235589,0.211268,0.842923,2.799042e-01,0.492575,0.917024,0.181900,0.543352,0.527095,3.862394e-01,0.511122,10,5
29,NIDS_CIC-ToN-IoT,17,1.000000,0.834201,0.076704,0.291062,0.850473,0.235035,0.211268,0.842928,3.165903e-01,0.492573,0.917100,0.183883,0.542754,0.527098,4.045815e-01,0.515083,10,5
30,NIDS_NF-ToN-IoT-v3,53,1.000000,0.777884,0.078268,0.403471,0.902917,0.255219,0.391304,0.796517,6.233136e-01,0.302820,0.888942,0.240869,0.579068,0.593911,4.630666e-01,0.553171,10,5
31,NIDS_NF-ToN-IoT-v3,23,1.000000,0.777879,0.075355,0.402832,0.904021,0.255916,0.391304,0.797092,6.250678e-01,0.303004,0.888939,0.239094,0.579969,0.594198,4.640359e-01,0.553247,10,5
32,NIDS_NF-ToN-IoT-v3,37,1.000000,0.777887,0.073774,0.396291,0.902909,0.253222,0.391304,0.799034,6.186396e-01,0.303034,0.888943,0.235033,0.578066,0.595169,4.608370e-01,0.551609,10,5
33,NIDS_NF-ToN-IoT-v3,89,1.000000,0.777890,0.077149,0.398724,0.902632,0.250356,0.391304,0.797343,6.150391e-01,0.302940,0.888945,0.237937,0.576494,0.594324,4.589897e-01,0.551338,10,5
34,NIDS_NF-ToN-IoT-v3,17,1.000000,0.777860,0.076027,0.403768,0.902306,0.256600,0.391304,0.798085,6.259857e-01,0.302911,0.888930,0.239898,0.579453,0.594694,4.644484e-01,0.553485,10,5
35,ToN_IoT_IoT_GPS_Tracker,53,1.000000,0.289271,0.000152,0.859755,1.000000,0.746761,0.500000,0.999211,5.686868e-12,0.301655,0.644636,0.429954,0.873380,0.749606,1.508275e-01,0.569681,10,5
36,ToN_IoT_IoT_GPS_Tracker,23,1.000000,0.290067,0.000153,0.860193,1.000000,0.748625,0.500000,0.999213,5.681434e-12,0.299888,0.645034,0.430173,0.874313,0.749606,1.499442e-01,0.569814,10,5
37,ToN_IoT_IoT_GPS_Tracker,37,1.000000,0.277923,0.000150,0.859825,1.000000,0.744407,0.500000,0.999208,6.625062e-12,0.303848,0.638961,0.429987,0.872204,0.749604,1.519240e-01,0.568536,10,5
38,ToN_IoT_IoT_GPS_Tracker,89,1.000000,0.290269,0.000149,0.859730,1.000000,0.747762,0.500000,0.999213,5.686063e-12,0.300753,0.645134,0.429940,0.873881,0.749606,1.503763e-01,0.569788,10,5
39,ToN_IoT_IoT_GPS_Tracker,17,1.000000,0.283300,0.000154,0.860786,1.000000,0.747835,0.500000,0.999212,5.684758e-12,0.300572,0.641650,0.430470,0.873917,0.749606,1.502861e-01,0.569186,10,5
40,ToN_IoT_Network,53,1.000000,0.836334,0.019747,0.637874,0.908443,0.410743,0.225000,0.953517,7.173546e-01,0.338003,0.918167,0.328810,0.659593,0.589259,5.276790e-01,0.604702,10,5
41,ToN_IoT_Network,23,1.000000,0.836347,0.019809,0.631239,0.909394,0.409573,0.200000,0.953635,7.031062e-01,0.338062,0.918173,0.325524,0.659483,0.576817,5.205841e-01,0.600116,10,5
42,ToN_IoT_Network,37,1.000000,0.836368,0.019954,0.629167,0.911268,0.409799,0.225000,0.953410,7.124843e-01,0.337807,0.918184,0.324560,0.660534,0.589205,5.251459e-01,0.603526,10,5
43,ToN_IoT_Network,89,1.000000,0.836474,0.020091,0.631991,0.910572,0.406174,0.200000,0.953536,7.183567e-01,0.338645,0.918237,0.326041,0.658373,0.576768,5.285006e-01,0.601584,10,5
44,ToN_IoT_Network,17,1.000000,0.836284,0.020021,0.628882,0.912740,0.407069,0.225000,0.953486,7.150301e-01,0.338062,0.918142,0.324452,0.659905,0.589243,5.265461e-01,0.603658,10,5
45,ToN_IoT_IoT_Motion_Light,53,1.000000,0.000000,0.006555,1.000000,0.920549,0.710681,0.500000,1.000000,9.053595e-11,0.000000,0.500000,0.503277,0.815615,0.750000,4.526798e-11,0.513779,8,5
46,ToN_IoT_IoT_Motion_Light,23,1.000000,0.000000,0.006555,1.000000,0.920549,0.710681,0.500000,1.000000,9.053595e-11,0.000000,0.500000,0.503277,0.815615,0.750000,4.526798e-11,0.513779,8,5
47,ToN_IoT_IoT_Motion_Light,37,1.000000,1.000000,0.000000,1.000000,1.000000,0.534395,0.000000,1.000000,7.543435e-11,0.053629,1.000000,0.500000,0.767198,0.500000,2.681443e-02,0.558802,7,4
48,ToN_IoT_IoT_Motion_Light,89,1.000000,1.000000,0.000000,1.000000,1.000000,0.534395,0.000000,1.000000,7.543435e-11,0.053629,1.000000,0.500000,0.767198,0.500000,2.681443e-02,0.558802,7,4
49,ToN_IoT_IoT_Motion_Light,17,1.000000,1.000000,0.000000,1.000000,0.889524,0.712677,0.000000,1.000000,9.053595e-11,0.000000,1.000000,0.500000,0.801100,0.500000,4.526798e-11,0.560220,7,4
50,ToN_IoT_Linux_Process,53,1.000000,0.910949,0.013716,0.597467,0.924422,0.479511,0.285714,0.993873,1.750304e-01,0.453929,0.955475,0.305591,0.701966,0.639793,3.144799e-01,0.583461,10,5
51,ToN_IoT_Linux_Process,23,1.000000,0.910538,0.013503,0.596693,0.924168,0.480161,0.285714,0.993553,1.785542e-01,0.454413,0.955269,0.305098,0.702165,0.639634,3.164837e-01,0.583730,10,5
52,ToN_IoT_Linux_Process,37,1.000000,0.910743,0.014602,0.597317,0.923354,0.477293,0.285714,0.993824,1.829222e-01,0.454946,0.955371,0.305959,0.700323,0.639769,3.189338e-01,0.584071,10,5
53,ToN_IoT_Linux_Process,89,1.000000,0.914272,0.013581,0.596465,0.923555,0.478804,0.285714,0.993910,1.848609e-01,0.455283,0.957136,0.305023,0.701180,0.639812,3.200718e-01,0.584644,10,5
54,ToN_IoT_Linux_Process,17,1.000000,0.914535,0.013296,0.596362,0.922114,0.478832,0.285714,0.993907,1.814433e-01,0.454989,0.957268,0.304829,0.700473,0.639811,3.182160e-01,0.584119,10,5
55,CICIoV2024_Decimal_Micro,53,1.000000,0.971518,0.016811,0.679946,0.736885,0.018092,0.375000,0.999909,1.560772e-01,0.959145,0.985759,0.348379,0.377489,0.687454,5.576112e-01,0.591338,10,5
56,CICIoV2024_Decimal_Micro,23,1.000000,0.965554,0.013631,1.000000,0.775942,0.019826,0.375000,0.999912,8.165037e-02,0.958432,0.982777,0.506815,0.397884,0.687456,5.200413e-01,0.618995,9,5
57,CICIoV2024_Decimal_Micro,37,1.000000,0.967451,0.016230,0.679861,0.779146,0.019864,0.375000,0.999910,1.570145e-01,0.956388,0.983725,0.348045,0.399505,0.687455,5.567014e-01,0.595086,10,5
58,CICIoV2024_Decimal_Micro,89,1.000000,0.964909,0.020051,1.000000,0.766079,0.019960,0.375000,0.999918,1.061859e-01,0.960054,0.982455,0.510026,0.393019,0.687459,5.331200e-01,0.621216,9,5
59,CICIoV2024_Decimal_Micro,17,1.000000,0.961825,0.016401,0.678605,0.780004,0.025214,0.375000,0.999892,7.512081e-02,0.949222,0.980912,0.347503,0.402609,0.687446,5.121715e-01,0.586128,10,5
60,NIDS_NF-CSE-CIC-IDS2018,53,1.000000,0.799843,0.111328,0.684140,0.829198,0.116622,0.400000,0.837065,1.272388e-01,0.780787,0.899921,0.397734,0.472910,0.618533,4.540127e-01,0.568622,10,5
61,NIDS_NF-CSE-CIC-IDS2018,23,1.000000,0.800516,0.109211,0.685727,0.832965,0.117355,0.400000,0.837988,4.034266e-02,0.781098,0.900258,0.397469,0.475160,0.618994,4.107201e-01,0.560520,10,5
62,NIDS_NF-CSE-CIC-IDS2018,37,1.000000,0.800433,0.109808,0.684174,0.829884,0.117209,0.400000,0.839557,1.095580e-01,0.780628,0.900216,0.396991,0.473546,0.619779,4.450931e-01,0.567125,10,5
63,NIDS_NF-CSE-CIC-IDS2018,89,1.000000,0.800498,0.108521,0.684702,0.832265,0.117049,0.400000,0.839405,5.202658e-02,0.780558,0.900249,0.396612,0.474657,0.619703,4.162921e-01,0.561502,10,5
64,NIDS_NF-CSE-CIC-IDS2018,17,1.000000,0.800279,0.109882,0.684589,0.830366,0.116392,0.400000,0.838032,9.015653e-02,0.781115,0.900139,0.397235,0.473379,0.619016,4.356357e-01,0.565081,10,5
65,N_BaIoT_Provision_PT_737E_Security_Camera,53,0.999999,0.295785,0.148807,0.364469,0.787248,0.070327,0.086957,0.894174,2.872973e-01,0.148514,0.647892,0.256638,0.428788,0.490565,2.179055e-01,0.408358,10,5
66,N_BaIoT_Provision_PT_737E_Security_Camera,23,0.999999,0.299811,0.140938,0.374053,0.797051,0.074849,0.086957,0.894366,3.006592e-01,0.148324,0.649905,0.257496,0.435950,0.490661,2.244915e-01,0.411701,10,5
67,N_BaIoT_Provision_PT_737E_Security_Camera,37,0.999999,0.296992,0.139472,0.366744,0.796531,0.068063,0.086957,0.894412,2.768369e-01,0.148529,0.648496,0.253108,0.432297,0.490684,2.126827e-01,0.407454,10,5
68,N_BaIoT_Provision_PT_737E_Security_Camera,89,0.999999,0.292455,0.133557,0.375522,0.799476,0.076573,0.086957,0.894627,2.666947e-01,0.148481,0.646227,0.254539,0.438024,0.490792,2.075879e-01,0.407434,10,5
69,N_BaIoT_Provision_PT_737E_Security_Camera,17,0.999999,0.294384,0.135029,0.366637,0.788903,0.074955,0.086957,0.894682,2.975765e-01,0.148617,0.647192,0.250833,0.431929,0.490819,2.230968e-01,0.408774,10,5
70,CICEVSE2024_EVSE-B_Micro,53,0.999998,0.203516,0.138343,0.553552,0.801787,0.208870,0.088235,0.931822,5.386726e-01,0.358806,0.601757,0.345947,0.505328,0.510028,4.487393e-01,0.482360,10,5
71,CICEVSE2024_EVSE-B_Micro,23,0.999998,0.203724,0.144498,0.553377,0.803288,0.209413,0.088235,0.931272,5.691259e-01,0.358725,0.601861,0.348938,0.506351,0.509754,4.639255e-01,0.486166,10,5
72,CICEVSE2024_EVSE-B_Micro,37,0.999998,0.203479,0.132493,0.550674,0.809469,0.209825,0.088235,0.932485,5.702831e-01,0.358466,0.601738,0.341584,0.509647,0.510360,4.643747e-01,0.485541,10,5
73,CICEVSE2024_EVSE-B_Micro,89,0.999998,0.201378,0.133400,0.553862,0.807017,0.208149,0.088235,0.932128,5.606750e-01,0.359194,0.600688,0.343631,0.507583,0.510182,4.599345e-01,0.484404,10,5
74,CICEVSE2024_EVSE-B_Micro,17,0.999998,0.198498,0.106978,0.553898,0.801008,0.208702,0.088235,0.933273,6.059301e-01,0.359096,0.599248,0.330438,0.504855,0.510754,4.825130e-01,0.485562,10,5
75,ToN_IoT_IoT_Weather,53,1.000000,0.944497,0.019138,0.785778,0.847559,0.327301,1.000000,0.994191,0.000000e+00,0.686206,0.972248,0.402458,0.587430,0.997096,3.431032e-01,0.660467,10,5
76,ToN_IoT_IoT_Weather,23,1.000000,0.944093,0.019198,0.785696,0.847417,0.326658,1.000000,0.994117,1.179612e-15,0.686685,0.972046,0.402447,0.587038,0.997058,3.433425e-01,0.660386,10,5
77,ToN_IoT_IoT_Weather,37,1.000000,0.944390,0.019248,0.785722,0.847418,0.326665,1.000000,0.994149,9.020562e-16,0.686675,0.972195,0.402485,0.587041,0.997074,3.433377e-01,0.660427,10,5
78,ToN_IoT_IoT_Weather,89,1.000000,0.944193,0.019332,0.785703,0.847483,0.326630,1.000000,0.994027,7.771561e-16,0.686593,0.972097,0.402517,0.587057,0.997014,3.432965e-01,0.660396,10,5
79,ToN_IoT_IoT_Weather,17,1.000000,0.944179,0.019552,0.785692,0.847399,0.326337,1.000000,0.994082,4.510281e-16,0.686768,0.972089,0.402622,0.586868,0.997041,3.433838e-01,0.660401,10,5
80,NIDS_CIC-BoT-IoT,53,1.000000,0.955433,0.317615,0.280644,0.967390,0.437045,0.139241,0.732223,8.100808e-01,0.337937,0.977717,0.299130,0.702218,0.435732,5.740088e-01,0.597761,10,5
81,NIDS_CIC-BoT-IoT,23,1.000000,0.954568,0.309088,0.280679,0.967173,0.435711,0.139241,0.724427,8.192452e-01,0.337985,0.977284,0.294883,0.701442,0.431834,5.786153e-01,0.596812,10,5
82,NIDS_CIC-BoT-IoT,37,1.000000,0.954984,0.310760,0.280394,0.966825,0.438016,0.139241,0.709076,8.197051e-01,0.338062,0.977492,0.295577,0.702421,0.424158,5.788838e-01,0.595706,10,5
83,NIDS_CIC-BoT-IoT,89,1.000000,0.953566,0.254132,0.280024,0.966041,0.434541,0.139241,0.712408,8.200835e-01,0.337773,0.976783,0.267078,0.700291,0.425824,5.789284e-01,0.589781,10,5
84,NIDS_CIC-BoT-IoT,17,1.000000,0.955280,0.320962,0.280313,0.966752,0.436086,0.139241,0.729196,7.733289e-01,0.337828,0.977640,0.300638,0.701419,0.434218,5.555786e-01,0.593899,10,5
85,CICIoV2024_Binary_Macro,53,1.000000,0.993154,0.029502,0.005537,0.745811,0.013332,0.426667,0.999846,2.788814e-01,0.940173,0.996577,0.017519,0.379571,0.713256,6.095272e-01,0.543290,10,5
86,CICIoV2024_Binary_Macro,23,1.000000,0.992568,0.028115,0.006486,0.746278,0.015673,0.440000,0.999839,2.497927e-01,0.930607,0.996284,0.017300,0.380976,0.719920,5.902001e-01,0.540936,10,5
87,CICIoV2024_Binary_Macro,37,1.000000,0.993772,0.033042,0.006255,0.732060,0.012001,0.426667,0.999848,2.074845e-01,0.947411,0.996886,0.019648,0.372031,0.713257,5.774477e-01,0.535854,10,5
88,CICIoV2024_Binary_Macro,89,1.000000,0.992820,0.032612,0.003375,0.723689,0.012146,0.440000,0.999821,1.360840e-01,0.937716,0.996410,0.017993,0.367917,0.719910,5.368999e-01,0.527826,10,5
89,CICIoV2024_Binary_Macro,17,1.000000,0.993764,0.026457,0.001910,0.746816,0.015783,0.453333,0.999874,3.142966e-01,0.935386,0.996882,0.014184,0.381299,0.726604,6.248412e-01,0.548762,10,5
90,ToN_IoT_Linux_Disk,53,1.000000,0.926155,0.018819,0.814203,0.898443,0.486290,0.666667,0.995695,1.193299e-03,0.501664,0.963077,0.416511,0.692366,0.831181,2.514289e-01,0.630913,10,5
91,ToN_IoT_Linux_Disk,23,1.000000,0.920501,0.019465,0.813150,0.898100,0.484480,0.666667,0.995524,6.099772e-04,0.502799,0.960251,0.416308,0.691290,0.831096,2.517045e-01,0.630130,10,5
92,ToN_IoT_Linux_Disk,37,1.000000,0.906240,0.020173,0.815258,0.898870,0.485869,0.666667,0.995610,9.115041e-03,0.500492,0.953120,0.417715,0.692370,0.831138,2.548035e-01,0.629829,10,5
93,ToN_IoT_Linux_Disk,89,1.000000,0.919055,0.019463,0.813665,0.898458,0.485235,0.666667,0.995547,1.488854e-03,0.501924,0.959527,0.416564,0.691847,0.831107,2.517065e-01,0.630150,10,5
94,ToN_IoT_Linux_Disk,17,1.000000,0.921148,0.017178,0.815407,0.898255,0.485855,0.666667,0.995769,6.726790e-04,0.502522,0.960574,0.416293,0.692055,0.831218,2.515974e-01,0.630347,10,5
95,UNSW_NB15,53,1.000000,0.948173,0.046691,0.292978,0.689826,0.034837,0.200000,0.951661,9.814880e-01,0.884272,0.974087,0.169834,0.362332,0.575831,9.328797e-01,0.602993,10,5
96,UNSW_NB15,23,1.000000,0.944746,0.046338,0.293656,0.683244,0.034730,0.200000,0.951037,9.581569e-01,0.884357,0.972373,0.169997,0.358987,0.575519,9.212570e-01,0.599626,10,5
97,UNSW_NB15,37,1.000000,0.945547,0.044988,0.292319,0.697282,0.034976,0.200000,0.951934,9.940627e-01,0.884247,0.972774,0.168654,0.366129,0.575967,9.391549e-01,0.604536,10,5
98,UNSW_NB15,89,1.000000,0.945095,0.046447,0.291477,0.684875,0.034672,0.200000,0.950394,1.000000e+00,0.884977,0.972548,0.168962,0.359773,0.575197,9.424884e-01,0.603794,10,5
99,UNSW_NB15,17,1.000000,0.947609,0.045255,0.292473,0.696262,0.035040,0.200000,0.953230,9.818467e-01,0.884535,0.973804,0.168864,0.365651,0.576615,9.331910e-01,0.603625,10,5
100,MQTT_IoT_IDS2020_PacketFeatures,53,1.000000,0.429370,0.017426,0.698509,0.826277,0.252466,0.411765,0.996873,4.727991e-01,0.155042,0.714685,0.357968,0.539371,0.704319,3.139208e-01,0.526053,10,5
101,MQTT_IoT_IDS2020_PacketFeatures,23,1.000000,0.416397,0.018477,0.703244,0.822422,0.245692,0.411765,0.996569,4.532227e-01,0.157921,0.708198,0.360861,0.534057,0.704167,3.055720e-01,0.522571,10,5
102,MQTT_IoT_IDS2020_PacketFeatures,37,1.000000,0.389742,0.016888,0.702120,0.824789,0.252608,0.411765,0.997101,4.538244e-01,0.157005,0.694871,0.359504,0.538698,0.704433,3.054146e-01,0.520584,10,5
103,MQTT_IoT_IDS2020_PacketFeatures,89,1.000000,0.463175,0.016177,0.697031,0.828545,0.258544,0.411765,0.997228,4.625315e-01,0.151882,0.731588,0.356604,0.543544,0.704496,3.072066e-01,0.528688,10,5

[sampled_50]	Found 365 JSON files to process

Computing composite difficulties:  20%|████████████████████████████████████▎                                                                                                                                              | 74/365 [00:00<00:01, 171.99it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean', 'intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Decimal_Micro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  61%|███████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                                                      | 221/365 [00:01<00:00, 169.01it/s]

[INFO] CICEVSE2024_EVSE-A_Macro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICEVSE2024_EVSE-A_Macro: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  71%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎                                                   | 259/365 [00:01<00:00, 176.90it/s]

[INFO] CICEVSE2024_EVSE-A_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICEVSE2024_EVSE-A_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] NIDS_NF-CICIDS2018-v3: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  81%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▊                                  | 295/365 [00:01<00:00, 173.31it/s]

[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] IoT_23: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties:  96%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▏      | 351/365 [00:02<00:00, 178.32it/s]

[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] CICIoV2024_Binary_Micro: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] KDD_Cup_1999: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']
[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:02<00:00, 172.04it/s]

[INFO] ToN_IoT_IoT_Garage_Door: Missing metrics: ['mahalanobis_class_distance_mean']

Normalizing metrics across 365 datasets...
[WARN] NaNs detected before normalization – filling with 0
Successfully processed 365 datasets
Average metrics used per dataset: 9.9
Average groups used per dataset: 5.0

,dataset_id,seed,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BoT_IoT_Macro,53,1.000000,0.909210,0.138115,0.577109,0.926751,0.301973,0.400000,0.821987,5.866308e-01,0.477004,0.954605,0.357612,0.614362,0.610993,0.531817,0.613878,10,5
1,BoT_IoT_Macro,23,1.000000,0.909065,0.145113,0.578332,0.927520,0.303151,0.350000,0.822648,5.682169e-01,0.476673,0.954532,0.361723,0.615336,0.586324,0.522445,0.608072,10,5
2,BoT_IoT_Macro,37,1.000000,0.907567,0.144901,0.577913,0.926496,0.302033,0.350000,0.823399,5.721912e-01,0.476553,0.953783,0.361407,0.614265,0.586699,0.524372,0.608105,10,5
3,BoT_IoT_Macro,89,1.000000,0.908160,0.150032,0.578312,0.926302,0.303101,0.400000,0.820398,6.023201e-01,0.476645,0.954080,0.364172,0.614702,0.610199,0.539482,0.616527,10,5
4,BoT_IoT_Macro,17,1.000000,0.909051,0.145358,0.578157,0.927152,0.302529,0.400000,0.817741,5.711958e-01,0.476847,0.954526,0.361757,0.614840,0.608871,0.524022,0.612803,10,5
5,NIDS_NF-ToN-IoT-v2,53,1.000000,0.753099,0.070135,0.405945,0.891963,0.344512,0.473684,0.940940,7.084482e-01,0.258153,0.876549,0.238040,0.618237,0.707312,0.483301,0.584688,10,5
6,NIDS_NF-ToN-IoT-v2,23,1.000000,0.762390,0.072576,0.410840,0.890550,0.350521,0.500000,0.943943,6.468731e-01,0.258282,0.881195,0.241708,0.620535,0.721971,0.452578,0.583597,10,5
7,NIDS_NF-ToN-IoT-v2,37,1.000000,0.755789,0.071014,0.402649,0.895308,0.348013,0.500000,0.940980,6.388013e-01,0.258210,0.877895,0.236831,0.621661,0.720490,0.448505,0.581076,10,5
8,NIDS_NF-ToN-IoT-v2,89,1.000000,0.753388,0.071568,0.405249,0.894353,0.347471,0.500000,0.940786,6.532804e-01,0.257979,0.876694,0.238408,0.620912,0.720393,0.455630,0.582407,10,5
9,NIDS_NF-ToN-IoT-v2,17,1.000000,0.759416,0.073477,0.411144,0.895918,0.348367,0.500000,0.944106,6.577991e-01,0.258101,0.879708,0.242310,0.622142,0.722053,0.457950,0.584833,10,5
10,ToN_IoT_Windows_7,53,1.000000,0.696215,0.177599,0.098220,0.651522,0.035303,0.250000,0.997666,1.228081e-01,0.605544,0.848108,0.137910,0.343412,0.623833,0.364176,0.463488,10,5
11,ToN_IoT_Windows_7,23,1.000000,0.694311,0.183635,0.098114,0.679488,0.036825,0.259615,0.997625,1.016913e-01,0.603066,0.847155,0.140874,0.358156,0.628620,0.352379,0.465437,10,5
12,ToN_IoT_Windows_7,37,1.000000,0.695567,0.180200,0.094488,0.653736,0.034620,0.250000,0.997635,9.875020e-02,0.605582,0.847783,0.137344,0.344178,0.623818,0.352166,0.461058,10,5
13,ToN_IoT_Windows_7,89,1.000000,0.702505,0.176500,0.098668,0.679071,0.036339,0.250000,0.997694,9.642414e-02,0.604932,0.851253,0.137584,0.357705,0.623847,0.350678,0.464213,10,5
14,ToN_IoT_Windows_7,17,1.000000,0.700276,0.177892,0.095362,0.658062,0.037177,0.259615,0.997640,1.010518e-01,0.602891,0.850138,0.136627,0.347620,0.628628,0.351972,0.462997,10,5
15,MQTT_IoT_IDS2020_BiflowFeatures,53,0.999994,0.308720,0.062047,0.646501,0.683850,0.007648,0.142857,0.974557,1.545264e-01,0.308754,0.654357,0.354274,0.345749,0.558707,0.231640,0.428945,10,5
16,MQTT_IoT_IDS2020_BiflowFeatures,23,0.999994,0.308777,0.058618,0.647129,0.678425,0.008488,0.142857,0.977658,1.485582e-01,0.308705,0.654386,0.352874,0.343456,0.560257,0.228632,0.427921,10,5
17,MQTT_IoT_IDS2020_BiflowFeatures,37,0.999994,0.308933,0.058442,0.649180,0.685906,0.008777,0.142857,0.977683,1.460080e-01,0.308153,0.654463,0.353811,0.347341,0.560270,0.227081,0.428593,10,5
18,MQTT_IoT_IDS2020_BiflowFeatures,89,0.999994,0.311574,0.057926,0.649103,0.689374,0.008763,0.142857,0.977181,1.457974e-01,0.307902,0.655784,0.353515,0.349068,0.560019,0.226850,0.429047,10,5
19,MQTT_IoT_IDS2020_BiflowFeatures,17,0.999994,0.315946,0.060768,0.648503,0.694994,0.008461,0.142857,0.976566,1.396262e-01,0.307961,0.657970,0.354635,0.351727,0.559711,0.223794,0.429568,10,5
20,MQTT_IoT_IDS2020_UniflowFeatures,53,1.000000,0.359753,0.041429,0.638358,0.640900,0.011567,0.250000,0.965563,2.665609e-01,0.390813,0.679877,0.339893,0.326233,0.607782,0.328687,0.456494,10,5
21,MQTT_IoT_IDS2020_UniflowFeatures,23,1.000000,0.400478,0.041990,0.639524,0.663504,0.011166,0.250000,0.965507,2.621666e-01,0.391600,0.700239,0.340757,0.337335,0.607754,0.326883,0.462594,10,5
22,MQTT_IoT_IDS2020_UniflowFeatures,37,1.000000,0.402590,0.042912,0.638507,0.680075,0.010402,0.250000,0.963229,2.675875e-01,0.389637,0.701295,0.340709,0.345238,0.606614,0.328612,0.464494,10,5
23,MQTT_IoT_IDS2020_UniflowFeatures,89,1.000000,0.298350,0.049502,0.630738,0.665529,0.008883,0.250000,0.949698,2.701846e-01,0.390539,0.649175,0.340120,0.337206,0.599849,0.330362,0.451342,10,5
24,MQTT_IoT_IDS2020_UniflowFeatures,17,1.000000,0.309779,0.049884,0.632078,0.660399,0.008775,0.250000,0.949754,2.467477e-01,0.390499,0.654889,0.340981,0.334587,0.599877,0.318623,0.449792,10,5
25,NIDS_CIC-ToN-IoT,53,1.000000,0.797893,0.086417,0.280575,0.828740,0.234990,0.239437,0.848618,3.145188e-01,0.492033,0.898947,0.183496,0.531865,0.544027,0.403276,0.512322,10,5
26,NIDS_CIC-ToN-IoT,23,1.000000,0.798107,0.084269,0.291617,0.828158,0.238061,0.211268,0.849624,3.192756e-01,0.492030,0.899053,0.187943,0.533110,0.530446,0.405653,0.511241,10,5
27,NIDS_CIC-ToN-IoT,37,1.000000,0.797549,0.087999,0.280173,0.828413,0.235764,0.225352,0.848719,3.211092e-01,0.492058,0.898774,0.184086,0.532088,0.537035,0.406584,0.511714,10,5
28,NIDS_CIC-ToN-IoT,89,1.000000,0.797798,0.085464,0.289454,0.828099,0.235265,0.211268,0.849186,3.093907e-01,0.492089,0.898899,0.187459,0.531682,0.530227,0.400740,0.509801,10,5
29,NIDS_CIC-ToN-IoT,17,1.000000,0.797340,0.084386,0.294134,0.829541,0.236332,0.211268,0.849290,3.145056e-01,0.491840,0.898670,0.189260,0.532937,0.530279,0.403173,0.510864,10,5
30,NIDS_NF-ToN-IoT-v3,53,1.000000,0.729230,0.087619,0.401490,0.887050,0.253008,0.391304,0.798121,6.118197e-01,0.302897,0.864615,0.244554,0.570029,0.594713,0.457358,0.546254,10,5
31,NIDS_NF-ToN-IoT-v3,23,1.000000,0.735662,0.083537,0.405341,0.889715,0.255884,0.413043,0.805442,6.253400e-01,0.302966,0.867831,0.244439,0.572800,0.609243,0.464153,0.551693,10,5
32,NIDS_NF-ToN-IoT-v3,37,1.000000,0.729108,0.082339,0.400939,0.888249,0.253716,0.391304,0.800573,6.319953e-01,0.302883,0.864554,0.241639,0.570982,0.595939,0.467439,0.548111,10,5
33,NIDS_NF-ToN-IoT-v3,89,1.000000,0.728939,0.083981,0.390063,0.886090,0.248504,0.391304,0.799486,6.128619e-01,0.302870,0.864470,0.237022,0.567297,0.595395,0.457866,0.544410,10,5
34,NIDS_NF-ToN-IoT-v3,17,1.000000,0.729202,0.084648,0.402402,0.888942,0.253987,0.391304,0.799851,6.223318e-01,0.302971,0.864601,0.243525,0.571465,0.595577,0.462651,0.547564,10,5
35,ToN_IoT_IoT_GPS_Tracker,53,1.000000,0.126095,0.000170,0.860258,1.000000,0.747854,0.500000,0.999382,5.672601e-12,0.300284,0.563048,0.430214,0.873927,0.749691,0.150142,0.553404,10,5
36,ToN_IoT_IoT_GPS_Tracker,23,1.000000,0.127126,0.000171,0.860148,0.995817,0.748575,0.500000,0.999384,5.672726e-12,0.299720,0.563563,0.430160,0.872196,0.749692,0.149860,0.553094,10,5
37,ToN_IoT_IoT_GPS_Tracker,37,1.000000,0.119015,0.000170,0.860144,1.000000,0.747086,0.500000,0.999379,5.672497e-12,0.300847,0.559508,0.430157,0.873543,0.749689,0.150423,0.552664,10,5
38,ToN_IoT_IoT_GPS_Tracker,89,1.000000,0.127334,0.000166,0.859680,1.000000,0.747709,0.500000,0.999385,5.677334e-12,0.300580,0.563667,0.429923,0.873855,0.749692,0.150290,0.553485,10,5
39,ToN_IoT_IoT_GPS_Tracker,17,1.000000,0.125830,0.000171,0.860516,1.000000,0.747657,0.500000,0.999385,5.676681e-12,0.300492,0.562915,0.430343,0.873828,0.749693,0.150246,0.553405,10,5
40,ToN_IoT_Network,53,1.000000,0.796519,0.021899,0.634257,0.896947,0.407505,0.225000,0.956201,7.103863e-01,0.336494,0.898260,0.328078,0.652226,0.590600,0.523440,0.598521,10,5
41,ToN_IoT_Network,23,1.000000,0.796555,0.021950,0.628965,0.898748,0.402530,0.200000,0.956318,7.108209e-01,0.336477,0.898277,0.325458,0.650639,0.578159,0.523649,0.595236,10,5
42,ToN_IoT_Network,37,1.000000,0.796542,0.021798,0.631347,0.897000,0.408412,0.225000,0.956213,7.131108e-01,0.336466,0.898271,0.326572,0.652706,0.590607,0.524788,0.598589,10,5
43,ToN_IoT_Network,89,1.000000,0.796699,0.022091,0.628776,0.896887,0.403455,0.200000,0.956258,7.154400e-01,0.336770,0.898349,0.325433,0.650171,0.578129,0.526105,0.595638,10,5
44,ToN_IoT_Network,17,1.000000,0.796415,0.021860,0.631925,0.897201,0.408157,0.225000,0.956291,7.127248e-01,0.336625,0.898208,0.326892,0.652679,0.590646,0.524675,0.598620,10,5
45,ToN_IoT_IoT_Motion_Light,53,1.000000,0.316782,0.003409,1.000000,0.874240,0.890587,0.500000,0.999997,7.514130e-11,0.032770,0.658391,0.501705,0.882414,0.749998,0.016385,0.561778,9,5
46,ToN_IoT_IoT_Motion_Light,23,1.000000,1.000000,0.000000,1.000000,0.874560,0.890764,0.000000,1.000000,7.514130e-11,0.032770,1.000000,0.500000,0.882662,0.500000,0.016385,0.579809,7,4
47,ToN_IoT_IoT_Motion_Light,37,1.000000,0.316782,0.003409,1.000000,0.874240,0.890587,0.500000,0.999997,7.514130e-11,0.032770,0.658391,0.501705,0.882414,0.749998,0.016385,0.561778,9,5
48,ToN_IoT_IoT_Motion_Light,89,1.000000,0.316782,0.003409,1.000000,0.874240,0.890587,0.500000,0.999997,7.514130e-11,0.032770,0.658391,0.501705,0.882413,0.749998,0.016385,0.561778,9,5
49,ToN_IoT_IoT_Motion_Light,17,1.000000,0.316782,0.003409,1.000000,0.874240,0.890587,0.500000,0.999997,7.514130e-11,0.032770,0.658391,0.501705,0.882414,0.749998,0.016385,0.561778,9,5
50,ToN_IoT_Linux_Process,53,1.000000,0.891500,0.015225,0.596577,0.912320,0.478323,0.285714,0.993937,1.732793e-01,0.452959,0.945750,0.305901,0.695321,0.639826,0.313119,0.579983,10,5
51,ToN_IoT_Linux_Process,23,1.000000,0.891401,0.015049,0.595771,0.912570,0.479810,0.285714,0.993713,1.793619e-01,0.453849,0.945700,0.305410,0.696190,0.639714,0.316606,0.580724,10,5
52,ToN_IoT_Linux_Process,37,1.000000,0.895061,0.015790,0.596406,0.911505,0.475028,0.285714,0.993863,1.816151e-01,0.456420,0.947530,0.306098,0.693266,0.639788,0.319018,0.581140,10,5
53,ToN_IoT_Linux_Process,89,1.000000,0.895823,0.014906,0.595857,0.911500,0.477546,0.285714,0.994013,1.800598e-01,0.455052,0.947911,0.305382,0.694523,0.639864,0.317556,0.581047,10,5
54,ToN_IoT_Linux_Process,17,1.000000,0.896255,0.015068,0.595359,0.909967,0.478380,0.285714,0.993911,1.794940e-01,0.455830,0.948127,0.305213,0.694174,0.639813,0.317662,0.580998,10,5
55,CICIoV2024_Decimal_Micro,53,1.000000,0.960656,0.017825,0.678535,0.743638,0.017789,0.375000,0.999896,1.238873e-01,0.955853,0.980328,0.348180,0.380713,0.687448,0.539870,0.587308,10,5
56,CICIoV2024_Decimal_Micro,23,1.000000,0.951211,0.019502,1.000000,0.745050,0.022045,0.375000,0.999930,7.257921e-02,0.959033,0.975605,0.509751,0.383548,0.687465,0.515806,0.614435,9,5
57,CICIoV2024_Decimal_Micro,37,1.000000,0.957673,0.020289,1.000000,0.744073,0.022608,0.375000,0.999936,6.221612e-02,0.961311,0.978837,0.510144,0.383340,0.687468,0.511763,0.614311,9,5
58,CICIoV2024_Decimal_Micro,89,1.000000,0.954322,0.019126,0.679303,0.746117,0.022303,0.375000,0.999933,6.221612e-02,0.960686,0.977161,0.349215,0.384210,0.687466,0.511451,0.581901,10,5
59,CICIoV2024_Decimal_Micro,17,1.000000,0.954946,0.018838,0.678955,0.712813,0.022796,0.375000,0.999914,7.151192e-02,0.954316,0.977473,0.348896,0.367805,0.687457,0.512914,0.578909,10,5
60,NIDS_NF-CSE-CIC-IDS2018,53,1.000000,0.749709,0.121051,0.684720,0.807632,0.116689,0.400000,0.844143,1.147323e-01,0.776788,0.874854,0.402886,0.462160,0.622072,0.445760,0.561546,10,5
61,NIDS_NF-CSE-CIC-IDS2018,23,1.000000,0.750541,0.120305,0.685656,0.807406,0.117671,0.400000,0.844525,8.349835e-02,0.777156,0.875270,0.402980,0.462538,0.622263,0.430327,0.558676,10,5
62,NIDS_NF-CSE-CIC-IDS2018,37,1.000000,0.750316,0.121153,0.685024,0.808288,0.116837,0.400000,0.844032,1.068747e-01,0.777235,0.875158,0.403089,0.462563,0.622016,0.442055,0.560976,10,5
63,NIDS_NF-CSE-CIC-IDS2018,89,1.000000,0.750035,0.119621,0.685579,0.803850,0.117023,0.400000,0.845291,4.714393e-02,0.776943,0.875017,0.402600,0.460436,0.622645,0.412044,0.554548,10,5
64,NIDS_NF-CSE-CIC-IDS2018,17,1.000000,0.750301,0.119646,0.685227,0.805017,0.117395,0.400000,0.843536,1.135787e-01,0.777252,0.875150,0.402436,0.461206,0.621768,0.445415,0.561195,10,5
65,N_BaIoT_Provision_PT_737E_Security_Camera,53,0.999999,0.146336,0.158470,0.358944,0.750793,0.066273,0.086957,0.898391,2.798294e-01,0.152915,0.573168,0.258707,0.408533,0.492674,0.216372,0.389891,10,5
66,N_BaIoT_Provision_PT_737E_Security_Camera,23,0.999999,0.141277,0.153500,0.369096,0.765951,0.071955,0.086957,0.898628,2.953743e-01,0.152926,0.570638,0.261298,0.418953,0.492792,0.224150,0.393566,10,5
67,N_BaIoT_Provision_PT_737E_Security_Camera,37,0.999999,0.144792,0.153685,0.363196,0.747246,0.063738,0.086957,0.898533,2.848353e-01,0.153403,0.572396,0.258440,0.405492,0.492745,0.219119,0.389638,10,5
68,N_BaIoT_Provision_PT_737E_Security_Camera,89,0.999999,0.139791,0.151677,0.370554,0.769889,0.073337,0.086957,0.898757,2.686211e-01,0.152909,0.569895,0.261116,0.421613,0.492857,0.210765,0.391249,10,5
69,N_BaIoT_Provision_PT_737E_Security_Camera,17,0.999999,0.148330,0.150008,0.360500,0.756534,0.071317,0.086957,0.898672,2.788973e-01,0.153306,0.574165,0.255254,0.413925,0.492814,0.216102,0.390452,10,5
70,CICEVSE2024_EVSE-B_Micro,53,0.999998,0.112212,0.196640,0.547822,0.781280,0.189768,0.088235,0.942033,5.614529e-01,0.377300,0.556105,0.372231,0.485524,0.515134,0.469376,0.479674,10,5
71,CICEVSE2024_EVSE-B_Micro,23,0.999998,0.091267,0.184317,0.549322,0.785459,0.189691,0.088235,0.942173,5.949655e-01,0.377721,0.545632,0.366820,0.487575,0.515204,0.486343,0.480315,10,5
72,CICEVSE2024_EVSE-B_Micro,37,0.999998,0.092098,0.180433,0.551162,0.777209,0.190473,0.088235,0.942816,5.955545e-01,0.377563,0.546048,0.365797,0.483841,0.515526,0.486559,0.479554,10,5
73,CICEVSE2024_EVSE-B_Micro,89,0.999998,0.115212,0.171503,0.550693,0.776236,0.188746,0.088235,0.943389,5.655718e-01,0.377787,0.557605,0.361098,0.482491,0.515812,0.471679,0.477737,10,5
74,CICEVSE2024_EVSE-B_Micro,17,0.999998,0.096934,0.137315,0.549129,0.772686,0.189033,0.088235,0.943898,6.298163e-01,0.378605,0.548466,0.343222,0.480859,0.516067,0.504211,0.478565,10,5
75,ToN_IoT_IoT_Weather,53,1.000000,0.932890,0.021216,0.785365,0.823776,0.326604,1.000000,0.994323,5.967449e-16,0.686775,0.966445,0.403290,0.575190,0.997162,0.343387,0.657095,10,5
76,ToN_IoT_IoT_Weather,23,1.000000,0.932236,0.021374,0.785273,0.823897,0.327220,1.000000,0.994176,9.783840e-16,0.686330,0.966118,0.403323,0.575559,0.997088,0.343165,0.657051,10,5
77,ToN_IoT_IoT_Weather,37,1.000000,0.932427,0.021195,0.785287,0.823960,0.326950,1.000000,0.994218,7.285839e-16,0.686293,0.966214,0.403241,0.575455,0.997109,0.343146,0.657033,10,5
78,ToN_IoT_IoT_Weather,89,1.000000,0.932694,0.021687,0.785292,0.823658,0.326044,1.000000,0.994175,1.929013e-15,0.687238,0.966347,0.403489,0.574851,0.997088,0.343619,0.657079,10,5
79,ToN_IoT_IoT_Weather,17,1.000000,0.932013,0.021683,0.785286,0.823778,0.326399,1.000000,0.994110,0.000000e+00,0.686741,0.966007,0.403485,0.575088,0.997055,0.343371,0.657001,10,5
80,NIDS_CIC-BoT-IoT,53,1.000000,0.942358,0.336879,0.274038,0.961342,0.433876,0.139241,0.764617,8.098748e-01,0.333413,0.971179,0.305458,0.697609,0.451929,0.571644,0.599564,10,5
81,NIDS_CIC-BoT-IoT,23,1.000000,0.942503,0.324985,0.274084,0.961078,0.434241,0.139241,0.763336,8.071558e-01,0.333202,0.971252,0.299534,0.697659,0.451288,0.570179,0.597983,10,5
82,NIDS_CIC-BoT-IoT,37,1.000000,0.941777,0.331974,0.273619,0.961423,0.435514,0.139241,0.756128,8.129125e-01,0.333346,0.970888,0.302797,0.698468,0.447684,0.573129,0.598593,10,5
83,NIDS_CIC-BoT-IoT,89,1.000000,0.943132,0.325325,0.273744,0.960690,0.435980,0.139241,0.759898,8.036338e-01,0.333276,0.971566,0.299534,0.698335,0.449569,0.568455,0.597492,10,5
84,NIDS_CIC-BoT-IoT,17,1.000000,0.943794,0.338242,0.273151,0.960441,0.434567,0.139241,0.765074,7.848955e-01,0.333102,0.971897,0.305697,0.697504,0.452157,0.558999,0.597251,10,5
85,CICIoV2024_Binary_Macro,53,1.000000,0.991200,0.030713,0.005017,0.703664,0.014786,0.440000,0.999846,2.571457e-01,0.930252,0.995600,0.017865,0.359225,0.719923,0.593699,0.537262,10,5
86,CICIoV2024_Binary_Macro,23,1.000000,0.991487,0.032199,0.002729,0.696474,0.013041,0.440000,0.999843,2.299631e-01,0.935798,0.995743,0.017464,0.354758,0.719921,0.582880,0.534154,10,5
87,CICIoV2024_Binary_Macro,37,1.000000,0.991836,0.030910,0.003986,0.705337,0.014194,0.440000,0.999858,3.218291e-01,0.937766,0.995918,0.017448,0.359765,0.719929,0.629798,0.544572,10,5
88,CICIoV2024_Binary_Macro,89,1.000000,0.991996,0.034696,0.004861,0.674613,0.011096,0.440000,0.999840,2.107128e-01,0.941444,0.995998,0.019778,0.342855,0.719920,0.576079,0.530926,10,5
89,CICIoV2024_Binary_Macro,17,1.000000,0.992036,0.031228,0.000000,0.705831,0.013196,0.453333,0.999861,3.033206e-01,0.937662,0.996018,0.015614,0.359514,0.726597,0.620491,0.543647,10,5
90,ToN_IoT_Linux_Disk,53,1.000000,0.911959,0.020341,0.814473,0.882913,0.486110,0.666667,0.995771,9.742294e-04,0.501139,0.955980,0.417407,0.684511,0.831219,0.251057,0.628035,10,5
91,ToN_IoT_Linux_Disk,23,1.000000,0.903536,0.021292,0.813700,0.881967,0.484468,0.666667,0.995725,1.220481e-03,0.503600,0.951768,0.417496,0.683217,0.831196,0.252410,0.627217,10,5
92,ToN_IoT_Linux_Disk,37,1.000000,0.896702,0.021273,0.815386,0.882666,0.484555,0.666667,0.995678,1.225936e-03,0.501820,0.948351,0.418330,0.683610,0.831173,0.251523,0.626597,10,5
93,ToN_IoT_Linux_Disk,89,1.000000,0.904511,0.021321,0.814168,0.882504,0.484082,0.666667,0.995625,1.219600e-03,0.502397,0.952255,0.417744,0.683293,0.831146,0.251808,0.627249,10,5
94,ToN_IoT_Linux_Disk,17,1.000000,0.903874,0.020039,0.814959,0.882330,0.485029,0.666667,0.995771,1.252295e-03,0.502873,0.951937,0.417499,0.683679,0.831219,0.252062,0.627279,10,5
95,UNSW_NB15,53,1.000000,0.937257,0.051406,0.291337,0.641602,0.034795,0.200000,0.952312,9.945968e-01,0.884613,0.968628,0.171372,0.338199,0.576156,0.939605,0.598792,10,5
96,UNSW_NB15,23,1.000000,0.936545,0.052071,0.292388,0.647200,0.034790,0.200000,0.951993,9.821118e-01,0.884606,0.968273,0.172229,0.340995,0.575997,0.933359,0.598170,10,5
97,UNSW_NB15,37,1.000000,0.935242,0.050227,0.290719,0.657734,0.034939,0.200000,0.952393,9.893665e-01,0.884522,0.967621,0.170473,0.346337,0.576196,0.936944,0.599514,10,5
98,UNSW_NB15,89,1.000000,0.934065,0.051377,0.290121,0.644646,0.034395,0.200000,0.951380,9.978489e-01,0.885470,0.967033,0.170749,0.339521,0.575690,0.941659,0.598930,10,5
99,UNSW_NB15,17,1.000000,0.936550,0.051150,0.290920,0.632892,0.034994,0.200000,0.952913,9.999999e-01,0.884896,0.968275,0.171035,0.333943,0.576457,0.942448,0.598431,10,5
100,MQTT_IoT_IDS2020_PacketFeatures,53,1.000000,0.296050,0.019767,0.704497,0.792268,0.229140,0.411765,0.996845,4.615265e-01,0.156761,0.648025,0.362132,0.510704,0.704305,0.309144,0.506862,10,5
101,MQTT_IoT_IDS2020_PacketFeatures,23,1.000000,0.288491,0.019910,0.703131,0.793231,0.230070,0.411765,0.996748,4.526948e-01,0.155717,0.644246,0.361521,0.511651,0.704257,0.304206,0.505176,10,5
102,MQTT_IoT_IDS2020_PacketFeatures,37,1.000000,0.310686,0.018959,0.703958,0.793561,0.231187,0.411765,0.997067,4.555459e-01,0.158616,0.655343,0.361458,0.512374,0.704416,0.307081,0.508134,10,5
103,MQTT_IoT_IDS2020_PacketFeatures,89,1.000000,0.309330,0.018624,0.692694,0.792325,0.240904,0.411765,0.997212,4.608792e-01,0.145438,0.654665,0.355659,0.516615,0.704488,0.303159,0.506917,10,5
104,MQTT_IoT_IDS2020_PacketFeatures,17,1.000000,0.243320,0.019010,0.698671,0.796621,0.239630,0.470588,0.997172,4.471628e-01,0.149185,0.621660,0.358840,0.518126,0.733880,0.298174,0.506136,10,5
105,N_BaIoT_Philips_B120N10_Baby_Monitor,53,0.999999,0.045502,0.142811,0.393516,0.763444,0.054715,0.121739,0.822493,3.159726e-01,0.181279,0.522750,0.268163,0.409080,0.472116,0.248626,0.384147,10,5
106,N_BaIoT_Philips_B120N10_Baby_Monitor,23,0.999999,0.039282,0.144521,0.392819,0.773262,0.054395,0.121739,0.822328,3.069648e-01,0.181458,0.519640,0.268670,0.413828,0.472034,0.244211,0.383677,10,5

[full]	Found 365 JSON files to process

Computing composite difficulties:  20%|███████████████████████████████████▊                                                                                                                                               | 73/365 [00:00<00:01, 157.83it/s]

[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics
[INFO] ToN_IoT_IoT_Motion_Light: Missing metrics: ['intrinsic_dimensionality_intrinsic_dimensionality_percent', 'calinski_harabasz_calinski_harabasz_score']
[WARN] ToN_IoT_IoT_Motion_Light: Group 'Global_Structure' has only 0 valid metrics

Computing composite difficulties: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 365/365 [00:02<00:00, 174.03it/s]

Normalizing metrics across 365 datasets...
[WARN] NaNs detected before normalization – filling with 0
Successfully processed 365 datasets
Average metrics used per dataset: 10.0
Average groups used per dataset: 5.0

,dataset_id,seed,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BoT_IoT_Macro,53,9.990109e-01,0.905087,1.953808e-01,0.574324,0.930997,0.281326,0.400000,0.796860,5.599416e-01,0.474375,0.952049,0.384852,0.606162,0.598430,5.171582e-01,0.611730,10,5
1,BoT_IoT_Macro,23,9.990102e-01,0.904999,1.951659e-01,0.574119,0.931711,0.280740,0.400000,0.796543,5.564919e-01,0.474375,0.952005,0.384643,0.606225,0.598271,5.154333e-01,0.611315,10,5
2,BoT_IoT_Macro,37,9.989980e-01,0.904655,1.949853e-01,0.573588,0.932095,0.281924,0.400000,0.796452,5.669234e-01,0.474290,0.951827,0.384286,0.607009,0.598226,5.206066e-01,0.612391,10,5
3,BoT_IoT_Macro,89,9.990067e-01,0.904951,1.978069e-01,0.575638,0.930924,0.280681,0.400000,0.794893,5.480427e-01,0.474375,0.951979,0.386722,0.605802,0.597446,5.112087e-01,0.610632,10,5
4,BoT_IoT_Macro,17,9.990058e-01,0.904931,1.963975e-01,0.576306,0.931205,0.279941,0.400000,0.794453,5.526984e-01,0.474375,0.951968,0.386352,0.605573,0.597227,5.135365e-01,0.610931,10,5
5,NIDS_NF-ToN-IoT-v2,53,9.994627e-01,0.758122,9.090987e-02,0.411062,0.903763,0.324082,0.526316,0.942216,6.578479e-01,0.258118,0.878792,0.250986,0.613923,0.734266,4.579832e-01,0.587190,10,5
6,NIDS_NF-ToN-IoT-v2,23,9.994628e-01,0.758127,9.079023e-02,0.411278,0.903749,0.324711,0.526316,0.942270,6.605473e-01,0.258116,0.878795,0.251034,0.614230,0.734293,4.593317e-01,0.587537,10,5
7,NIDS_NF-ToN-IoT-v2,37,9.994629e-01,0.758177,9.086151e-02,0.411087,0.903705,0.324435,0.526316,0.942290,6.673835e-01,0.258113,0.878820,0.250974,0.614070,0.734303,4.627483e-01,0.588183,10,5
8,NIDS_NF-ToN-IoT-v2,89,9.994629e-01,0.758175,9.080595e-02,0.412872,0.903234,0.323039,0.526316,0.942289,6.619249e-01,0.258118,0.878819,0.251839,0.613136,0.734303,4.600216e-01,0.587624,10,5
9,NIDS_NF-ToN-IoT-v2,17,9.994629e-01,0.758164,9.090070e-02,0.412817,0.904169,0.323603,0.526316,0.942288,6.791548e-01,0.258118,0.878814,0.251859,0.613886,0.734302,4.686365e-01,0.589499,10,5
10,ToN_IoT_Windows_7,53,9.999939e-01,0.700563,2.257193e-01,0.098756,0.684920,0.031300,0.259615,0.997587,9.972940e-02,0.603416,0.850278,0.162237,0.358110,0.628601,3.515725e-01,0.470160,10,5
11,ToN_IoT_Windows_7,23,9.999939e-01,0.700563,2.257194e-01,0.098756,0.692901,0.031311,0.259615,0.997587,9.972940e-02,0.603416,0.850278,0.162237,0.362106,0.628601,3.515725e-01,0.470959,10,5
12,ToN_IoT_Windows_7,37,9.999939e-01,0.700563,2.257193e-01,0.098756,0.692381,0.031273,0.259615,0.997587,9.953444e-02,0.603416,0.850278,0.162237,0.361827,0.628601,3.514750e-01,0.470884,10,5
13,ToN_IoT_Windows_7,89,9.999939e-01,0.700563,2.257193e-01,0.098756,0.681526,0.031269,0.259615,0.997587,9.972940e-02,0.603416,0.850278,0.162237,0.356397,0.628601,3.515725e-01,0.469817,10,5
14,ToN_IoT_Windows_7,17,9.999939e-01,0.700563,2.257194e-01,0.098756,0.674403,0.031277,0.259615,0.997587,9.953412e-02,0.603416,0.850278,0.162237,0.352840,0.628601,3.514749e-01,0.469086,10,5
15,MQTT_IoT_IDS2020_BiflowFeatures,53,9.673835e-01,0.308484,7.554759e-02,0.646521,0.709143,0.006595,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357869,0.559139,2.352132e-01,0.430238,10,5
16,MQTT_IoT_IDS2020_BiflowFeatures,23,9.673835e-01,0.308484,7.554761e-02,0.646521,0.709262,0.006589,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357926,0.559139,2.352132e-01,0.430249,10,5
17,MQTT_IoT_IDS2020_BiflowFeatures,37,9.673835e-01,0.308484,7.554761e-02,0.646521,0.709375,0.006585,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357980,0.559139,2.352132e-01,0.430260,10,5
18,MQTT_IoT_IDS2020_BiflowFeatures,89,9.673835e-01,0.308484,7.554761e-02,0.646521,0.709351,0.006598,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357975,0.559139,2.352132e-01,0.430259,10,5
19,MQTT_IoT_IDS2020_BiflowFeatures,17,9.673835e-01,0.308484,7.554762e-02,0.646521,0.709493,0.006593,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.358043,0.559139,2.352132e-01,0.430273,10,5
20,MQTT_IoT_IDS2020_UniflowFeatures,53,9.997424e-01,0.400214,5.368856e-02,0.638872,0.689221,0.008769,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.348995,0.606537,3.426387e-01,0.468886,10,5
21,MQTT_IoT_IDS2020_UniflowFeatures,23,9.997424e-01,0.400214,5.368856e-02,0.638872,0.685617,0.008781,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.347199,0.606537,3.426387e-01,0.468527,10,5
22,MQTT_IoT_IDS2020_UniflowFeatures,37,9.997424e-01,0.400214,5.368856e-02,0.638872,0.687578,0.008784,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.348181,0.606537,3.426387e-01,0.468723,10,5
23,MQTT_IoT_IDS2020_UniflowFeatures,89,9.997424e-01,0.400214,5.368856e-02,0.638872,0.689506,0.008785,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.349145,0.606537,3.426387e-01,0.468916,10,5
24,MQTT_IoT_IDS2020_UniflowFeatures,17,9.997424e-01,0.400214,5.368854e-02,0.638872,0.690492,0.008770,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.349631,0.606537,3.426387e-01,0.469013,10,5
25,NIDS_CIC-ToN-IoT,53,9.992393e-01,0.797475,1.080334e-01,0.277671,0.839471,0.220916,0.225352,0.854849,3.141673e-01,0.491422,0.898357,0.192852,0.530193,0.540101,4.027945e-01,0.512860,10,5
26,NIDS_CIC-ToN-IoT,23,9.992623e-01,0.798135,1.080685e-01,0.284574,0.840951,0.223933,0.225352,0.855095,3.231879e-01,0.491411,0.898699,0.196321,0.532442,0.540224,4.072995e-01,0.514997,10,5
27,NIDS_CIC-ToN-IoT,37,9.992615e-01,0.797344,1.079968e-01,0.277484,0.842973,0.221060,0.225352,0.855101,3.251455e-01,0.491420,0.898303,0.192741,0.532017,0.540226,4.082828e-01,0.514314,10,5
28,NIDS_CIC-ToN-IoT,89,9.992395e-01,0.797176,1.080491e-01,0.285403,0.840288,0.223126,0.225352,0.854837,3.168623e-01,0.491440,0.898208,0.196726,0.531707,0.540094,4.041510e-01,0.514177,10,5
29,NIDS_CIC-ToN-IoT,17,9.992397e-01,0.797351,1.080185e-01,0.286013,0.841582,0.223482,0.225352,0.854894,3.138355e-01,0.491439,0.898295,0.197016,0.532532,0.540123,4.026371e-01,0.514121,10,5
30,NIDS_NF-ToN-IoT-v3,53,9.979925e-01,0.733420,1.053384e-01,0.396687,0.894775,0.234045,0.413043,0.799057,6.232846e-01,0.303022,0.865707,0.251013,0.564410,0.606050,4.631532e-01,0.550067,10,5
31,NIDS_NF-ToN-IoT-v3,23,9.979938e-01,0.733824,1.052858e-01,0.397578,0.899020,0.238573,0.413043,0.799805,6.296524e-01,0.303022,0.865909,0.251432,0.568797,0.606424,4.663371e-01,0.551780,10,5
32,NIDS_NF-ToN-IoT-v3,37,9.979929e-01,0.733509,1.053298e-01,0.396277,0.895540,0.234514,0.413043,0.799352,6.236324e-01,0.303022,0.865751,0.250803,0.565027,0.606198,4.633271e-01,0.550221,10,5
33,NIDS_NF-ToN-IoT-v3,89,9.979883e-01,0.733521,1.053614e-01,0.395199,0.897140,0.249980,0.413043,0.796771,6.379240e-01,0.303022,0.865754,0.250280,0.573560,0.604907,4.704729e-01,0.552995,10,5
34,NIDS_NF-ToN-IoT-v3,17,9.979924e-01,0.733879,1.053866e-01,0.396543,0.894238,0.236622,0.413043,0.798999,6.300032e-01,0.303022,0.865936,0.250965,0.565430,0.606021,4.665125e-01,0.550973,10,5
35,ToN_IoT_IoT_GPS_Tracker,53,9.999987e-01,0.122881,2.157580e-04,0.859865,1.000000,0.699605,0.500000,0.999556,5.738576e-12,0.300372,0.561440,0.430040,0.849802,0.749778,1.501862e-01,0.548249,10,5
36,ToN_IoT_IoT_GPS_Tracker,23,9.999988e-01,0.123915,2.158538e-04,0.859755,0.996088,0.700275,0.500000,0.999558,5.738701e-12,0.299809,0.561957,0.429986,0.848181,0.749779,1.499044e-01,0.547961,10,5
37,ToN_IoT_IoT_GPS_Tracker,37,9.999987e-01,0.125187,2.152721e-04,0.859980,1.000000,0.699208,0.500000,0.999556,5.737841e-12,0.300849,0.562593,0.430098,0.849604,0.749778,1.504244e-01,0.548499,10,5
38,ToN_IoT_IoT_GPS_Tracker,89,9.999988e-01,0.123915,2.158538e-04,0.859755,0.996088,0.700275,0.500000,0.999558,5.738701e-12,0.299809,0.561957,0.429986,0.848181,0.749779,1.499044e-01,0.547962,10,5
39,ToN_IoT_IoT_GPS_Tracker,17,9.999987e-01,0.122881,2.157580e-04,0.859865,1.000000,0.699604,0.500000,0.999556,5.738576e-12,0.300372,0.561440,0.430040,0.849802,0.749778,1.501862e-01,0.548249,10,5
40,ToN_IoT_Network,53,9.995618e-01,0.793010,2.828796e-02,0.628008,0.902635,0.376225,0.250000,0.962807,7.202668e-01,0.334798,0.896286,0.328148,0.639430,0.606404,5.275325e-01,0.599560,10,5
41,ToN_IoT_Network,23,9.995618e-01,0.792983,2.795603e-02,0.627632,0.903489,0.372536,0.250000,0.962834,7.200864e-01,0.334798,0.896272,0.327794,0.638013,0.606417,5.274423e-01,0.599188,10,5
42,ToN_IoT_Network,37,9.995619e-01,0.792946,2.809416e-02,0.627677,0.901390,0.375541,0.250000,0.962869,7.180846e-01,0.334798,0.896254,0.327886,0.638465,0.606434,5.264413e-01,0.599096,10,5
43,ToN_IoT_Network,89,9.995619e-01,0.792890,2.795829e-02,0.627719,0.903023,0.376059,0.250000,0.962869,7.188163e-01,0.334798,0.896226,0.327839,0.639541,0.606435,5.268072e-01,0.599370,10,5
44,ToN_IoT_Network,17,9.995619e-01,0.793013,2.774921e-02,0.627971,0.902783,0.375548,0.250000,0.962887,7.229789e-01,0.334798,0.896287,0.327860,0.639166,0.606444,5.288885e-01,0.599729,10,5
45,ToN_IoT_IoT_Motion_Light,53,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8,4
46,ToN_IoT_IoT_Motion_Light,23,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8,4
47,ToN_IoT_IoT_Motion_Light,37,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8,4
48,ToN_IoT_IoT_Motion_Light,89,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8,4
49,ToN_IoT_IoT_Motion_Light,17,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8,4
50,ToN_IoT_Linux_Process,53,9.999868e-01,0.893493,2.023510e-02,0.594970,0.917895,0.444735,0.285714,0.993551,1.854767e-01,0.455410,0.946740,0.307603,0.681315,0.639632,3.204431e-01,0.579147,10,5
51,ToN_IoT_Linux_Process,23,9.999869e-01,0.887002,1.895214e-02,0.595177,0.915973,0.444817,0.285714,0.993633,1.759891e-01,0.455410,0.943494,0.307065,0.680395,0.639674,3.156993e-01,0.577265,10,5
52,ToN_IoT_Linux_Process,37,9.999868e-01,0.890343,1.950279e-02,0.594997,0.918194,0.443788,0.285714,0.993533,1.811571e-01,0.455410,0.945165,0.307250,0.680991,0.639624,3.182833e-01,0.578263,10,5
53,ToN_IoT_Linux_Process,89,9.999869e-01,0.893662,1.918299e-02,0.595085,0.917353,0.444538,0.285714,0.993747,1.981777e-01,0.455410,0.946825,0.307134,0.680945,0.639731,3.267936e-01,0.580286,10,5
54,ToN_IoT_Linux_Process,17,9.999870e-01,0.897832,2.015648e-02,0.595252,0.918891,0.445452,0.285714,0.993812,1.802144e-01,0.455410,0.948910,0.307704,0.682171,0.639763,3.178120e-01,0.579272,10,5
55,CICIoV2024_Decimal_Micro,53,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742463,0.021809,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382136,0.687465,5.157882e-01,0.582334,10,5
56,CICIoV2024_Decimal_Micro,23,9.999995e-01,0.952777,2.211537e-02,0.677674,0.742463,0.021798,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382131,0.687465,5.157882e-01,0.582333,10,5
57,CICIoV2024_Decimal_Micro,37,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742463,0.021804,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382134,0.687465,5.157882e-01,0.582334,10,5
58,CICIoV2024_Decimal_Micro,89,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742462,0.021807,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382135,0.687465,5.157882e-01,0.582334,10,5
59,CICIoV2024_Decimal_Micro,17,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742465,0.021810,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382137,0.687465,5.157882e-01,0.582335,10,5
60,NIDS_NF-CSE-CIC-IDS2018,53,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819746,0.110075,0.400000,0.847841,3.835871e-02,0.771732,0.869922,0.417307,0.464911,0.623920,4.050451e-01,0.556221,10,5
61,NIDS_NF-CSE-CIC-IDS2018,23,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819742,0.110170,0.400000,0.847841,1.054733e-01,0.771732,0.869922,0.417307,0.464956,0.623920,4.386024e-01,0.562942,10,5
62,NIDS_NF-CSE-CIC-IDS2018,37,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819745,0.109631,0.400000,0.847841,3.867751e-02,0.771732,0.869922,0.417307,0.464688,0.623920,4.052045e-01,0.556208,10,5
63,NIDS_NF-CSE-CIC-IDS2018,89,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819746,0.109836,0.400000,0.847841,3.633051e-02,0.771732,0.869922,0.417307,0.464791,0.623920,4.040310e-01,0.555994,10,5
64,NIDS_NF-CSE-CIC-IDS2018,17,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819744,0.110128,0.400000,0.847841,3.876682e-02,0.771732,0.869922,0.417307,0.464936,0.623920,4.052492e-01,0.556267,10,5
65,N_BaIoT_Provision_PT_737E_Security_Camera,53,9.959677e-01,0.146994,1.955219e-01,0.352088,0.763309,0.057889,0.086957,0.901245,2.674785e-01,0.161226,0.571481,0.273805,0.410599,0.494101,2.143525e-01,0.392868,10,5
66,N_BaIoT_Provision_PT_737E_Security_Camera,23,9.959902e-01,0.140512,1.954629e-01,0.361228,0.782113,0.062918,0.086957,0.901353,2.748365e-01,0.161242,0.568251,0.278345,0.422516,0.494155,2.180395e-01,0.396261,10,5
67,N_BaIoT_Provision_PT_737E_Security_Camera,37,9.959475e-01,0.146626,1.955069e-01,0.355130,0.757807,0.055668,0.086957,0.901261,2.631478e-01,0.161290,0.571287,0.275319,0.406737,0.494109,2.122191e-01,0.391934,10,5
68,N_BaIoT_Provision_PT_737E_Security_Camera,89,9.959496e-01,0.142100,1.955006e-01,0.363474,0.792348,0.063784,0.086957,0.901231,2.707669e-01,0.161240,0.569025,0.279487,0.428066,0.494094,2.160033e-01,0.397335,10,5
69,N_BaIoT_Provision_PT_737E_Security_Camera,17,9.959603e-01,0.146301,1.954919e-01,0.352714,0.762051,0.062528,0.086957,0.901251,2.780378e-01,0.161260,0.571130,0.274103,0.412289,0.494104,2.196489e-01,0.394255,10,5
70,CICEVSE2024_EVSE-B_Micro,53,9.901133e-01,0.107470,2.252710e-01,0.545099,0.770765,0.148383,0.088235,0.943530,5.935617e-01,0.405028,0.548792,0.385185,0.459574,0.515882,4.992947e-01,0.481746,10,5
71,CICEVSE2024_EVSE-B_Micro,23,9.901136e-01,0.107442,2.252662e-01,0.545340,0.791469,0.148513,0.088235,0.943532,6.081367e-01,0.405022,0.548778,0.385303,0.469991,0.515884,5.065793e-01,0.485307,10,5
72,CICEVSE2024_EVSE-B_Micro,37,9.901136e-01,0.107442,2.252661e-01,0.545340,0.794427,0.148734,0.088235,0.943532,5.729057e-01,0.405022,0.548778,0.385303,0.471581,0.515884,4.889638e-01,0.482102,10,5
73,CICEVSE2024_EVSE-B_Micro,89,9.901137e-01,0.107435,2.252647e-01,0.545234,0.779490,0.148919,0.088235,0.943533,5.844227e-01,0.405023,0.548775,0.385249,0.464204,0.515884,4.947230e-01,0.481767,10,5
74,CICEVSE2024_EVSE-B_Micro,17,9.899707e-01,0.106611,2.253122e-01,0.544816,0.787962,0.147493,0.088235,0.943644,6.485116e-01,0.405819,0.548291,0.385064,0.467728,0.515940,5.271655e-01,0.488838,10,5
75,ToN_IoT_IoT_Weather,53,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305360,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570278,0.997033,3.434317e-01,0.656582,10,5
76,ToN_IoT_IoT_Weather,23,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305280,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570238,0.997033,3.434317e-01,0.656574,10,5
77,ToN_IoT_IoT_Weather,37,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305469,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570332,0.997033,3.434317e-01,0.656593,10,5
78,ToN_IoT_IoT_Weather,89,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305248,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570222,0.997033,3.434317e-01,0.656571,10,5
79,ToN_IoT_IoT_Weather,17,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305316,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570256,0.997033,3.434317e-01,0.656578,10,5
80,NIDS_CIC-BoT-IoT,53,9.994142e-01,0.934744,3.885087e-01,0.266013,0.961654,0.405572,0.139241,0.804524,8.084733e-01,0.324697,0.967079,0.327261,0.683613,0.471882,5.665851e-01,0.603284,10,5
81,NIDS_CIC-BoT-IoT,23,9.994161e-01,0.934936,3.873146e-01,0.265071,0.962362,0.405538,0.139241,0.804424,7.872389e-01,0.324781,0.967176,0.326193,0.683950,0.471832,5.560101e-01,0.601032,10,5
82,NIDS_CIC-BoT-IoT,37,9.994159e-01,0.934165,3.863499e-01,0.264838,0.962901,0.405114,0.139241,0.805350,8.029879e-01,0.324633,0.966790,0.325594,0.684007,0.472295,5.638105e-01,0.602500,10,5
83,NIDS_CIC-BoT-IoT,89,9.994119e-01,0.934170,3.853294e-01,0.264621,0.962168,0.406371,0.139241,0.805740,7.580630e-01,0.324299,0.966791,0.324975,0.684270,0.472490,5.411810e-01,0.597941,10,5
84,NIDS_CIC-BoT-IoT,17,9.994156e-01,0.934160,3.874467e-01,0.264678,0.961812,0.405776,0.139241,0.804910,8.068162e-01,0.324447,0.966788,0.326062,0.683794,0.472075,5.656316e-01,0.602870,10,5
85,CICIoV2024_Binary_Macro,53,9.999992e-01,0.991681,4.063189e-02,0.000000,0.715435,0.010565,0.440000,0.999844,2.099103e-01,0.936375,0.995840,0.020316,0.363000,0.719922,5.731428e-01,0.534444,10,5
86,CICIoV2024_Binary_Macro,23,9.999992e-01,0.991681,4.063189e-02,0.000000,0.711527,0.010562,0.440000,0.999844,2.099103e-01,0.936375,0.995840,0.020316,0.361044,0.719922,5.731428e-01,0.534053,10,5
87,CICIoV2024_Binary_Macro,37,9.999992e-01,0.991681,4.063189e-02,0.000000,0.718177,0.010565,0.440000,0.999844,2.099103e-01,0.936375,0.995840,0.020316,0.364371,0.719922,5.731428e-01,0.534718,10,5
88,CICIoV2024_Binary_Macro,89,9.999992e-01,0.991681,4.063189e-02,0.000000,0.713630,0.010565,0.440000,0.999844,2.099103e-01,0.936375,0.995840,0.020316,0.362097,0.719922,5.731428e-01,0.534264,10,5
89,CICIoV2024_Binary_Macro,17,9.999992e-01,0.991681,4.063189e-02,0.000000,0.715614,0.010564,0.440000,0.999844,2.099103e-01,0.936375,0.995840,0.020316,0.363089,0.719922,5.731428e-01,0.534462,10,5
90,ToN_IoT_Linux_Disk,53,9.999899e-01,0.906238,2.656051e-02,0.814540,0.890119,0.453034,0.666667,0.995637,1.006547e-03,0.502506,0.953114,0.420550,0.671576,0.831152,2.517564e-01,0.625630,10,5
91,ToN_IoT_Linux_Disk,23,9.999899e-01,0.908268,2.564784e-02,0.814116,0.890194,0.452446,0.666667,0.995616,9.731364e-04,0.502506,0.954129,0.419882,0.671320,0.831142,2.517397e-01,0.625642,10,5
92,ToN_IoT_Linux_Disk,37,9.999900e-01,0.905017,2.565990e-02,0.816374,0.890077,0.453676,0.666667,0.995674,9.982338e-04,0.502506,0.952504,0.421017,0.671876,0.831170,2.517523e-01,0.625664,10,5
93,ToN_IoT_Linux_Disk,89,9.999897e-01,0.894847,2.534728e-02,0.814004,0.890171,0.451700,0.666667,0.995548,8.702559e-04,0.502506,0.947418,0.419676,0.670935,0.831108,2.516882e-01,0.624165,10,5
94,ToN_IoT_Linux_Disk,17,9.999901e-01,0.897690,2.497808e-02,0.814730,0.890047,0.454468,0.666667,0.995744,1.006547e-03,0.502506,0.948840,0.419854,0.672258,0.831205,2.517564e-01,0.624783,10,5
95,UNSW_NB15,53,9.994934e-01,0.938298,6.463378e-02,0.289345,0.676507,0.032299,0.200000,0.952066,9.976799e-01,0.885322,0.968896,0.176990,0.354403,0.576033,9.415011e-01,0.603564,10,5
96,UNSW_NB15,23,9.994909e-01,0.937631,6.462340e-02,0.290284,0.661133,0.032306,0.200000,0.951951,9.997904e-01,0.885349,0.968561,0.177454,0.346720,0.575976,9.425699e-01,0.602256,10,5
97,UNSW_NB15,37,9.994934e-01,0.938241,6.463276e-02,0.288642,0.656042,0.032385,0.200000,0.952070,1.000000e+00,0.885323,0.968867,0.176637,0.344214,0.576035,9.426615e-01,0.601683,10,5
98,UNSW_NB15,89,9.994879e-01,0.938369,6.447998e-02,0.288256,0.676594,0.032095,0.200000,0.951927,9.962403e-01,0.886267,0.968929,0.176368,0.354345,0.575964,9.412536e-01,0.603372,10,5
99,UNSW_NB15,17,9.994886e-01,0.937226,6.458541e-02,0.288968,0.662499,0.032212,0.200000,0.951939,9.931883e-01,0.885554,0.968357,0.176777,0.347355,0.575969,9.393710e-01,0.601566,10,5

In [8]:
for frac in SAMPLE_FRACS:

    print(frac)
    try:
        df_composite[frac] = df_composite[frac].groupby('dataset_id', as_index=False).mean(numeric_only=True).drop(columns=['seed'])
    except Exception as e:
        print('error', e)
        continue

display(df_composite['full'])

sampled_05
error 'dataset_id'
sampled_10
sampled_20
sampled_25
sampled_50
full

,dataset_id,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
0,BCCC_CIC-BCCC-NRC-ACI-IOT-2023,9.999275e-01,0.804043,5.363762e-02,0.362441,0.925368,0.510467,0.273973,0.991203,5.952467e-01,0.237416,0.901985,0.208040,0.717917,0.632588,4.163311e-01,0.575372,10.0,5.0
1,BCCC_CIC-BCCC-NRC-Edge-IIoTSet-2022,9.958051e-01,0.782120,2.257247e-01,0.499741,0.712437,0.012031,0.173913,0.743210,2.978558e-01,0.752202,0.888962,0.362733,0.362234,0.458562,5.250289e-01,0.519504,10.0,5.0
2,BCCC_CIC-BCCC-NRC-IoMT-2024,9.997652e-01,0.682533,1.997377e-01,0.301290,0.833293,0.166076,0.219178,0.930076,7.373126e-01,0.452544,0.841149,0.250514,0.499685,0.574627,5.949281e-01,0.552181,10.0,5.0
3,BCCC_CIC-BCCC-NRC-IoT-2022,9.999865e-01,0.982795,9.218891e-02,0.301410,0.032206,0.003036,0.263889,0.998275,9.655223e-02,0.901102,0.991391,0.196799,0.017621,0.631082,4.988274e-01,0.467144,10.0,5.0
4,BCCC_CIC-BCCC-NRC-IoT-2023-Original_Training_a...,9.992814e-01,0.603465,1.102160e-01,0.416148,0.773053,0.055111,0.267606,0.925620,5.503181e-01,0.398317,0.801373,0.263182,0.414082,0.596613,4.743176e-01,0.509914,10.0,5.0
5,BCCC_CIC-BCCC-NRC-IoT-HCRL-2019,9.999248e-01,0.738776,1.860812e-01,0.565708,0.810843,0.138997,0.260274,0.984388,8.223315e-01,0.432346,0.869351,0.375894,0.474920,0.622331,6.273388e-01,0.593967,10.0,5.0
6,BCCC_CIC-BCCC-NRC-MQTTIoT-IDS-2020,9.879524e-01,0.170644,6.683876e-02,0.357698,0.701070,0.042604,0.101449,0.014240,4.779768e-01,0.440618,0.579298,0.212268,0.371837,0.057844,4.592977e-01,0.336109,10.0,5.0
7,BCCC_CIC-BCCC-NRC-TONIoT-2021,9.996886e-01,0.903233,8.204560e-02,0.312916,0.683617,0.053069,0.239437,0.948634,6.630396e-01,0.668412,0.951461,0.197481,0.368343,0.594035,6.657256e-01,0.555409,10.0,5.0
8,BCCC_CIC-BCCC-NRC-UQ-IOT-2022,9.989427e-01,0.907023,6.242871e-01,0.451664,0.737776,0.018467,0.202899,0.910938,4.125024e-01,0.466369,0.952983,0.537975,0.378122,0.556918,4.394355e-01,0.573087,10.0,5.0
9,BoT_IoT_Macro,9.990063e-01,0.904925,1.959473e-01,0.574795,0.931386,0.280922,0.400000,0.795840,5.568196e-01,0.474358,0.951965,0.385371,0.606154,0.597920,5.155886e-01,0.611400,10.0,5.0
10,BoT_IoT_Micro,9.982967e-01,0.457380,2.099127e-01,0.619429,0.920630,0.254009,0.400000,0.780061,5.785961e-01,0.322393,0.727838,0.414671,0.587320,0.590030,4.504946e-01,0.554071,10.0,5.0
11,CICAPT_IIoT_Phase2_Macro,9.999998e-01,0.999903,2.804442e-02,0.324078,0.703825,0.000065,0.187500,0.999909,4.579899e-12,1.000000,0.999951,0.176061,0.351945,0.593704,4.999999e-01,0.524332,10.0,5.0
12,CICAPT_IIoT_Phase2_Micro,9.999993e-01,0.999912,3.975927e-02,0.323462,0.704362,0.000002,0.187500,0.999718,3.137309e-04,0.999828,0.999956,0.181611,0.352182,0.593609,5.000709e-01,0.525486,10.0,5.0
13,CICEVSE2024_EVSE-A_Macro,9.944040e-01,0.338065,9.890660e-01,0.682688,0.751610,0.098192,0.161765,0.889242,4.967044e-01,0.300088,0.666235,0.835877,0.424901,0.525503,3.983962e-01,0.570182,10.0,5.0
14,CICEVSE2024_EVSE-A_Micro,2.384186e-08,0.152679,1.000000e+00,0.720742,0.765844,0.096109,0.161765,0.879377,3.558992e-01,0.254939,0.076340,0.860371,0.430977,0.520571,3.054189e-01,0.438735,10.0,5.0
15,CICEVSE2024_EVSE-B_Macro,9.974090e-01,0.325122,2.723329e-01,0.498453,0.713821,0.104767,0.088235,0.925856,5.878595e-01,0.546603,0.661266,0.385393,0.409294,0.507045,5.672312e-01,0.506046,10.0,5.0
16,CICEVSE2024_EVSE-B_Micro,9.900850e-01,0.107280,2.252760e-01,0.545166,0.784822,0.148409,0.088235,0.943554,6.015077e-01,0.405183,0.548683,0.385221,0.466615,0.515895,5.033453e-01,0.483952,10.0,5.0
17,CICIoMT2024_Bluetooth,9.999534e-01,0.931189,5.155764e-02,0.745418,0.632683,0.015121,0.428571,0.994021,1.292438e-13,0.886177,0.965571,0.398488,0.323902,0.711296,4.430884e-01,0.568469,10.0,5.0
18,CICIoMT2024_WiFi_and_MQTT,9.901643e-01,0.259640,1.456568e-01,0.490625,0.885712,0.206006,0.295455,0.000066,4.769428e-01,0.213208,0.624902,0.318141,0.545859,0.147760,3.450756e-01,0.396348,10.0,5.0
19,CICIoV2024_Binary_Macro,9.999992e-01,0.991681,4.063189e-02,0.000000,0.714876,0.010564,0.440000,0.999844,2.099102e-01,0.936375,0.995840,0.020316,0.362720,0.719922,5.731428e-01,0.534388,10.0,5.0
20,CICIoV2024_Binary_Micro,9.999996e-01,0.990027,5.197570e-02,0.001601,0.737836,0.013039,0.440000,0.999922,3.559847e-01,0.957409,0.995013,0.026789,0.375438,0.719961,6.566969e-01,0.554779,10.0,5.0
21,CICIoV2024_Decimal_Macro,9.999989e-01,0.958127,2.491147e-02,0.677100,0.753205,0.017522,0.375000,0.999841,1.485186e-01,0.938872,0.979063,0.351005,0.385364,0.687420,5.436953e-01,0.589310,10.0,5.0
22,CICIoV2024_Decimal_Micro,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742463,0.021806,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382135,0.687465,5.157882e-01,0.582334,10.0,5.0
23,CIC_IDS_2017,9.998266e-01,0.781049,1.912842e-01,0.171354,0.752435,0.013494,0.185714,0.963209,2.994197e-01,0.762430,0.890438,0.181319,0.382964,0.574462,5.309249e-01,0.512022,10.0,5.0
24,CIC_IOT_Dataset2023,9.956639e-01,0.251654,1.252598e-01,0.392455,0.928340,0.422491,0.333333,0.232210,7.643563e-01,0.143047,0.623659,0.258858,0.675416,0.282772,4.537015e-01,0.458881,10.0,5.0
25,EDGE-IIOTSET_DNN-EdgeIIoT,9.588555e-01,0.705752,2.397037e-01,0.534184,0.772503,0.105087,0.244444,0.525221,6.274710e-01,0.547195,0.832304,0.386944,0.438795,0.384832,5.873330e-01,0.526042,10.0,5.0
26,EDGE-IIOTSET_ML-EdgeIIoT,9.905225e-01,0.571808,9.061216e-02,0.665914,0.843454,0.338502,0.219512,0.944743,6.247728e-01,0.058823,0.781165,0.378263,0.590978,0.582128,3.417981e-01,0.534866,10.0,5.0
27,IoT_23,9.997946e-01,0.811357,3.200495e-01,0.718751,0.800901,0.111346,0.500000,0.996208,5.767349e-01,0.764896,0.905576,0.519400,0.456124,0.748104,6.708153e-01,0.660004,10.0,5.0
28,IoT_Network_Intrusion_Macro,9.999914e-01,0.960318,3.919903e-02,0.576205,0.825956,0.177117,0.192308,0.998002,3.391479e-01,0.705840,0.980155,0.307702,0.501537,0.595155,5.224940e-01,0.581409,10.0,5.0
29,IoT_Network_Intrusion_Micro,9.999951e-01,0.955576,4.725233e-02,0.578219,0.831009,0.179887,0.192308,0.999066,1.983134e-01,0.795674,0.977786,0.312736,0.505448,0.595687,4.969937e-01,0.577730,10.0,5.0
30,KDD_Cup_1999,9.900512e-01,0.730730,1.031493e-01,0.548376,0.737175,0.008383,0.200000,0.844604,3.807039e-01,0.790417,0.860391,0.325763,0.372779,0.522302,5.855603e-01,0.533359,10.0,5.0
31,MQTT_IoT_IDS2020_BiflowFeatures,9.673835e-01,0.308484,7.554761e-02,0.646521,0.709325,0.006592,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357958,0.559139,2.352132e-01,0.430256,10.0,5.0
32,MQTT_IoT_IDS2020_PacketFeatures,9.999873e-01,0.297269,2.464260e-02,0.704571,0.802848,0.194654,0.411765,0.996902,4.521913e-01,0.154540,0.648628,0.364607,0.498751,0.704334,3.033656e-01,0.503937,10.0,5.0
33,MQTT_IoT_IDS2020_UniflowFeatures,9.997424e-01,0.400214,5.368856e-02,0.638872,0.688483,0.008778,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.348630,0.606537,3.426387e-01,0.468813,10.0,5.0
34,NIDS_CIC-BoT-IoT,9.994147e-01,0.934435,3.869899e-01,0.265044,0.962179,0.405674,0.139241,0.804990,7.927159e-01,0.324571,0.966925,0.326017,0.683927,0.472115,5.586437e-01,0.601525,10.0,5.0
35,NIDS_CIC-ToN-IoT,9.992485e-01,0.797496,1.080333e-01,0.282229,0.841053,0.222503,0.225352,0.854955,3.186397e-01,0.491426,0.898372,0.195131,0.531778,0.540154,4.050330e-01,0.514094,10.0,5.0
36,NIDS_NF-BoT-IoT,9.999136e-01,0.845027,5.524115e-02,0.710901,0.938690,0.457547,0.500000,0.982745,7.618958e-01,0.234256,0.922470,0.383071,0.698119,0.741373,4.980758e-01,0.648622,10.0,5.0
37,NIDS_NF-BoT-IoT-v2,9.998018e-01,0.648105,8.122462e-02,0.454383,0.862591,0.235514,0.421053,0.972101,5.456977e-01,0.181790,0.823954,0.267804,0.549053,0.696577,3.637438e-01,0.540226,10.0,5.0
38,NIDS_NF-BoT-IoT-v3,9.993187e-01,0.838307,3.071614e-01,0.447938,0.895002,0.224528,0.347826,0.847979,4.275848e-01,0.430602,0.918813,0.377549,0.559765,0.597903,4.290935e-01,0.576625,10.0,5.0
39,NIDS_NF-CICIDS2018-v3,9.979488e-01,0.822935,4.924437e-01,0.362760,0.774919,0.016076,0.311111,0.429903,2.299139e-01,0.825319,0.910442,0.427602,0.395498,0.370507,5.276163e-01,0.526333,10.0,5.0
40,NIDS_NF-CSE-CIC-IDS2018,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819745,0.109968,0.400000,0.847841,5.152137e-02,0.771732,0.869922,0.417307,0.464856,0.623920,4.116264e-01,0.557526,10.0,5.0
41,NIDS_NF-CSE-CIC-IDS2018-v2,9.972093e-01,0.570009,2.934940e-01,0.475589,0.782013,0.029088,0.432432,0.681455,1.984773e-01,0.655540,0.783609,0.384541,0.405550,0.556944,4.270086e-01,0.511531,10.0,5.0
42,NIDS_NF-ToN-IoT,9.996490e-01,0.832900,2.254714e-02,0.740245,0.956721,0.515314,0.500000,0.985307,3.709058e-01,0.363437,0.916275,0.381396,0.736018,0.742654,3.671713e-01,0.628703,10.0,5.0
43,NIDS_NF-ToN-IoT-v2,9.994629e-01,0.758153,9.085365e-02,0.411823,0.903724,0.323974,0.526316,0.942271,6.653717e-01,0.258117,0.878808,0.251339,0.613849,0.734293,4.617442e-01,0.588007,10.0,5.0
44,NIDS_NF-ToN-IoT-v3,9.979919e-01,0.733631,1.053404e-01,0.396457,0.896143,0.238747,0.413043,0.798797,6.288993e-01,0.303022,0.865811,0.250899,0.567445,0.605920,4.659605e-01,0.551207,10.0,5.0
45,NIDS_NF-UNSW-NB15,9.999369e-01,0.886361,6.075505e-02,0.665660,0.812733,0.178194,0.500000,0.989751,3.985922e-01,0.758286,0.943149,0.363208,0.495464,0.744876,5.784394e-01,0.625027,10.0,5.0
46,NIDS_NF-UNSW-NB15-v2,9.999655e-01,0.712018,5.990264e-02,0.347677,0.825116,0.238743,0.315789,0.994593,9.681040e-01,0.554122,0.855992,0.203790,0.531929,0.655191,7.611129e-01,0.601603,10.0,5.0
47,NIDS_NF-UNSW-NB15-v3,9.971269e-01,0.862882,5.436258e-02,0.330046,0.620502,0.044757,0.239130,0.978180,5.953562e-01,0.828727,0.930004,0.192204,0.332630,0.608655,7.120418e-01,0.555107,10.0,5.0
48,NIDS_NF-UQ-NIDS,9.999116e-01,0.688482,7.529153e-02,0.691450,0.878791,0.372328,0.600000,0.985005,3.931232e-01,0.571788,0.844197,0.383371,0.625560,0.792503,4.824558e-01,0.625617,10.0,5.0
49,NIDS_NF-UQ-NIDS-v2,9.995468e-01,0.661143,1.375339e-01,0.431633,0.862838,0.221355,0.500000,0.932424,7.096007e-01,0.472423,0.830345,0.284584,0.542097,0.716212,5.910119e-01,0.592850,10.0,5.0
50,N_BaIoT_Danmini_Doorbell,8.077890e-01,0.006694,3.557229e-01,0.404863,0.746302,0.030916,0.113043,0.840779,2.319586e-01,0.201346,0.407241,0.380293,0.388609,0.476911,2.166522e-01,0.373941,10.0,5.0
51,N_BaIoT_Ecobee_Thermostat,9.870348e-01,0.099721,2.909971e-01,0.371329,0.784277,0.050348,0.095652,0.814317,2.749381e-01,0.207924,0.543378,0.331163,0.417312,0.454985,2.414313e-01,0.397654,10.0,5.0
52,N_BaIoT_Ennio_Doorbell,9.971145e-01,0.315551,6.713064e-01,0.374658,0.791202,0.110401,0.184348,0.941012,2.669636e-01,0.239961,0.656332,0.522982,0.450801,0.562680,2.534625e-01,0.489252,10.0,5.0
53,N_BaIoT_Philips_B120N10_Baby_Monitor,9.926977e-01,0.037358,1.848409e-01,0.387385,0.784786,0.047994,0.121739,0.824147,3.254043e-01,0.188952,0.515028,0.286113,0.416390,0.472943,2.571782e-01,0.389530,10.0,5.0
54,N_BaIoT_Provision_PT_737E_Security_Camera,9.959631e-01,0.144506,1.954969e-01,0.356927,0.771526,0.060557,0.086957,0.901268,2.708535e-01,0.161252,0.570235,0.276212,0.416041,0.494112,2.160526e-01,0.394531,10.0,5.0
55,N_BaIoT_Provision_PT_838_Security_Camera,9.988122e-01,0.120344,1.891862e-01,0.307433,0.745268,0.078514,0.086957,0.902893,3.318023e-01,0.178743,0.559578,0.248310,0.411891,0.494925,2.552727e-01,0.393995,10.0,5.0
56,N_BaIoT_Samsung_SNH_1011_N_Webcam,9.949719e-01,0.179009,3.200131e-01,0.424713,0.782675,0.123299,0.156522,0.866647,3.443983e-01,0.251406,0.586991,0.372363,0.452987,0.511585,2.979023e-01,0.444365,10.0,5.0
57,N_BaIoT_SimpleHome_XCS7_1002_WHT_Security_Camera,9.887168e-01,0.010781,2.074122e-01,0.366233,0.776141,0.043414,0.113043,0.882608,2.846214e-01,0.182630,0.499749,0.286822,0.409778,0.497826,2.336257e-01,0.385560,10.0,5.0
58,N_BaIoT_SimpleHome_XCS7_1003_WHT_Security_Camera,9.803270e-01,0.097767,2.969757e-01,0.368652,0.775694,0.046191,0.139130,0.885114,2.894869e-01,0.201055,0.539047,0.332814,0.410942,0.512122,2.452711e-01,0.408039,10.0,5.0
59,ToN_IoT_IoT_Fridge,1.000000e+00,1.000000,1.645835e-11,0.824563,0.829680,0.935760,1.000000,1.000000,5.607459e-13,0.000000,1.000000,0.412282,0.882720,1.000000,2.803729e-13,0.659000,10.0,5.0
60,ToN_IoT_IoT_GPS_Tracker,9.999987e-01,0.123756,2.156991e-04,0.859844,0.998435,0.699793,0.500000,0.999557,5.738479e-12,0.300242,0.561877,0.430030,0.849114,0.749778,1.501211e-01,0.548184,10.0,5.0
61,ToN_IoT_IoT_Garage_Door,1.000000e+00,0.787961,1.271221e-03,0.974095,0.867351,0.982230,0.500000,0.999992,4.262451e-11,0.017440,0.893981,0.487683,0.924791,0.749996,8.720249e-03,0.613034,10.0,5.0
62,ToN_IoT_IoT_Modbus,1.000000e+00,0.996904,1.950573e-03,0.738486,0.859097,0.345178,1.000000,0.999994,8.316264e-14,0.599356,0.998452,0.370218,0.602137,0.999997,2.996782e-01,0.654096,10.0,5.0
63,ToN_IoT_IoT_Motion_Light,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8.0,4.0
64,ToN_IoT_IoT_Thermostat,9.999858e-01,0.881294,5.590344e-03,0.829815,0.903940,0.645457,0.500000,0.998657,2.908224e-01,0.262382,0.940640,0.417703,0.774698,0.749329,2.766020e-01,0.631794,10.0,5.0
65,ToN_IoT_IoT_Weather,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305335,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570265,0.997033,3.434317e-01,0.656579,10.0,5.0
66,ToN_IoT_Linux_Disk,9.999899e-01,0.902412,2.563872e-02,0.814753,0.890122,0.453065,0.666667,0.995644,9.709440e-04,0.502506,0.951201,0.420196,0.671593,0.831155,2.517386e-01,0.625177,10.0,5.0
67,ToN_IoT_Linux_Memory,9.999903e-01,0.931654,3.279572e-02,0.714735,0.865269,0.372665,0.900000,0.996236,6.984788e-02,0.535496,0.965822,0.373765,0.618967,0.948118,3.026721e-01,0.641869,10.0,5.0
68,ToN_IoT_Linux_Process,9.999869e-01,0.892466,1.960590e-02,0.595096,0.917661,0.444666,0.285714,0.993655,1.842030e-01,0.455410,0.946226,0.307351,0.681164,0.639685,3.198063e-01,0.578846,10.0,5.0
69,ToN_IoT_Network,9.995619e-01,0.792968,2.800913e-02,0.627802,0.902664,0.375182,0.250000,0.962853,7.200466e-01,0.334798,0.896265,0.327905,0.638923,0.606427,5.274223e-01,0.599388,10.0,5.0
70,ToN_IoT_Windows_10,9.999887e-01,0.603178,1.747106e-01,0.004695,0.603374,0.039766,0.306037,0.996328,1.412207e-01,0.490952,0.801583,0.089703,0.321570,0.651182,3.160864e-01,0.436025,10.0,5.0
71,ToN_IoT_Windows_7,9.999939e-01,0.700563,2.257194e-01,0.098756,0.685226,0.031286,0.259615,0.997587,9.965135e-02,0.603416,0.850278,0.162237,0.358256,0.628601,3.515335e-01,0.470181,10.0,5.0
72,UNSW_NB15,9.994909e-01,0.937953,6.459107e-02,0.289099,0.666555,0.032260,0.200000,0.951991,9.973798e-01,0.885563,0.968722,0.176845,0.349407,0.575995,9.414715e-01,0.602488,10.0,5.0

In [9]:
df_composite_indexed = {}
df_ordered = {}

for frac in SAMPLE_FRACS:

    print(frac)

    try:
        
        # Set index to dataset_id
        df_composite_indexed[frac] = df_composite[frac].set_index('dataset_id')
        
        # Filter row_order to only include datasets that exist in the DataFrame
        valid_order = [d for d in row_order if d in df_composite_indexed[frac].index]
        
        # Reorder using the filtered list
        df_ordered[frac] = df_composite_indexed[frac].loc[valid_order]
        
        # Export to LaTeX with thousands separator
        df_ordered[frac].style.format(thousands=",").to_latex(f"tables/complexity_metrics_{frac}.tex")
        
        df_ordered[frac].to_excel(f'tables/complexity_metrics_{frac}.xlsx')
        df_ordered[frac].to_json(f'tables/complexity_metrics_{frac}.json', orient='index')

    except Exception as e:
        print('error', e)
        continue

sampled_05
error "None of ['dataset_id'] are in the columns"
sampled_10
sampled_20
sampled_25
sampled_50
full

In [10]:
df_ordered['full']

,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,Feature_Relevance_difficulty,Local_Overlap_difficulty,Boundary_Hardness_difficulty,Global_Structure_difficulty,Class_Distribution_Separation_difficulty,overall_difficulty,metrics_used,groups_used
dataset_id,,,,,,,,,,,,,,,,,,
CIC_IDS_2017,9.998266e-01,0.781049,1.912842e-01,0.171354,0.752435,0.013494,0.185714,0.963209,2.994197e-01,0.762430,0.890438,0.181319,0.382964,0.574462,5.309249e-01,0.512022,10.0,5.0
CIC_IOT_Dataset2023,9.956639e-01,0.251654,1.252598e-01,0.392455,0.928340,0.422491,0.333333,0.232210,7.643563e-01,0.143047,0.623659,0.258858,0.675416,0.282772,4.537015e-01,0.458881,10.0,5.0
IoT_23,9.997946e-01,0.811357,3.200495e-01,0.718751,0.800901,0.111346,0.500000,0.996208,5.767349e-01,0.764896,0.905576,0.519400,0.456124,0.748104,6.708153e-01,0.660004,10.0,5.0
IoT_Network_Intrusion_Macro,9.999914e-01,0.960318,3.919903e-02,0.576205,0.825956,0.177117,0.192308,0.998002,3.391479e-01,0.705840,0.980155,0.307702,0.501537,0.595155,5.224940e-01,0.581409,10.0,5.0
IoT_Network_Intrusion_Micro,9.999951e-01,0.955576,4.725233e-02,0.578219,0.831009,0.179887,0.192308,0.999066,1.983134e-01,0.795674,0.977786,0.312736,0.505448,0.595687,4.969937e-01,0.577730,10.0,5.0
KDD_Cup_1999,9.900512e-01,0.730730,1.031493e-01,0.548376,0.737175,0.008383,0.200000,0.844604,3.807039e-01,0.790417,0.860391,0.325763,0.372779,0.522302,5.855603e-01,0.533359,10.0,5.0
UNSW_NB15,9.994909e-01,0.937953,6.459107e-02,0.289099,0.666555,0.032260,0.200000,0.951991,9.973798e-01,0.885563,0.968722,0.176845,0.349407,0.575995,9.414715e-01,0.602488,10.0,5.0
BCCC_CIC-BCCC-NRC-ACI-IOT-2023,9.999275e-01,0.804043,5.363762e-02,0.362441,0.925368,0.510467,0.273973,0.991203,5.952467e-01,0.237416,0.901985,0.208040,0.717917,0.632588,4.163311e-01,0.575372,10.0,5.0
BCCC_CIC-BCCC-NRC-Edge-IIoTSet-2022,9.958051e-01,0.782120,2.257247e-01,0.499741,0.712437,0.012031,0.173913,0.743210,2.978558e-01,0.752202,0.888962,0.362733,0.362234,0.458562,5.250289e-01,0.519504,10.0,5.0
BCCC_CIC-BCCC-NRC-IoMT-2024,9.997652e-01,0.682533,1.997377e-01,0.301290,0.833293,0.166076,0.219178,0.930076,7.373126e-01,0.452544,0.841149,0.250514,0.499685,0.574627,5.949281e-01,0.552181,10.0,5.0
BCCC_CIC-BCCC-NRC-IoT-2022,9.999865e-01,0.982795,9.218891e-02,0.301410,0.032206,0.003036,0.263889,0.998275,9.655223e-02,0.901102,0.991391,0.196799,0.017621,0.631082,4.988274e-01,0.467144,10.0,5.0
BCCC_CIC-BCCC-NRC-IoT-2023-Original_Training_and_Testing,9.992814e-01,0.603465,1.102160e-01,0.416148,0.773053,0.055111,0.267606,0.925620,5.503181e-01,0.398317,0.801373,0.263182,0.414082,0.596613,4.743176e-01,0.509914,10.0,5.0
BCCC_CIC-BCCC-NRC-IoT-HCRL-2019,9.999248e-01,0.738776,1.860812e-01,0.565708,0.810843,0.138997,0.260274,0.984388,8.223315e-01,0.432346,0.869351,0.375894,0.474920,0.622331,6.273388e-01,0.593967,10.0,5.0
BCCC_CIC-BCCC-NRC-MQTTIoT-IDS-2020,9.879524e-01,0.170644,6.683876e-02,0.357698,0.701070,0.042604,0.101449,0.014240,4.779768e-01,0.440618,0.579298,0.212268,0.371837,0.057844,4.592977e-01,0.336109,10.0,5.0
BCCC_CIC-BCCC-NRC-TONIoT-2021,9.996886e-01,0.903233,8.204560e-02,0.312916,0.683617,0.053069,0.239437,0.948634,6.630396e-01,0.668412,0.951461,0.197481,0.368343,0.594035,6.657256e-01,0.555409,10.0,5.0
BCCC_CIC-BCCC-NRC-UQ-IOT-2022,9.989427e-01,0.907023,6.242871e-01,0.451664,0.737776,0.018467,0.202899,0.910938,4.125024e-01,0.466369,0.952983,0.537975,0.378122,0.556918,4.394355e-01,0.573087,10.0,5.0
BoT_IoT_Macro,9.990063e-01,0.904925,1.959473e-01,0.574795,0.931386,0.280922,0.400000,0.795840,5.568196e-01,0.474358,0.951965,0.385371,0.606154,0.597920,5.155886e-01,0.611400,10.0,5.0
BoT_IoT_Micro,9.982967e-01,0.457380,2.099127e-01,0.619429,0.920630,0.254009,0.400000,0.780061,5.785961e-01,0.322393,0.727838,0.414671,0.587320,0.590030,4.504946e-01,0.554071,10.0,5.0
CICAPT_IIoT_Phase2_Macro,9.999998e-01,0.999903,2.804442e-02,0.324078,0.703825,0.000065,0.187500,0.999909,4.579899e-12,1.000000,0.999951,0.176061,0.351945,0.593704,4.999999e-01,0.524332,10.0,5.0
CICAPT_IIoT_Phase2_Micro,9.999993e-01,0.999912,3.975927e-02,0.323462,0.704362,0.000002,0.187500,0.999718,3.137309e-04,0.999828,0.999956,0.181611,0.352182,0.593609,5.000709e-01,0.525486,10.0,5.0
CICEVSE2024_EVSE-A_Macro,9.944040e-01,0.338065,9.890660e-01,0.682688,0.751610,0.098192,0.161765,0.889242,4.967044e-01,0.300088,0.666235,0.835877,0.424901,0.525503,3.983962e-01,0.570182,10.0,5.0
CICEVSE2024_EVSE-A_Micro,2.384186e-08,0.152679,1.000000e+00,0.720742,0.765844,0.096109,0.161765,0.879377,3.558992e-01,0.254939,0.076340,0.860371,0.430977,0.520571,3.054189e-01,0.438735,10.0,5.0
CICEVSE2024_EVSE-B_Macro,9.974090e-01,0.325122,2.723329e-01,0.498453,0.713821,0.104767,0.088235,0.925856,5.878595e-01,0.546603,0.661266,0.385393,0.409294,0.507045,5.672312e-01,0.506046,10.0,5.0
CICEVSE2024_EVSE-B_Micro,9.900850e-01,0.107280,2.252760e-01,0.545166,0.784822,0.148409,0.088235,0.943554,6.015077e-01,0.405183,0.548683,0.385221,0.466615,0.515895,5.033453e-01,0.483952,10.0,5.0
CICIoMT2024_Bluetooth,9.999534e-01,0.931189,5.155764e-02,0.745418,0.632683,0.015121,0.428571,0.994021,1.292438e-13,0.886177,0.965571,0.398488,0.323902,0.711296,4.430884e-01,0.568469,10.0,5.0
CICIoMT2024_WiFi_and_MQTT,9.901643e-01,0.259640,1.456568e-01,0.490625,0.885712,0.206006,0.295455,0.000066,4.769428e-01,0.213208,0.624902,0.318141,0.545859,0.147760,3.450756e-01,0.396348,10.0,5.0
CICIoV2024_Decimal_Macro,9.999989e-01,0.958127,2.491147e-02,0.677100,0.753205,0.017522,0.375000,0.999841,1.485186e-01,0.938872,0.979063,0.351005,0.385364,0.687420,5.436953e-01,0.589310,10.0,5.0
CICIoV2024_Decimal_Micro,9.999995e-01,0.952777,2.211536e-02,0.677674,0.742463,0.021806,0.375000,0.999931,7.425932e-02,0.957317,0.976388,0.349894,0.382135,0.687465,5.157882e-01,0.582334,10.0,5.0
EDGE-IIOTSET_DNN-EdgeIIoT,9.588555e-01,0.705752,2.397037e-01,0.534184,0.772503,0.105087,0.244444,0.525221,6.274710e-01,0.547195,0.832304,0.386944,0.438795,0.384832,5.873330e-01,0.526042,10.0,5.0
EDGE-IIOTSET_ML-EdgeIIoT,9.905225e-01,0.571808,9.061216e-02,0.665914,0.843454,0.338502,0.219512,0.944743,6.247728e-01,0.058823,0.781165,0.378263,0.590978,0.582128,3.417981e-01,0.534866,10.0,5.0
MQTT_IoT_IDS2020_BiflowFeatures,9.673835e-01,0.308484,7.554761e-02,0.646521,0.709325,0.006592,0.142857,0.975421,1.615517e-01,0.308875,0.637934,0.361034,0.357958,0.559139,2.352132e-01,0.430256,10.0,5.0
MQTT_IoT_IDS2020_PacketFeatures,9.999873e-01,0.297269,2.464260e-02,0.704571,0.802848,0.194654,0.411765,0.996902,4.521913e-01,0.154540,0.648628,0.364607,0.498751,0.704334,3.033656e-01,0.503937,10.0,5.0
MQTT_IoT_IDS2020_UniflowFeatures,9.997424e-01,0.400214,5.368856e-02,0.638872,0.688483,0.008778,0.250000,0.963075,2.948444e-01,0.390433,0.699978,0.346280,0.348630,0.606537,3.426387e-01,0.468813,10.0,5.0
NIDS_CIC-BoT-IoT,9.994147e-01,0.934435,3.869899e-01,0.265044,0.962179,0.405674,0.139241,0.804990,7.927159e-01,0.324571,0.966925,0.326017,0.683927,0.472115,5.586437e-01,0.601525,10.0,5.0
NIDS_CIC-ToN-IoT,9.992485e-01,0.797496,1.080333e-01,0.282229,0.841053,0.222503,0.225352,0.854955,3.186397e-01,0.491426,0.898372,0.195131,0.531778,0.540154,4.050330e-01,0.514094,10.0,5.0
NIDS_NF-BoT-IoT,9.999136e-01,0.845027,5.524115e-02,0.710901,0.938690,0.457547,0.500000,0.982745,7.618958e-01,0.234256,0.922470,0.383071,0.698119,0.741373,4.980758e-01,0.648622,10.0,5.0
NIDS_NF-BoT-IoT-v2,9.998018e-01,0.648105,8.122462e-02,0.454383,0.862591,0.235514,0.421053,0.972101,5.456977e-01,0.181790,0.823954,0.267804,0.549053,0.696577,3.637438e-01,0.540226,10.0,5.0
NIDS_NF-BoT-IoT-v3,9.993187e-01,0.838307,3.071614e-01,0.447938,0.895002,0.224528,0.347826,0.847979,4.275848e-01,0.430602,0.918813,0.377549,0.559765,0.597903,4.290935e-01,0.576625,10.0,5.0
NIDS_NF-CICIDS2018-v3,9.979488e-01,0.822935,4.924437e-01,0.362760,0.774919,0.016076,0.311111,0.429903,2.299139e-01,0.825319,0.910442,0.427602,0.395498,0.370507,5.276163e-01,0.526333,10.0,5.0
NIDS_NF-CSE-CIC-IDS2018,9.988118e-01,0.741032,1.488631e-01,0.685751,0.819745,0.109968,0.400000,0.847841,5.152137e-02,0.771732,0.869922,0.417307,0.464856,0.623920,4.116264e-01,0.557526,10.0,5.0
NIDS_NF-CSE-CIC-IDS2018-v2,9.972093e-01,0.570009,2.934940e-01,0.475589,0.782013,0.029088,0.432432,0.681455,1.984773e-01,0.655540,0.783609,0.384541,0.405550,0.556944,4.270086e-01,0.511531,10.0,5.0
NIDS_NF-ToN-IoT,9.996490e-01,0.832900,2.254714e-02,0.740245,0.956721,0.515314,0.500000,0.985307,3.709058e-01,0.363437,0.916275,0.381396,0.736018,0.742654,3.671713e-01,0.628703,10.0,5.0
NIDS_NF-ToN-IoT-v2,9.994629e-01,0.758153,9.085365e-02,0.411823,0.903724,0.323974,0.526316,0.942271,6.653717e-01,0.258117,0.878808,0.251339,0.613849,0.734293,4.617442e-01,0.588007,10.0,5.0
NIDS_NF-ToN-IoT-v3,9.979919e-01,0.733631,1.053404e-01,0.396457,0.896143,0.238747,0.413043,0.798797,6.288993e-01,0.303022,0.865811,0.250899,0.567445,0.605920,4.659605e-01,0.551207,10.0,5.0
NIDS_NF-UNSW-NB15,9.999369e-01,0.886361,6.075505e-02,0.665660,0.812733,0.178194,0.500000,0.989751,3.985922e-01,0.758286,0.943149,0.363208,0.495464,0.744876,5.784394e-01,0.625027,10.0,5.0
NIDS_NF-UNSW-NB15-v2,9.999655e-01,0.712018,5.990264e-02,0.347677,0.825116,0.238743,0.315789,0.994593,9.681040e-01,0.554122,0.855992,0.203790,0.531929,0.655191,7.611129e-01,0.601603,10.0,5.0
NIDS_NF-UNSW-NB15-v3,9.971269e-01,0.862882,5.436258e-02,0.330046,0.620502,0.044757,0.239130,0.978180,5.953562e-01,0.828727,0.930004,0.192204,0.332630,0.608655,7.120418e-01,0.555107,10.0,5.0
NIDS_NF-UQ-NIDS,9.999116e-01,0.688482,7.529153e-02,0.691450,0.878791,0.372328,0.600000,0.985005,3.931232e-01,0.571788,0.844197,0.383371,0.625560,0.792503,4.824558e-01,0.625617,10.0,5.0
NIDS_NF-UQ-NIDS-v2,9.995468e-01,0.661143,1.375339e-01,0.431633,0.862838,0.221355,0.500000,0.932424,7.096007e-01,0.472423,0.830345,0.284584,0.542097,0.716212,5.910119e-01,0.592850,10.0,5.0
N_BaIoT_Danmini_Doorbell,8.077890e-01,0.006694,3.557229e-01,0.404863,0.746302,0.030916,0.113043,0.840779,2.319586e-01,0.201346,0.407241,0.380293,0.388609,0.476911,2.166522e-01,0.373941,10.0,5.0
N_BaIoT_Ecobee_Thermostat,9.870348e-01,0.099721,2.909971e-01,0.371329,0.784277,0.050348,0.095652,0.814317,2.749381e-01,0.207924,0.543378,0.331163,0.417312,0.454985,2.414313e-01,0.397654,10.0,5.0
N_BaIoT_Ennio_Doorbell,9.971145e-01,0.315551,6.713064e-01,0.374658,0.791202,0.110401,0.184348,0.941012,2.669636e-01,0.239961,0.656332,0.522982,0.450801,0.562680,2.534625e-01,0.489252,10.0,5.0
N_BaIoT_Philips_B120N10_Baby_Monitor,9.926977e-01,0.037358,1.848409e-01,0.387385,0.784786,0.047994,0.121739,0.824147,3.254043e-01,0.188952,0.515028,0.286113,0.416390,0.472943,2.571782e-01,0.389530,10.0,5.0
N_BaIoT_Provision_PT_737E_Security_Camera,9.959631e-01,0.144506,1.954969e-01,0.356927,0.771526,0.060557,0.086957,0.901268,2.708535e-01,0.161252,0.570235,0.276212,0.416041,0.494112,2.160526e-01,0.394531,10.0,5.0
N_BaIoT_Provision_PT_838_Security_Camera,9.988122e-01,0.120344,1.891862e-01,0.307433,0.745268,0.078514,0.086957,0.902893,3.318023e-01,0.178743,0.559578,0.248310,0.411891,0.494925,2.552727e-01,0.393995,10.0,5.0
N_BaIoT_Samsung_SNH_1011_N_Webcam,9.949719e-01,0.179009,3.200131e-01,0.424713,0.782675,0.123299,0.156522,0.866647,3.443983e-01,0.251406,0.586991,0.372363,0.452987,0.511585,2.979023e-01,0.444365,10.0,5.0
N_BaIoT_SimpleHome_XCS7_1002_WHT_Security_Camera,9.887168e-01,0.010781,2.074122e-01,0.366233,0.776141,0.043414,0.113043,0.882608,2.846214e-01,0.182630,0.499749,0.286822,0.409778,0.497826,2.336257e-01,0.385560,10.0,5.0
N_BaIoT_SimpleHome_XCS7_1003_WHT_Security_Camera,9.803270e-01,0.097767,2.969757e-01,0.368652,0.775694,0.046191,0.139130,0.885114,2.894869e-01,0.201055,0.539047,0.332814,0.410942,0.512122,2.452711e-01,0.408039,10.0,5.0
ToN_IoT_IoT_Fridge,1.000000e+00,1.000000,1.645835e-11,0.824563,0.829680,0.935760,1.000000,1.000000,5.607459e-13,0.000000,1.000000,0.412282,0.882720,1.000000,2.803729e-13,0.659000,10.0,5.0
ToN_IoT_IoT_GPS_Tracker,9.999987e-01,0.123756,2.156991e-04,0.859844,0.998435,0.699793,0.500000,0.999557,5.738479e-12,0.300242,0.561877,0.430030,0.849114,0.749778,1.501211e-01,0.548184,10.0,5.0
ToN_IoT_IoT_Garage_Door,1.000000e+00,0.787961,1.271221e-03,0.974095,0.867351,0.982230,0.500000,0.999992,4.262451e-11,0.017440,0.893981,0.487683,0.924791,0.749996,8.720249e-03,0.613034,10.0,5.0
ToN_IoT_IoT_Modbus,1.000000e+00,0.996904,1.950573e-03,0.738486,0.859097,0.345178,1.000000,0.999994,8.316264e-14,0.599356,0.998452,0.370218,0.602137,0.999997,2.996782e-01,0.654096,10.0,5.0
ToN_IoT_IoT_Motion_Light,1.000000e+00,1.000000,0.000000e+00,1.000000,0.819746,1.000000,0.000000,1.000000,4.546894e-11,0.000000,1.000000,0.500000,0.909873,0.500000,2.273447e-11,0.581975,8.0,4.0
ToN_IoT_IoT_Thermostat,9.999858e-01,0.881294,5.590344e-03,0.829815,0.903940,0.645457,0.500000,0.998657,2.908224e-01,0.262382,0.940640,0.417703,0.774698,0.749329,2.766020e-01,0.631794,10.0,5.0
ToN_IoT_IoT_Weather,9.999836e-01,0.932591,2.705808e-02,0.784701,0.835196,0.305335,1.000000,0.994067,0.000000e+00,0.686863,0.966287,0.405880,0.570265,0.997033,3.434317e-01,0.656579,10.0,5.0
ToN_IoT_Linux_Disk,9.999899e-01,0.902412,2.563872e-02,0.814753,0.890122,0.453065,0.666667,0.995644,9.709440e-04,0.502506,0.951201,0.420196,0.671593,0.831155,2.517386e-01,0.625177,10.0,5.0
ToN_IoT_Linux_Memory,9.999903e-01,0.931654,3.279572e-02,0.714735,0.865269,0.372665,0.900000,0.996236,6.984788e-02,0.535496,0.965822,0.373765,0.618967,0.948118,3.026721e-01,0.641869,10.0,5.0
ToN_IoT_Linux_Process,9.999869e-01,0.892466,1.960590e-02,0.595096,0.917661,0.444666,0.285714,0.993655,1.842030e-01,0.455410,0.946226,0.307351,0.681164,0.639685,3.198063e-01,0.578846,10.0,5.0
ToN_IoT_Network,9.995619e-01,0.792968,2.800913e-02,0.627802,0.902664,0.375182,0.250000,0.962853,7.200466e-01,0.334798,0.896265,0.327905,0.638923,0.606427,5.274223e-01,0.599388,10.0,5.0
ToN_IoT_Windows_10,9.999887e-01,0.603178,1.747106e-01,0.004695,0.603374,0.039766,0.306037,0.996328,1.412207e-01,0.490952,0.801583,0.089703,0.321570,0.651182,3.160864e-01,0.436025,10.0,5.0
ToN_IoT_Windows_7,9.999939e-01,0.700563,2.257194e-01,0.098756,0.685226,0.031286,0.259615,0.997587,9.965135e-02,0.603416,0.850278,0.162237,0.358256,0.628601,3.515335e-01,0.470181,10.0,5.0

In [11]:
cols_to_drop = [
    "Feature_Relevance_difficulty", "Local_Overlap_difficulty", 
    "Boundary_Hardness_difficulty", "Global_Structure_difficulty", 
    "Class_Distribution_Separation_difficulty", 
    "metrics_used", "groups_used"
]

df_ordered_pretty = {}

for frac in SAMPLE_FRACS:

    try:
        df_ordered_pretty[frac] = format_and_color_columns(
            df_ordered[frac].drop(columns=cols_to_drop).loc[valid_order],
            color_map_dict={'overall_difficulty': 'RdYlGn_r'},
            alpha=0.5
        )
    
        with open(f"tables/table_2_{frac}.tex", "w") as f:
            f.write(df_ordered_pretty[frac].to_string())

    except Exception as e:
        print('error', e)
        continue
    
df_ordered_pretty['full']

error 'sampled_05'

/tmp/ipykernel_3612/3793402051.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '\cellcolor[rgb]{0.966, 0.986, 0.829} 0.510' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df_colored.loc[i, col] = (
/tmp/ipykernel_3612/3793402051.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '\cellcolor[rgb]{0.955, 0.981, 0.813} 0.514' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df_colored.loc[i, col] = (
/tmp/ipykernel_3612/3793402051.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '\cellcolor[rgb]{0.978, 0.991, 0.845} 0.517' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df_colored.loc[i, col] = (
/tmp/ipykernel_3612/3793402051.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '\cellcolor[rgb]{0.981, 0.992, 0.849} 0.507' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df_colored.loc[i, col] = (
/tmp/ipykernel_3612/3793402051.py:37: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '\cellcolor[rgb]{0.999, 0.973, 0.829} 0.512' has dtype incompatible with float32, please explicitly cast to a compatible dtype first.
  df_colored.loc[i, col] = (

,anova_f_mean,mutual_info_mean,pca_centroid_distance_pca_centroid_score,mahalanobis_class_distance_mean,svm_margin_mean,class_proba_entropy_mean,intrinsic_dimensionality_intrinsic_dimensionality_percent,calinski_harabasz_calinski_harabasz_score,class_confusion_entropy_confusion_entropy,class_imbalance_normalized_entropy,overall_difficulty
dataset_id,,,,,,,,,,,
CIC_IDS_2017,1.000,0.781,0.191,0.171,0.752,0.013,0.186,0.963,0.299,0.762,"\cellcolor[rgb]{0.999, 0.973, 0.829} 0.512"
CIC_IOT_Dataset2023,0.996,0.252,0.125,0.392,0.928,0.422,0.333,0.232,0.764,0.143,"\cellcolor[rgb]{0.906, 0.960, 0.760} 0.459"
IoT_23,1.000,0.811,0.320,0.719,0.801,0.111,0.500,0.996,0.577,0.765,"\cellcolor[rgb]{0.824, 0.500, 0.575} 0.660"
IoT_Network_Intrusion_Macro,1.000,0.960,0.039,0.576,0.826,0.177,0.192,0.998,0.339,0.706,"\cellcolor[rgb]{0.986, 0.769, 0.657} 0.581"
IoT_Network_Intrusion_Micro,1.000,0.956,0.047,0.578,0.831,0.180,0.192,0.999,0.198,0.796,"\cellcolor[rgb]{0.988, 0.784, 0.664} 0.578"
KDD_Cup_1999,0.990,0.731,0.103,0.548,0.737,0.008,0.200,0.845,0.381,0.790,"\cellcolor[rgb]{0.998, 0.932, 0.766} 0.533"
UNSW_NB15,0.999,0.938,0.065,0.289,0.667,0.032,0.200,0.952,0.997,0.886,"\cellcolor[rgb]{0.965, 0.686, 0.618} 0.602"
BCCC_CIC-BCCC-NRC-ACI-IOT-2023,1.000,0.804,0.054,0.362,0.925,0.510,0.274,0.991,0.595,0.237,"\cellcolor[rgb]{0.989, 0.789, 0.666} 0.575"
BCCC_CIC-BCCC-NRC-Edge-IIoTSet-2022,0.996,0.782,0.226,0.500,0.712,0.012,0.174,0.743,0.298,0.752,"\cellcolor[rgb]{0.999, 0.961, 0.809} 0.520"
BCCC_CIC-BCCC-NRC-IoMT-2024,1.000,0.683,0.200,0.301,0.833,0.166,0.219,0.930,0.737,0.453,"\cellcolor[rgb]{0.997, 0.874, 0.718} 0.552"
BCCC_CIC-BCCC-NRC-IoT-2022,1.000,0.983,0.092,0.301,0.032,0.003,0.264,0.998,0.097,0.901,"\cellcolor[rgb]{0.928, 0.970, 0.777} 0.467"
BCCC_CIC-BCCC-NRC-IoT-2023-Original_Training_and_Testing,0.999,0.603,0.110,0.416,0.773,0.055,0.268,0.926,0.550,0.398,"\cellcolor[rgb]{0.999, 0.977, 0.837} 0.510"
BCCC_CIC-BCCC-NRC-IoT-HCRL-2019,1.000,0.739,0.186,0.566,0.811,0.139,0.260,0.984,0.822,0.432,"\cellcolor[rgb]{0.979, 0.719, 0.634} 0.594"
BCCC_CIC-BCCC-NRC-MQTTIoT-IDS-2020,0.988,0.171,0.067,0.358,0.701,0.043,0.101,0.014,0.478,0.441,"\cellcolor[rgb]{0.500, 0.704, 0.608} 0.336"
BCCC_CIC-BCCC-NRC-TONIoT-2021,1.000,0.903,0.082,0.313,0.684,0.053,0.239,0.949,0.663,0.668,"\cellcolor[rgb]{0.997, 0.862, 0.708} 0.555"
BCCC_CIC-BCCC-NRC-UQ-IOT-2022,0.999,0.907,0.624,0.452,0.738,0.018,0.203,0.911,0.413,0.466,"\cellcolor[rgb]{0.990, 0.799, 0.671} 0.573"
BoT_IoT_Macro,0.999,0.905,0.196,0.575,0.931,0.281,0.400,0.796,0.557,0.474,"\cellcolor[rgb]{0.949, 0.653, 0.603} 0.611"
BoT_IoT_Micro,0.998,0.457,0.210,0.619,0.921,0.254,0.400,0.780,0.579,0.322,"\cellcolor[rgb]{0.997, 0.866, 0.711} 0.554"
CICAPT_IIoT_Phase2_Macro,1.000,1.000,0.028,0.324,0.704,0.000,0.188,1.000,0.000,1.000,"\cellcolor[rgb]{0.998, 0.951, 0.793} 0.524"
CICAPT_IIoT_Phase2_Micro,1.000,1.000,0.040,0.323,0.704,0.000,0.188,1.000,0.000,1.000,"\cellcolor[rgb]{0.998, 0.949, 0.789} 0.525"
CICEVSE2024_EVSE-A_Macro,0.994,0.338,0.989,0.683,0.752,0.098,0.162,0.889,0.497,0.300,"\cellcolor[rgb]{0.992, 0.809, 0.675} 0.570"
CICEVSE2024_EVSE-A_Micro,0.000,0.153,1.000,0.721,0.766,0.096,0.162,0.879,0.356,0.255,"\cellcolor[rgb]{0.843, 0.933, 0.719} 0.439"
CICEVSE2024_EVSE-B_Macro,0.997,0.325,0.272,0.498,0.714,0.105,0.088,0.926,0.588,0.547,"\cellcolor[rgb]{1.000, 0.985, 0.849} 0.506"
CICEVSE2024_EVSE-B_Micro,0.990,0.107,0.225,0.545,0.785,0.148,0.088,0.944,0.602,0.405,"\cellcolor[rgb]{0.966, 0.986, 0.829} 0.484"
CICIoMT2024_Bluetooth,1.000,0.931,0.052,0.745,0.633,0.015,0.429,0.994,0.000,0.886,"\cellcolor[rgb]{0.993, 0.819, 0.680} 0.568"
CICIoMT2024_WiFi_and_MQTT,0.990,0.260,0.146,0.491,0.886,0.206,0.295,0.000,0.477,0.213,"\cellcolor[rgb]{0.677, 0.859, 0.688} 0.396"
CICIoV2024_Decimal_Macro,1.000,0.958,0.025,0.677,0.753,0.018,0.375,1.000,0.149,0.939,"\cellcolor[rgb]{0.981, 0.734, 0.641} 0.589"
CICIoV2024_Decimal_Micro,1.000,0.953,0.022,0.678,0.742,0.022,0.375,1.000,0.074,0.957,"\cellcolor[rgb]{0.985, 0.764, 0.654} 0.582"
EDGE-IIOTSET_DNN-EdgeIIoT,0.959,0.706,0.240,0.534,0.773,0.105,0.244,0.525,0.627,0.547,"\cellcolor[rgb]{0.998, 0.946, 0.785} 0.526"
EDGE-IIOTSET_ML-EdgeIIoT,0.991,0.572,0.091,0.666,0.843,0.339,0.220,0.945,0.625,0.059,"\cellcolor[rgb]{0.998, 0.924, 0.760} 0.535"
MQTT_IoT_IDS2020_BiflowFeatures,0.967,0.308,0.076,0.647,0.709,0.007,0.143,0.975,0.162,0.309,"\cellcolor[rgb]{0.813, 0.920, 0.706} 0.430"
MQTT_IoT_IDS2020_PacketFeatures,1.000,0.297,0.025,0.705,0.803,0.195,0.412,0.997,0.452,0.155,"\cellcolor[rgb]{1.000, 0.989, 0.857} 0.504"
MQTT_IoT_IDS2020_UniflowFeatures,1.000,0.400,0.054,0.639,0.688,0.009,0.250,0.963,0.295,0.390,"\cellcolor[rgb]{0.931, 0.971, 0.781} 0.469"
NIDS_CIC-BoT-IoT,0.999,0.934,0.387,0.265,0.962,0.406,0.139,0.805,0.793,0.325,"\cellcolor[rgb]{0.967, 0.690, 0.621} 0.602"
NIDS_CIC-ToN-IoT,0.999,0.797,0.108,0.282,0.841,0.223,0.225,0.855,0.319,0.491,"\cellcolor[rgb]{0.999, 0.970, 0.825} 0.514"
NIDS_NF-BoT-IoT,1.000,0.845,0.055,0.711,0.939,0.458,0.500,0.983,0.762,0.234,"\cellcolor[rgb]{0.854, 0.530, 0.575} 0.649"
NIDS_NF-BoT-IoT-v2,1.000,0.648,0.081,0.454,0.863,0.236,0.421,0.972,0.546,0.182,"\cellcolor[rgb]{0.997, 0.908, 0.747} 0.540"
NIDS_NF-BoT-IoT-v3,0.999,0.838,0.307,0.448,0.895,0.225,0.348,0.848,0.428,0.431,"\cellcolor[rgb]{0.988, 0.784, 0.664} 0.577"
NIDS_NF-CICIDS2018-v3,0.998,0.823,0.492,0.363,0.775,0.016,0.311,0.430,0.230,0.825,"\cellcolor[rgb]{0.998, 0.946, 0.785} 0.526"
NIDS_NF-CSE-CIC-IDS2018,0.999,0.741,0.149,0.686,0.820,0.110,0.400,0.848,0.052,0.772,"\cellcolor[rgb]{0.996, 0.855, 0.701} 0.558"
NIDS_NF-CSE-CIC-IDS2018-v2,0.997,0.570,0.293,0.476,0.782,0.029,0.432,0.681,0.198,0.656,"\cellcolor[rgb]{0.999, 0.975, 0.833} 0.512"
NIDS_NF-ToN-IoT,1.000,0.833,0.023,0.740,0.957,0.515,0.500,0.985,0.371,0.363,"\cellcolor[rgb]{0.916, 0.589, 0.576} 0.629"
NIDS_NF-ToN-IoT-v2,0.999,0.758,0.091,0.412,0.904,0.324,0.526,0.942,0.665,0.258,"\cellcolor[rgb]{0.982, 0.739, 0.643} 0.588"
NIDS_NF-ToN-IoT-v3,0.998,0.734,0.105,0.396,0.896,0.239,0.413,0.799,0.629,0.303,"\cellcolor[rgb]{0.997, 0.874, 0.718} 0.551"
NIDS_NF-UNSW-NB15,1.000,0.886,0.061,0.666,0.813,0.178,0.500,0.990,0.399,0.758,"\cellcolor[rgb]{0.925, 0.601, 0.580} 0.625"
NIDS_NF-UNSW-NB15-v2,1.000,0.712,0.060,0.348,0.825,0.239,0.316,0.995,0.968,0.554,"\cellcolor[rgb]{0.967, 0.690, 0.621} 0.602"
NIDS_NF-UNSW-NB15-v3,0.997,0.863,0.054,0.330,0.621,0.045,0.239,0.978,0.595,0.829,"\cellcolor[rgb]{0.997, 0.862, 0.708} 0.555"
NIDS_NF-UQ-NIDS,1.000,0.688,0.075,0.691,0.879,0.372,0.600,0.985,0.393,0.572,"\cellcolor[rgb]{0.925, 0.601, 0.580} 0.626"
NIDS_NF-UQ-NIDS-v2,1.000,0.661,0.138,0.432,0.863,0.221,0.500,0.932,0.710,0.472,"\cellcolor[rgb]{0.980, 0.724, 0.636} 0.593"
N_BaIoT_Danmini_Doorbell,0.808,0.007,0.356,0.405,0.746,0.031,0.113,0.841,0.232,0.201,"\cellcolor[rgb]{0.571, 0.808, 0.662} 0.374"
N_BaIoT_Ecobee_Thermostat,0.987,0.100,0.291,0.371,0.784,0.050,0.096,0.814,0.275,0.208,"\cellcolor[rgb]{0.682, 0.862, 0.690} 0.398"
N_BaIoT_Ennio_Doorbell,0.997,0.316,0.671,0.375,0.791,0.110,0.184,0.941,0.267,0.240,"\cellcolor[rgb]{0.981, 0.992, 0.849} 0.489"
N_BaIoT_Philips_B120N10_Baby_Monitor,0.993,0.037,0.185,0.387,0.785,0.048,0.122,0.824,0.325,0.189,"\cellcolor[rgb]{0.647, 0.845, 0.681} 0.390"
N_BaIoT_Provision_PT_737E_Security_Camera,0.996,0.145,0.195,0.357,0.772,0.061,0.087,0.901,0.271,0.161,"\cellcolor[rgb]{0.671, 0.856, 0.687} 0.395"
N_BaIoT_Provision_PT_838_Security_Camera,0.999,0.120,0.189,0.307,0.745,0.079,0.087,0.903,0.332,0.179,"\cellcolor[rgb]{0.665, 0.854, 0.685} 0.394"
N_BaIoT_Samsung_SNH_1011_N_Webcam,0.995,0.179,0.320,0.425,0.783,0.123,0.157,0.867,0.344,0.251,"\cellcolor[rgb]{0.859, 0.940, 0.729} 0.444"
N_BaIoT_SimpleHome_XCS7_1002_WHT_Security_Camera,0.989,0.011,0.207,0.366,0.776,0.043,0.113,0.883,0.285,0.183,"\cellcolor[rgb]{0.630, 0.836, 0.677} 0.386"
N_BaIoT_SimpleHome_XCS7_1003_WHT_Security_Camera,0.980,0.098,0.297,0.369,0.776,0.046,0.139,0.885,0.289,0.201,"\cellcolor[rgb]{0.725, 0.881, 0.697} 0.408"
ToN_IoT_IoT_Fridge,1.000,1.000,0.000,0.825,0.830,0.936,1.000,1.000,0.000,0.000,"\cellcolor[rgb]{0.824, 0.500, 0.575} 0.659"
ToN_IoT_IoT_GPS_Tracker,1.000,0.124,0.000,0.860,0.998,0.700,0.500,1.000,0.000,0.300,"\cellcolor[rgb]{0.997, 0.885, 0.727} 0.548"
ToN_IoT_IoT_Garage_Door,1.000,0.788,0.001,0.974,0.867,0.982,0.500,1.000,0.000,0.017,"\cellcolor[rgb]{0.947, 0.648, 0.601} 0.613"
ToN_IoT_IoT_Modbus,1.000,0.997,0.002,0.738,0.859,0.345,1.000,1.000,0.000,0.599,"\cellcolor[rgb]{0.839, 0.515, 0.575} 0.654"
ToN_IoT_IoT_Motion_Light,1.000,1.000,0.000,1.000,0.820,1.000,0.000,1.000,0.000,0.000,"\cellcolor[rgb]{0.985, 0.764, 0.654} 0.582"
ToN_IoT_IoT_Thermostat,1.000,0.881,0.006,0.830,0.904,0.645,0.500,0.999,0.291,0.262,"\cellcolor[rgb]{0.908, 0.581, 0.576} 0.632"
ToN_IoT_IoT_Weather,1.000,0.933,0.027,0.785,0.835,0.305,1.000,0.994,0.000,0.687,"\cellcolor[rgb]{0.831, 0.507, 0.575} 0.657"
ToN_IoT_Linux_Disk,1.000,0.902,0.026,0.815,0.890,0.453,0.667,0.996,0.001,0.503,"\cellcolor[rgb]{0.925, 0.601, 0.580} 0.625"
ToN_IoT_Linux_Memory,1.000,0.932,0.033,0.715,0.865,0.373,0.900,0.996,0.070,0.535,"\cellcolor[rgb]{0.877, 0.552, 0.576} 0.642"
ToN_IoT_Linux_Process,1.000,0.892,0.020,0.595,0.918,0.445,0.286,0.994,0.184,0.455,"\cellcolor[rgb]{0.987, 0.779, 0.661} 0.579"
ToN_IoT_Network,1.000,0.793,0.028,0.628,0.903,0.375,0.250,0.963,0.720,0.335,"\cellcolor[rgb]{0.970, 0.695, 0.623} 0.599"
ToN_IoT_Windows_10,1.000,0.603,0.175,0.005,0.603,0.040,0.306,0.996,0.141,0.491,"\cellcolor[rgb]{0.831, 0.928, 0.712} 0.436"
ToN_IoT_Windows_7,1.000,0.701,0.226,0.099,0.685,0.031,0.260,0.998,0.100,0.603,"\cellcolor[rgb]{0.934, 0.972, 0.785} 0.470"

In [12]:
styled_df = {}

for frac in SAMPLE_FRACS:

    print(frac)

    try:

        # Compute min and max of overall_difficulty
        vmin = df_ordered[frac]['overall_difficulty'].min()
        vmax = df_ordered[frac]['overall_difficulty'].max()
        
        # Select and style (don't include 'dataset_id' as it's now the index)
        styled_df[frac] = df_ordered[frac][['overall_difficulty', 'metrics_used', 'groups_used']].style \
            .background_gradient(subset=['overall_difficulty'], cmap='RdYlGn_r', vmin=vmin, vmax=vmax) \
            .format({'overall_difficulty': '{:.3f}'})

    except Exception as e:
        print('error', e)
    
styled_df['full']

sampled_05
error 'sampled_05'
sampled_10
sampled_20
sampled_25
sampled_50
full